// config.bin - 13:05:11 06/17/17, generated in 0.23 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define true	1
#define false	0

#define private		0
#define protected		1
#define public		2

#define VSoft		0
#define VArmor		1
#define VAir		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#include "CfgPatches.hpp"
#include "ItemActions.hpp"
#include "CfgMovesBasic.hpp"
#include "CfgGesturesMale.hpp"
#include "Mode_SemiAuto.hpp"
#include "DZ_SingleMelee.hpp"
#include "CfgRecoils.hpp"
#include "cfgWeapons.hpp"
#include "cfgMagazines.hpp"
#include "CfgCloudlets.hpp"
#include "FlareSparks.hpp"
#include "GlassSmash.hpp"
#include "cfgAmmo.hpp"
#include "CfgVehicles.hpp"
