// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class All {};
	
	class AllVehicles : All {};
	
	class Land : AllVehicles {};
	
	class LandVehicle : Land {};
	
	class Car : LandVehicle {
		class Exhausts;	// External class reference
		class AnimationSources;	// External class reference
		
		class HitPoints {
			class HitLFWheel;	// External class reference
			class HitLBWheel;	// External class reference
			class HitLMWheel;	// External class reference
			class HitLF2Wheel;	// External class reference
			class HitRFWheel;	// External class reference
			class HitRBWheel;	// External class reference
			class HitRMWheel;	// External class reference
			class HitRF2Wheel;	// External class reference
		};
	};
	
	class Car_sedan : Car {};
	
	class Copcar : Car_sedan {
		scope = public;
		vehicleClass = "Monaro";
		displayName = "Holden Monaro Cop (Basic)";
		picture = "\Holdenmonarocop\icons\picture.pac";
		icon = "\Holdenmonarocop\icons\icon.pac";
		model = "\Holdenmonarocop\Copcar";
		accuracy = 0.9;	// accuracy needed to recognize type of this target
		canlock = LockCadet;
		crew = "Doctor";
		side = TCivilian;
		type = VArmor;
		typicalCargo[] = {};
		cargoIsCoDriver[] = {1, 0};
		magazines[] = {};
		unloadInCombat = false;
		
		class TransportWeapons {};
		transportSoldier = 3;
		transportMaxMagazines = 0;
		transportMaxWeapons = 0;
		viewCargoShadow = true;
		maxSpeed = 209;	// max speed on level road, km/h
		turnCoef = 1.95;
		terrainCoef = 3.55;
		brakeDistance = 20.0;	// vehicle movement precision
		cost = 30000;
		fuelCapacity = 35;
		armorWheels = 0.07;
		armor = 18;
		armorStructural = 8.0;
		armorEngine = 2.2;
		soundEngine[] = {"\Holdenmonarocop\sounds\engine.wav", 0.1, 1};
		selectionBrakeLights = "BLight";
		selectionBackLights = "Blight";
		
		class Exhausts {
			class exhaust1 {
				position = "vyfuk start";
				direction = "vyfuk konec";
				effect = "ExhaustsEffect";
			};
			
			class exhaust2 : exhaust1 {
				position = "exhaust2start";
				direction = "exhaust2end";
			};
		};
		
		class Library {
			libTextDesc = "Holden Monaro.";
		};
		
		class HitPoints : HitPoints {
			class HitEngine {
				armor = 0.4;
				material = 60;
				name = "motor";
				visual = "motor";
				passThrough = true;
			};
			
			class HitBody {
				armor = 1;
				material = 51;
				name = "karoserie";
				visual = "karoserie";
				passThrough = true;
			};
			
			class HitFuel {
				armor = 0.3;
				material = 51;
				name = "palivo";
				passThrough = true;
			};
			
			class HitLFWheel {
				armor = 0.38;
				material = -1;
				name = "levy predni tlumic";
				visual = "levy predni tlumic";
				passThrough = false;
			};
			
			class HitRFWheel {
				armor = 0.38;
				material = -1;
				name = "pravy predni tlumic";
				visual = "pravy predni tlumic";
				passThrough = false;
			};
			
			class HitLBWheel {
				armor = 0.38;
				material = -1;
				name = "levy zadni tlumic";
				visual = "levy zadni tlumic";
				passThrough = false;
			};
			
			class HitRBWheel {
				armor = 0.38;
				material = -1;
				name = "pravy zadni tlumic";
				visual = "pravy zadni tlumic";
				passThrough = false;
			};
			
			class HitGlass1 {
				armor = 0.05;
				material = -1;
				name = "sklo predni L";
				visual = "sklo predni L";
				passThrough = false;
			};
			
			class HitGlass2 : HitGlass1 {
				name = "sklo predni P";
				visual = "sklo predni P";
			};
		};
		dammageHalf[] = {"\Holdenmonarocop\textures\glass.paa", "\Holdenmonarocop\textures\broke_glass.paa"};
		dammageFull[] = {"\Holdenmonarocop\textures\glass.paa", "\Holdenmonarocop\textures\broken_glass.paa"};
		
		class Damage {
			tex[] = {};
			mat[] = {"Holdenmonarocop\textures\skin_1.rvmat", "Holdenmonarocop\textures\skin_1.rvmat", "Holdenmonarocop\textures\destruct.rvmat"};
		};
	};
	
	class Copcarhw : Copcar {
		crew = "Doctor";
		DisplayName = "Holden Monaro Cop (Maroon)";
		model = "\Holdenmonarocop\Copcarhw";
	};
	
	class Copcarswat : Copcar {
		crew = "Doctor";
		DisplayName = "Holden Monaro Cop (Black)";
		model = "\Holdenmonarocop\Copcarswat";
	};
};
