// Generated by unRap v1.06 by Kegetys

class cfgAmmo {
	class GrenadeBase;	// External class reference
	class BulletBase;	// External class reference
	
	class B_7x92_Ball : BulletBase {
		hit = 15;
		indirectHit = 0;
		indirectHitRange = 0;
		visibleFire = 22;	// how much is visible when this weapon is fired
		audibleFire = 18;
		visibleFireTime = 3;	// how long is it visible
		cost = 1.2;
		airLock = true;
	};
	
	class Riflegrenade : GrenadeBase {
		model = "";
		soundHit[] = {"\ca\weapons\data\sound\explosion_small_22_grenade_B", db25, 1};
		soundFly[] = {"\ca\weapons\data\sound\bullet_noise_1", 3.16228e-005, 1};
		supersonicCrackNear[] = {"\ca\Weapons\Data\Sound\supersonic_crack_close.wss", 1, 1};
		supersonicCrackFar[] = {"\ca\Weapons\Data\Sound\supersonic_crack_50meters.wss", 1, 1};
		CraterEffects = "GrenadeCrater";
		explosionEffects = "GrenadeExplosion";
		hit = 13;
		indirectHit = 10;
		indirectHitRange = 5.5;
		visibleFire = 18;	// how much is visible when this weapon is fired
		audibleFire = 18;
		visibleFireTime = 3;	// how long is it visible
		explosive = true;
		cost = 10;
		deflecting = 10;
	};
	
	class Panzergrenade30 : Riflegrenade {
		model = "\gms_k98\panzergrenade.p3d";
		cartridge = "";
	};
};
