// Generated by unRap v1.06 by Kegetys

class CfgMagazines {
	class CA_Magazine;	// External class reference
	
	class gms_k98_mag : CA_Magazine {
		scope = public;
		displayName = $STR_MN_K98;
		initSpeed = 700;
		ammo = "B_7x92_Ball";
		count = 5;
		picture = "\gms_k98\data\equip\m_k98_ca.paa";
		descriptionShort = $STR_DSS_5RND_K98;
	};
	
	class RifleGrenadeMagazine : CA_Magazine {
		scope = protected;
		type = 16;
		initSpeed = 80;
		count = 1;
	};
	
	class panzergrenade : RifleGrenadeMagazine {
		scope = public;
		ammo = "Panzergrenade30";
		displayName = $STR_MN_PNZRGRND30;
		picture = "\gms_k98\data\equip\m_rg_ca.paa";
		modelSpecial = "\gms_k98\gms_k98_gl_loaded.p3d";
		descriptionShort = $STR_DSS_PNZRGRND30;
	};
};
