// config.bin - 13:06:11 06/17/17, generated in 0.12 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define true	1
#define false	0

#define private		0
#define protected		1
#define public		2

#include "CfgPatches.hpp"
#include "cfgAmmo.hpp"
#include "CfgMagazines.hpp"
#include "Mode_SemiAuto.hpp"
#include "Mode_FullAuto.hpp"
#include "cfgWeapons.hpp"
