// Generated by unRap v1.06 by Kegetys

class CfgFactionClasses {
	class ibr_arl_faction {
		displayName = "Lingor Rebels (ARL)";
		priority = 90;
		side = TEast;
	};
	
	class ibr_drg_faction {
		displayName = "Druglord's Army";
		priority = 90;
		side = TEast;
	};
};
