// Generated by unRap v1.06 by Kegetys

class CfgPatches {
	class JetSkiYanahuiAddon {
		units[] = {"JetSkiYanahui", "JetSkiYanahui_Case", "JetSkiYanahui_Case_Green", "JetSkiYanahui_White", "JetSkiYanahui_Red"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"CAData", "CACharacters", "CAWeapons", "CA_Anims_Char"};
		author[] = {"Kol9yN", "Zakat", "Gerasimow9", "YuraPetrov", "zGuba", "A.Karagod", "IceBreakr", "Sahbazz"};
	};
};
