// Generated by unRap v1.06 by Kegetys

class CfgFactionClasses {
	class gsc_stalker_faction {
		displayName = "GSC Stalker Units";
		priority = 100;
		side = TGuerrila;
	};
	
	class gsc_military_faction {
		displayName = "GSC Military Units";
		priority = 100;
		side = TEast;
	};
};
