// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class All;	// External class reference
	class AllVehicles;	// External class reference
	class ThingEffect;	// External class reference
	class Land;	// External class reference
	class Man;	// External class reference
	class CAManBase;	// External class reference
	class RU_Soldier2;	// External class reference
	
	class gsc_military_helmet_wdl : RU_Soldier2 {
		scope = public;
		displayName = "Military 1";
		model = "\gsc_stalker\gsc_military_helmet_wdl.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {"AK_107_pso", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {"AK_107_pso", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_mil_class";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TEast;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_helmet_wdl_AT : RU_Soldier2 {
		scope = public;
		displayName = "Military 1 - AT";
		model = "\gsc_stalker\gsc_military_helmet_wdl.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {"AK_107_kobra", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", RPG7V};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", PG7V, PG7V};
		respawnWeapons[] = {"AK_107_kobra", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_mil_class";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TEast;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_helmet_grey_AT : RU_Soldier2 {
		scope = public;
		displayName = "Military 2 - AT";
		model = "\gsc_stalker\gsc_military_helmet_grey.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {"AK_107_kobra", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", RPG7V};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", PG7V, PG7V};
		respawnWeapons[] = {"AK_107_kobra", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_mil_class";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TEast;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_helmet_wdlSNP : RU_Soldier2 {
		scope = public;
		displayName = "Military 1 - Sniper";
		model = "\gsc_stalker\gsc_military_helmet_wdl.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {"VSS_vintorez", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {"VSS_vintorez", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_mil_class";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TEast;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_helmet_greySNP : RU_Soldier2 {
		scope = public;
		displayName = "Military 2 - Sniper";
		model = "\gsc_stalker\gsc_military_helmet_grey.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {"VSS_vintorez", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {"VSS_vintorez", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "20Rnd_9x39_SP5_VSS", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_mil_class";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TEast;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_helmet_grey : RU_Soldier2 {
		scope = public;
		displayName = "Military 2";
		model = "\gsc_stalker\gsc_military_helmet_grey.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {RPK_74, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"75Rnd_545x39_RPK", "75Rnd_545x39_RPK", "75Rnd_545x39_RPK", "75Rnd_545x39_RPK", "75Rnd_545x39_RPK", "75Rnd_545x39_RPK", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {RPK_74, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"75Rnd_545x39_RPK", "75Rnd_545x39_RPK", "75Rnd_545x39_RPK", "75Rnd_545x39_RPK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_mil_class";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TEast;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_head_grey : RU_Soldier2 {
		scope = public;
		displayName = "Military 2";
		model = "\gsc_stalker\gsc_military_head_grey.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {AKS_74_U, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {AKS_74_U, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_mil_class2";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TEast;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_head_greySNP : RU_Soldier2 {
		scope = public;
		displayName = "Military 2 - Sniper";
		model = "\gsc_stalker\gsc_military_head_grey.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {SVD, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "HandGrenade_east"};
		respawnWeapons[] = {SVD, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "HandGrenade_east"};
		vehicleClass = "gsc_mil_class2";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TEast;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_head_wdlSNP : RU_Soldier2 {
		scope = public;
		displayName = "Military 1 - Sniper";
		model = "\gsc_stalker\gsc_military_head_grey.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {SVD, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "HandGrenade_east"};
		respawnWeapons[] = {SVD, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "10Rnd_762x54_SVD", "HandGrenade_east"};
		vehicleClass = "gsc_mil_class2";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TEast;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_head_wdl : RU_Soldier2 {
		scope = public;
		displayName = "Military 1";
		model = "\gsc_stalker\gsc_military_head_wdl.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {"AK_107_kobra", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {"AK_107_kobra", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_mil_class2";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TEast;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_head_wdl_AT : RU_Soldier2 {
		scope = public;
		displayName = "Military 1 - AT";
		model = "\gsc_stalker\gsc_military_head_wdl.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {"AK_107_kobra", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", RPG7V};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", PG7V, PG7V};
		respawnWeapons[] = {"AK_107_kobra", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_mil_class2";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TEast;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_head_grey_AT : RU_Soldier2 {
		scope = public;
		displayName = "Military 2 - AT";
		model = "\gsc_stalker\gsc_military_head_grey.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {"AK_107_kobra", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", RPG7V};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", PG7V, PG7V};
		respawnWeapons[] = {"AK_107_kobra", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_mil_class2";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TEast;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_scientist1 : RU_Soldier2 {
		scope = public;
		displayName = "Scientist 1";
		model = "\gsc_stalker\gsc_eco_suit.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {"Makarov", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov"};
		respawnWeapons[] = {"Makarov", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov"};
		vehicleClass = "gsc_stalker_class";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TGuerrila;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\scien.rvmat", "gsc_stalker\scien_wound1.rvmat", "gsc_stalker\scien_wound2.rvmat"};
		};
	};
	
	class gsc_scientist1_head : RU_Soldier2 {
		scope = public;
		displayName = "Scientist 1";
		model = "\gsc_stalker\gsc_eco_suit_head.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {"Makarov", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov"};
		respawnWeapons[] = {"Makarov", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov"};
		vehicleClass = "gsc_stalker_class2";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TGuerrila;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\scien.rvmat", "gsc_stalker\scien_wound1.rvmat", "gsc_stalker\scien_wound2.rvmat"};
		};
	};
	
	class gsc_scientist2 : RU_Soldier2 {
		scope = public;
		displayName = "Scientist 2";
		model = "\gsc_stalker\gsc_eco_suit2.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {"Makarov", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov"};
		respawnWeapons[] = {"Makarov", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov"};
		vehicleClass = "gsc_stalker_class";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TGuerrila;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\scien.rvmat", "gsc_stalker\scien_wound1.rvmat", "gsc_stalker\scien_wound2.rvmat"};
		};
	};
	
	class gsc_scientist2_head : RU_Soldier2 {
		scope = public;
		displayName = "Scientist 2";
		model = "\gsc_stalker\gsc_eco_suit2_head.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {"Makarov", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov"};
		respawnWeapons[] = {"Makarov", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov", "8Rnd_9x18_Makarov"};
		vehicleClass = "gsc_stalker_class2";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TGuerrila;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\scien.rvmat", "gsc_stalker\scien_wound1.rvmat", "gsc_stalker\scien_wound2.rvmat"};
		};
	};
	
	class gsc_eco_stalker_mask_fred : RU_Soldier2 {
		scope = public;
		displayName = "Stalker - Flecktarn";
		model = "\gsc_stalker\gsc_eco_stalker_mask_fred.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {AKS_74_U, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {AKS_74_U, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_stalker_class";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TGuerrila;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
	
	class gsc_eco_stalker_head_fred : RU_Soldier2 {
		scope = public;
		displayName = "Stalker - Flecktarn";
		model = "\gsc_stalker\gsc_eco_stalker_head_fred.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {AK_74, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {AK_74, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_stalker_class2";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TGuerrila;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
	
	class gsc_eco_stalker_mask_camo : RU_Soldier2 {
		scope = public;
		displayName = "Stalker - Camo";
		model = "\gsc_stalker\gsc_eco_stalker_mask_camo.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {"AKS_74_pso", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {"AKS_74_pso", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_stalker_class";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TGuerrila;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
	
	class gsc_eco_stalker_head_camo1 : RU_Soldier2 {
		scope = public;
		displayName = "Stalker - Camo";
		model = "\gsc_stalker\gsc_eco_stalker_head_camo1.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {AKS_74_U, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {AKS_74_U, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_stalker_class2";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TGuerrila;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
	
	class gsc_cloth_loner_head : RU_Soldier2 {
		scope = public;
		displayName = "Loner";
		model = "\gsc_stalker\gsc_cloth_loner_head.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {AK_47_M, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {AK_47_M, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_stalker_class";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TGuerrila;
		
		class Wounds {
			tex[] = {};
			mat[] = {};
		};
	};
	
	class gsc_eco_stalker_mask_duty : RU_Soldier2 {
		scope = public;
		displayName = "Stalker - Black";
		model = "\gsc_stalker\gsc_eco_stalker_mask_duty.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {AK_47_M, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {AK_47_M, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_stalker_class";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TGuerrila;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
	
	class gsc_eco_stalker_head_duty : RU_Soldier2 {
		scope = public;
		displayName = "Stalker - Black";
		model = "\gsc_stalker\gsc_eco_stalker_head_duty.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {AKS_74_U, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {AKS_74_U, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_stalker_class2";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TGuerrila;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
	
	class gsc_eco_stalker_mask_neutral : RU_Soldier2 {
		scope = public;
		displayName = "Stalker";
		model = "\gsc_stalker\gsc_eco_stalker_mask.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {AK_74, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {AK_74, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_stalker_class";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TGuerrila;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
	
	class gsc_eco_stalker_head_neutral : RU_Soldier2 {
		scope = public;
		displayName = "Stalker";
		model = "\gsc_stalker\gsc_eco_stalker_head.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {AKS_74_U, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east", "HandGrenade_east"};
		respawnWeapons[] = {AKS_74_U, "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_east", "HandGrenade_east"};
		vehicleClass = "gsc_stalker_class2";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = TGuerrila;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
};
