// Generated by unRap v1.06 by Kegetys

class CfgVehicleClasses {
	class gsc_stalker_class2 {
		displayName = "No Helmet/Cover";
	};
	
	class gsc_mil_class2 {
		displayName = "No Helmet/Cover";
	};
	
	class gsc_mil_class {
		displayName = "Helmet/Cover";
	};
	
	class gsc_stalker_class {
		displayName = "Helmet/Cover";
	};
};
