// config.bin - 13:06:57 06/17/17, generated in 0.07 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define private		0
#define protected		1
#define public		2

#include "CfgPatches.hpp"
#include "CfgVehicleClasses.hpp"
#include "CfgFactionClasses.hpp"
#include "CfgVehicles.hpp"
