// Generated by unRap v1.06 by Kegetys

class CfgAmmo {
	class Default;	// External class reference
	class BulletCore;	// External class reference
	class BulletBase;	// External class reference
	
	class USSR_408ch_base : BulletBase {
		hit = 25;
		indirectHit = 0;
		indirectHitRange = 0;
		visibleFire = 18;	// how much is visible when this weapon is fired
		audibleFire = 18;
		visibleFireTime = 3;	// how long is it visible
		airLock = true;
		cost = 20;
		airFriction = -0.00035;
		caliber = 1.88;
		muzzleEffect = "BIS_Effects_HeavySniper";
	};
};
