// Generated by unRap v1.06 by Kegetys

class CfgMagazines {
	class Default;	// External class reference
	class CA_Magazine;	// External class reference
	
	class USSR_5Rnd_408 : CA_Magazine {
		scope = public;
		displayName = ".408 CheyTac";
		ammo = "USSR_408ch_base";
		count = 5;
		initSpeed = 1600;
		picture = "\CA\weapons\data\Equip\M_107_CA.paa";
		descriptionShort = ".408 CheyTac";
	};
};
