// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class USSR_cheytac {
		units[] = {"USSR_solcheytac", "USSR_solcheytac_sd"};
		weapons[] = {"USSR_cheytacM200", "USSR_cheytacM200_sd"};
		requiredVersion = 1.03;
		requiredAddons[] = {"CAWeapons_Colt1911", "CAWeapons2", "CACharacters2"};
	};
};
