// Generated by unRap v1.06 by Kegetys

class CfgRecoils {
	cheytacRecoil[] = {0, 0, 0, 0.09, 0.08, 0.07, 0.006, -0.04, -0.3, 0.01, 0, 0};
	cheytacRecoilProne[] = {0, 0, 0, 0.1, 0.1, 0.005, 0.05, -0.2, -0.01, 0.05, 0, 0};
};
