// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class FR_AC;	// External class reference
	
	class USSR_solcheytac : FR_AC {
		displayName = "Sniper(CheyTac)";
		vehicleClass = "USSR_cheytacsol";
		weapons[] = {"USSR_cheytacM200", "Colt1911", "NVGoggles", "Binocular", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "HandGrenade_West", "HandGrenade_West", "SmokeShell", "SmokeShell"};
		respawnWeapons[] = {"USSR_cheytacM200", "Colt1911", "NVGoggles", "Binocular", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "HandGrenade_West", "HandGrenade_West", "SmokeShell", "SmokeShell"};
	};
	
	class USSR_solcheytac_sd : FR_AC {
		displayName = "Sniper(CheyTac) SD";
		vehicleClass = "USSR_cheytacsol";
		weapons[] = {"USSR_cheytacM200_sd", M9SD, "NVGoggles", "Binocular", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "15Rnd_9x19_M9SD", "15Rnd_9x19_M9SD", "15Rnd_9x19_M9SD", "15Rnd_9x19_M9SD", "15Rnd_9x19_M9SD", "15Rnd_9x19_M9SD", "HandGrenade_West", "HandGrenade_West", "SmokeShell", "SmokeShell"};
		respawnWeapons[] = {"USSR_cheytacM200_sd", M9SD, "NVGoggles", "Binocular", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "USSR_5Rnd_408", "15Rnd_9x19_M9SD", "15Rnd_9x19_M9SD", "15Rnd_9x19_M9SD", "15Rnd_9x19_M9SD", "15Rnd_9x19_M9SD", "15Rnd_9x19_M9SD", "HandGrenade_West", "HandGrenade_West", "SmokeShell", "SmokeShell"};
	};
};
