// Generated by unRap v1.06 by Kegetys

class CfgWeapons {
	class Rifle;	// External class reference
	
	class USSR_cheytacM200 : Rifle {
		scope = public;
		type = 5;
		model = "\USSR_m200\m200cht.p3d";
		displayName = "CheyTac M200";
		descriptionShort = "CheyTac M200 Intervention";
		dexterity = 0.45;
		modelOptics = "\USSR_m200\optika_nightforce.p3d";
		opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
		opticsFlare = true;
		opticsDisablePeripherialVision = true;
		optics = true;
		opticsZoomMin = 0.02;
		opticsZoomMax = 0.12;
		distanceZoomMin = 300;
		distanceZoomMax = 300;
		picture = "\USSR_m200\data\w_m200_ca.paa";
		UiPicture = "\CA\weapons\data\Ico\i_sniper_CA.paa";
		magazines[] = {"USSR_5Rnd_408"};
		reloadMagazineSound[] = {"\ca\Weapons\Data\Sound\M21_reload_v4", 0.0316228, 1};
		begin1[] = {"ca\sounds\weapons\rifles\m107", 1.51189, 1, 1300};
		soundBegin[] = {"begin1", 1};
		autoFire = false;
		reloadTime = 2;
		dispersion = 3e-005;
		minRange = 2;
		minRangeProbab = 0.1;
		midRange = 1200;
		midRangeProbab = 0.7;
		maxRange = 1800;
		maxRangeProbab = 0.05;
		recoil = "cheytacRecoil";
		recoilProne = "cheytacRecoilProne";
		
		class Library {
			libTextDesc = "CheyTac M200 Intervention";
		};
	};
	
	class USSR_cheytacM200_sd : USSR_cheytacM200 {
		model = "\USSR_m200\m200chtSD.p3d";
		displayName = "CheyTac M200 SD";
		descriptionShort = "CheyTac M200 Intervention SD";
		modelOptics = "\USSR_m200\optika_nightforce_sd.p3d";
		picture = "\USSR_m200\data\w_m200_sd_ca.paa";
		UiPicture = "\CA\weapons\data\Ico\i_sniper_CA.paa";
		begin1[] = {"\USSR_m200\data\sound\chtSD.ogg", 1.77928, 1, 1000};
		begin2[] = {"\USSR_m200\data\sound\chtSD.ogg", 1.77928, 1, 1000};
		soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		
		class Library {
			libTextDesc = "CheyTac M200 Intervention SD";
		};
	};
};
