// Generated by unRap v1.06 by Kegetys

class CfgMovesMaleSdr : CfgMovesBasic {
	class States {
		class AmovPercMstpSlowWrflDnon : StandBase {};
		
		class AmovPercMstpSlowWrflDnon_AmovPercMevaSrasWrflDl : AmovPercMstpSlowWrflDnon {
			ConnectTo[] = {};
		};
		
		class AmovPercMstpSrasWrflDnon : AmovPercMstpSlowWrflDnon {};
		
		class AmovPercMstpSrasWrflDnon_AmovPercMevaSrasWrflDr : AmovPercMstpSrasWrflDnon {
			ConnectTo[] = {};
		};
	};
};
