// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class st_evasive {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"CA_Anims", "CA_Anims_Sdr", "CA_Anims_Wmn"};
	};
};
