// Generated by unRap v1.06 by Kegetys

class CfgAmmo {
	class BulletBase;	// External class reference
	
	class DDOPP_B_Taser : BulletBase {
		hit = 0.55;
		airFriction = -0.15;
		caliber = 0.3;
		
		class HitEffects {
			Hit_Blood = "ImpactBlood";
		};
	};
};
