// Generated by unRap v1.06 by Kegetys

class CfgMagazines {
	class CA_Magazine;	// External class reference
	
	class DDOPP_Nothing : CA_Magazine {
		scope = protected;
		value = 0;
		displayName = "";
		model = "\ca\weapons\mag_univ.p3d";
		picture = "";
		modelSpecial = "";
		useAction = false;
		useActionTitle = "";
		reloadAction = "ManActReloadMagazine";
		ammo = "";
		count = 0;
		initSpeed = 900;
		selectionFireAnim = "zasleh";
		nameSound = "magazine";
		maxLeadSpeed = 23;	// max estimated speed km/h
	};
	
	class DDOPP_1Rnd_X26 : CA_Magazine {
		scope = public;
		model = "DDOPP_taserPack\taser_x26\DDOPP_x26_mag";
		picture = "\DDOPP_taserPack\taser_x26\m_x26.paa";
		type = 16;
		initSpeed = 85;
		ammo = "DDOPP_B_Taser";
		selectionFireAnim = "zasleh";
		count = 1;
		displayName = "X26 Cartridge";
		descriptionShort = "X26 Taser Stun Cartridge. Holds 1 round. Use in the X26 Taser.";
	};
	
	class DDOPP_3Rnd_X3 : DDOPP_1Rnd_X26 {
		model = "DDOPP_taserPack\taser_x3\DDOPP_x3_mag";
		picture = "\DDOPP_taserPack\taser_x3\m_x3.paa";
		ammo = "DDOPP_B_Taser";
		count = 3;
		displayName = "X3 Cartridges";
		descriptionShort = "X3 Set of 3 Taser Stun Cartridges. Holds 3 rounds. Use in the X3 Taser.";
	};
};
