// Generated by unRap v1.06 by Kegetys

class CfgMods {
	class DDOPP_TaserMod {
		dir = "Expansion";
		name = "Double Doppler's Taser Mod";
		picture = "ca\ui\data\logo_arma2ep1_ca.paa";
		hidePicture = 0;
		hideName = 1;
		action = "http://www.arma2.com/arrowhead";
	};
};
