// Generated by unRap v1.06 by Kegetys

class CfgSounds {
	class taser_hit {
		sound[] = {"\DDOPP_taserPack\Taser_Hit.wav", 0.1, 1};
		name = "taser_hit";
		titles[] = {};
	};
	
	class taser_spark {
		sound[] = {"\DDOPP_taserPack\Taser_Spark.wav", 0.1, 1};
		name = "taser_spark";
		titles[] = {};
	};
};
