// config.bin - 19:05:26 03/25/13, generated in 0.07 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

#define VSoft		0
#define VArmor		1
#define VAir		2

#include "CfgPatches.hpp"
#include "CfgMods.hpp"
class Mode_SemiAuto;	// External class reference
class Mode_FullAuto;	// External class reference
class GrenadeLauncher;	// External class reference
#include "CfgAmmo.hpp"
#include "CfgMagazines.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicleClasses.hpp"
#include "CfgVehicles.hpp"
#include "CfgSounds.hpp"
class RscText;	// External class reference
class RscEdit;	// External class reference
class RscShortcutButton;	// External class reference
class RscControlsGroup;	// External class reference
class RscListBox;	// External class reference
#include "RscTitles.hpp"
