// Generated by unRap v1.06 by Kegetys

class RscTitles {
	class RscPicture {
		type = VSoft;
		idc = -1;
		style = 48;
		colorBackground[] = {1, 1, 1, 1};
		colorText[] = {1, 1, 1, 1};
		font = "Zeppelin32";
		sizeEx = 0.02;
		text = "";
	};
	
	class taser_hit_fx {
		name = "taser_hit_fx";
		duration = 5;
		idd = -1;
		movingEnable = 0;
		controls[] = {"taser_hit_fx"};
		
		class taser_hit_fx : RscPicture {
			text = "DDOPP_taserPack\data\taser_hit_fx.paa";
			x = "-0.000481755 * safezoneW + safezoneX";
			y = "6.49715e-006 * safezoneH + safezoneY";
			w = "1.0003 * safezoneW";
			h = "1.00067 * safezoneH";
		};
	};
};
