// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class Thing;	// External class reference
	class Building;	// External class reference
	class Strategic;	// External class reference
	
	class NonStrategic : Building {
		class DestructionEffects;	// External class reference
	};
	class Ruins;	// External class reference
	
	class land_PBstadS_ruins : Ruins {
		displayName = "Apex Ruins";
		vehicleClass = "Oz_Is_Objects";
		scope = public;
		model = "\PAF_stad_obj\PBstadS_ruins.p3d";
	};
	
	class land_PBstadR_ruins : Ruins {
		displayName = "Ramp Ruins";
		vehicleClass = "Oz_Is_Objects";
		scope = public;
		model = "\PAF_stad_obj\PBstadR_ruins.p3d";
	};
	
	class land_PBstadRscore_ruins : Ruins {
		displayName = "Scoreboard Ruins";
		vehicleClass = "Oz_Is_Objects";
		scope = public;
		model = "\PAF_stad_obj\PBstadRscore_ruins.p3d";
	};
	
	class land_PBstadE_ruins : Ruins {
		displayName = "Entrance Ruins";
		vehicleClass = "Oz_Is_Objects";
		scope = public;
		model = "\PAF_stad_obj\PBstadE_ruins.p3d";
	};
	
	class land_PBlighttower_ruins : Ruins {
		displayName = "Light Tower Ruins";
		vehicleClass = "Oz_Is_Objects";
		scope = public;
		model = "\PAF_stad_obj\PBlighttower_ruins.p3d";
	};
	class HouseBase;	// External class reference
	class Land_VASICore;	// External class reference
	
	class House : HouseBase {
		class DestructionEffects;	// External class reference
	};
	
	class Land_PBaflgoals : NonStrategic {
		displayName = "AFL Goal Posts";
		vehicleClass = "Oz_Is_Objects";
		model = "\PAF_stad_obj\pbaflgoals.p3d";
		icon = "\PAF_stad_obj\icon\goalpost.paa";
		scope = public;
		destrType = "DestructNo";
		meSound = "bunker";
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		mapSize = 10;
	};
	
	class Land_PBstadS : House {
		displayName = "Apex";
		vehicleClass = "Oz_Is_Objects";
		model = "\PAF_stad_obj\PBstadS.p3d";
		icon = "\PAF_stad_obj\icon\goalpost.paa";
		scope = public;
		animated = true;
		nameSound = "bunker";
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		mapSize = 10;
		armor = 2200;
		damageResistance = 0.008;
		
		class DestructionEffects : DestructionEffects {
			class Ruins {
				simulation = "ruin";
				type = "\PAF_stad_obj\PBstadS_ruins.p3d";
				position = "";
				intensity = 3;
				interval = 1;
				lifeTime = 6;
			};
		};
		
		class Hitpoints {
			class Hit1 {
				armor = 0.9;
				material = -1;
				name = "hit1";
				visual = "hit1";
				passThrough = 0.55;
				convexComponent = "hit1";
				
				class DestructionEffects {
					class Dust {
						simulation = "particles";
						type = "ImpactDustConcrete";
						position = "";
						intensity = 1;
						interval = 1;
						lifeTime = 0.1;
					};
					
					class Dust2 : Dust {
						type = "HousePartDustLong";
					};
					
					class Walls : Dust {
						type = "HousePartWall";
						lifeTime = 0.02;
					};
				};
			};
		};
		replaceDamagedHitpoints[] = {"Hit1"};
		replaceDamaged = "Land_PBstadSD_dam";
	};
	
	class Land_PBstadSD_dam : House {
		model = "\PAF_stad_obj\PBstadS_dam.p3d";
		icon = "\PAF_stad_obj\icon\goalpost.paa";
		scope = public;
		animated = true;
		nameSound = "bunker";
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		mapSize = 10;
		armor = 1500;
		damageResistance = 0.008;
		
		class DestructionEffects : DestructionEffects {
			class Ruins {
				simulation = "ruin";
				type = "\PAF_stad_obj\PBstadS_ruins.p3d";
				position = "";
				intensity = 2;
				interval = 2;
				lifeTime = 8;
			};
		};
		
		class AnimationSources {
			class Hit1 {
				source = "hit";
				hitpoint = "Hit1";
				raw = 1;
			};
		};
		replaceDamaged = "";
	};
	
	class Land_PBstadSD : House {
		displayName = "Apex Damaged";
		vehicleClass = "Oz_Is_Objects";
		model = "\PAF_stad_obj\PBstadSD.p3d";
		icon = "\PAF_stad_obj\icon\goalpost.paa";
		scope = public;
		animated = true;
		nameSound = "bunker";
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		mapSize = 10;
		armor = 1500;
		damageResistance = 0.008;
		
		class DestructionEffects : DestructionEffects {
			class Ruins {
				simulation = "ruin";
				type = "\PAF_stad_obj\PBstadS_ruins.p3d";
				position = "";
				intensity = 2;
				interval = 1;
				lifeTime = 5;
			};
		};
	};
	
	class Land_PBstadR : House {
		displayName = "Ramped";
		vehicleClass = "Oz_Is_Objects";
		model = "\PAF_stad_obj\PBstadR.p3d";
		icon = "\PAF_stad_obj\icon\goalpost.paa";
		scope = public;
		animated = true;
		nameSound = "bunker";
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		mapSize = 10;
		armor = 2200;
		damageResistance = 0.008;
		
		class DestructionEffects : DestructionEffects {
			class Ruins {
				simulation = "ruin";
				type = "\PAF_stad_obj\PBstadR_ruins.p3d";
				position = "";
				intensity = 1;
				interval = 1;
				lifeTime = 9;
			};
		};
	};
	
	class Land_PBstadRscore : House {
		displayName = "Scoreboard";
		vehicleClass = "Oz_Is_Objects";
		model = "\PAF_stad_obj\PBstadRscore.p3d";
		icon = "\PAF_stad_obj\icon\goalpost.paa";
		scope = public;
		animated = true;
		nameSound = "bunker";
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		mapSize = 10;
		armor = 2200;
		damageResistance = 0.008;
		
		class DestructionEffects : DestructionEffects {
			class Ruins {
				simulation = "ruin";
				type = "\PAF_stad_obj\PBstadRscore_ruins.p3d";
				position = "";
				intensity = 2;
				interval = 1;
				lifeTime = 9;
			};
		};
		
		class Hitpoints {
			class HitGlass1 {
				armor = 0.025;
				material = -1;
				name = "Glass1";
				visual = "Glass1";
				passThrough = false;
				convexComponent = "Glass1";
			};
			
			class HitGlass2 {
				armor = 0.025;
				material = -1;
				name = "Glass2";
				visual = "Glass2";
				passThrough = false;
				convexComponent = "Glass2";
			};
			
			class HitGlass3 {
				armor = 0.015;
				material = -1;
				name = "Glass3";
				visual = "Glass3";
				passThrough = false;
				convexComponent = "Glass3";
			};
			
			class HitGlass4 {
				armor = 0.015;
				material = -1;
				name = "Glass4";
				visual = "Glass4";
				passThrough = false;
				convexComponent = "Glass4";
			};
		};
		
		class AnimationSources {
			class HitGlass1 {
				source = "hit";
				hitpoint = "HitGlass1";
				raw = 1;
			};
			
			class HitGlass2 {
				source = "hit";
				hitpoint = "HitGlass2";
				raw = 1;
			};
			
			class HitGlass3 {
				source = "hit";
				hitpoint = "HitGlass3";
				raw = 1;
			};
			
			class HitGlass4 {
				source = "hit";
				hitpoint = "HitGlass4";
				raw = 1;
			};
		};
	};
	
	class Land_PBstadE : House {
		displayName = "Eliptical Entrance";
		vehicleClass = "Oz_Is_Objects";
		model = "\PAF_stad_obj\PBstadE.p3d";
		icon = "\PAF_stad_obj\icon\goalpost.paa";
		scope = public;
		animated = true;
		nameSound = "bunker";
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		mapSize = 10;
		armor = 2200;
		damageResistance = 0.008;
		
		class DestructionEffects : DestructionEffects {
			class Ruins {
				simulation = "ruin";
				type = "\PAF_stad_obj\PBstadE_ruins.p3d";
				position = "";
				intensity = 3;
				interval = 3;
				lifeTime = 8;
			};
		};
	};
	
	class Land_PBlighttower : House {
		displayName = "Lighting Tower";
		vehicleClass = "Oz_Is_Objects";
		model = "\PAF_stad_obj\PBlighttower.p3d";
		icon = "\PAF_stad_obj\icon\goalpost.paa";
		scope = public;
		animated = true;
		nameSound = "bunker";
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		mapSize = 10;
		armor = 450;
		damageResistance = 0.004;
		
		class DestructionEffects : DestructionEffects {
			class Ruins {
				simulation = "ruin";
				type = "\PAF_stad_obj\PBlighttower_ruins.p3d";
				position = "";
				intensity = 2;
				interval = 2;
				lifeTime = 8;
			};
		};
		
		class Reflectors {
			class FL01 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL01SOR;
				direction = FL01DIR;
				hitpoint = FL01;
				selection = FL01;
				size = 1.4;
				brightness = 1.6;
			};
			
			class FL02 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL02SOR;
				direction = FL02DIR;
				hitpoint = FL02;
				selection = FL02;
				size = 1.9;
				brightness = 1.6;
			};
			
			class FL03 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL03SOR;
				direction = FL03DIR;
				hitpoint = FL03;
				selection = FL03;
				size = 1.4;
				brightness = 1.6;
			};
			
			class FL04 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL04SOR;
				direction = FL04DIR;
				hitpoint = FL04;
				selection = FL04;
				size = 1.4;
				brightness = 1.6;
			};
			
			class FL05 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL05SOR;
				direction = FL05DIR;
				hitpoint = FL05;
				selection = FL05;
				size = 1.9;
				brightness = 1.6;
			};
			
			class FL06 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL06SOR;
				direction = FL06DIR;
				hitpoint = FL06;
				selection = FL06;
				size = 1.4;
				brightness = 1.6;
			};
			
			class FL07 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL07SOR;
				direction = FL07DIR;
				hitpoint = FL07;
				selection = FL07;
				size = 1.4;
				brightness = 1.5;
			};
			
			class FL08 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL08SOR;
				direction = FL08DIR;
				hitpoint = FL08;
				selection = FL08;
				size = 1.9;
				brightness = 1.5;
			};
			
			class FL09 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL09SOR;
				direction = FL09DIR;
				hitpoint = FL09;
				selection = FL09;
				size = 1.4;
				brightness = 1.5;
			};
			
			class FL10 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL10SOR;
				direction = FL10DIR;
				hitpoint = FL10;
				selection = FL10;
				size = 1.9;
				brightness = 1.5;
			};
			
			class FL11 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL11SOR;
				direction = FL11DIR;
				hitpoint = FL11;
				selection = FL11;
				size = 1.4;
				brightness = 1.5;
			};
			
			class FL12 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL12SOR;
				direction = FL12DIR;
				hitpoint = FL12;
				selection = FL12;
				size = 1.4;
				brightness = 1.4;
			};
			
			class FL13 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL13SOR;
				direction = FL13DIR;
				hitpoint = FL13;
				selection = FL13;
				size = 1.9;
				brightness = 1.4;
			};
			
			class FL14 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL14SOR;
				direction = FL14DIR;
				hitpoint = FL14;
				selection = FL14;
				size = 1.9;
				brightness = 1.4;
			};
			
			class FL15 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL15SOR;
				direction = FL15DIR;
				hitpoint = FL15;
				selection = FL15;
				size = 1.4;
				brightness = 1.4;
			};
			
			class FL16 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL16SOR;
				direction = FL16DIR;
				hitpoint = FL16;
				selection = FL16;
				size = 1.4;
				brightness = 1.3;
			};
			
			class FL17 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL17SOR;
				direction = FL17DIR;
				hitpoint = FL17;
				selection = FL17;
				size = 1.9;
				brightness = 1.3;
			};
			
			class FL18 {
				color[] = {0.9, 0.8, 0.8, 1.0};
				ambient[] = {0.1, 0.1, 0.1, 1.0};
				position = FL18SOR;
				direction = FL18DIR;
				hitpoint = FL18;
				selection = FL18;
				size = 1.4;
				brightness = 1.3;
			};
		};
	};
};
