// Generated by unRap v1.06 by Kegetys

class CfgVehicleClasses {
	class sfsg_des {
		displayName = "SFSG (Desert)";
	};
	
	class sfsg_mtp {
		displayName = "SFSG (Desert MTP)";
	};
	
	class sfsg_wdl {
		displayName = "SFSG (Woodland)";
	};
	
	class sfsg_mtpw {
		displayName = "SFSG (Woodland MTP)";
	};
	
	class uksf_des {
		displayName = "SAS/SBS (Assault Desert)";
	};
	
	class uksf_wdl {
		displayName = "SAS/SBS (Assault Woodland)";
	};
	
	class uksf_des_l {
		displayName = "SAS/SBS (Desert)";
	};
	
	class uksf_wdl_l {
		displayName = "SAS/SBS (Woodland)";
	};
};
