// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class CZ_Backpack_EP1;	// External class reference
	class US_Patrol_Pack_EP1;	// External class reference
	class US_Backpack_EP1;	// External class reference
	class US_Delta_Force_TL_EP1;	// External class reference
	class US_Delta_Force_EP1;	// External class reference
	class US_Delta_Force_AR_EP1;	// External class reference
	class US_Delta_Force_Medic_EP1;	// External class reference
	class US_Delta_Force_Marksman_EP1;	// External class reference
	class US_Delta_Force_Air_Controller_EP1;	// External class reference
	
	class SFSG_des_tl : US_Delta_Force_TL_EP1 {
		faction = BIS_BAF;
		identityTypes[] = {"Language_BAF", "Head_BAF", "BAF_Glasses"};
		displayName = "Team Leader";
		model = "\GoosUKSF\assault\uksf_des_1";
		vehicleClass = "sfsg_des";
		canCarryBackPack = 1;
		backpack = "";
		weapons[] = {M4A3_RCO_GL_EP1, "Colt1911", "Binocular_Vector", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		magazines[] = {"30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "1Rnd_HE_M203", "1Rnd_HE_M203", "1Rnd_HE_M203", "1Rnd_HE_M203", BAF_L109A1_HE, BAF_L109A1_HE, "SmokeShell"};
		respawnWeapons[] = {M4A3_RCO_GL_EP1, "Colt1911", "Binocular_Vector", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		respawnMagazines[] = {"30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "1Rnd_HE_M203", "1Rnd_HE_M203", "1Rnd_HE_M203", "1Rnd_HE_M203", BAF_L109A1_HE, BAF_L109A1_HE, "SmokeShell"};
	};
	
	class SFSG_des_op : US_Delta_Force_EP1 {
		faction = BIS_BAF;
		identityTypes[] = {"Language_BAF", "Head_BAF", "BAF_Glasses"};
		displayName = "Operator";
		model = "\GoosUKSF\assault\uksf_des_1";
		vehicleClass = "sfsg_des";
		canCarryBackPack = 1;
		backpack = "";
		weapons[] = {M4A3_RCO_GL_EP1, "Colt1911", "Binocular_Vector", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		magazines[] = {"30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "1Rnd_HE_M203", "1Rnd_HE_M203", "1Rnd_HE_M203", "1Rnd_HE_M203", BAF_L109A1_HE, BAF_L109A1_HE, "SmokeShell"};
		respawnWeapons[] = {M4A3_RCO_GL_EP1, "Colt1911", "Binocular_Vector", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		respawnMagazines[] = {"30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "1Rnd_HE_M203", "1Rnd_HE_M203", "1Rnd_HE_M203", "1Rnd_HE_M203", BAF_L109A1_HE, BAF_L109A1_HE, "SmokeShell"};
	};
	
	class SFSG_des_ar : US_Delta_Force_AR_EP1 {
		faction = BIS_BAF;
		identityTypes[] = {"Language_BAF", "Head_BAF", "BAF_Glasses"};
		displayName = "Automatic Rifleman";
		model = "\GoosUKSF\assault\uksf_des_2";
		vehicleClass = "sfsg_des";
		canCarryBackPack = 1;
		backpack = "";
		weapons[] = {"BAF_L110A1_Aim", "Colt1911", "Binocular_Vector", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		magazines[] = {"200Rnd_556x45_L110A1", "200Rnd_556x45_L110A1", "200Rnd_556x45_L110A1", "200Rnd_556x45_L110A1", "200Rnd_556x45_L110A1", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", BAF_L109A1_HE, "SmokeShell"};
		respawnWeapons[] = {"BAF_L110A1_Aim", "Colt1911", "Binocular_Vector", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		respawnMagazines[] = {"200Rnd_556x45_L110A1", "200Rnd_556x45_L110A1", "200Rnd_556x45_L110A1", "200Rnd_556x45_L110A1", "200Rnd_556x45_L110A1", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", BAF_L109A1_HE, "SmokeShell"};
	};
	
	class SFSG_des_med : US_Delta_Force_Medic_EP1 {
		faction = BIS_BAF;
		identityTypes[] = {"Language_BAF", "Head_BAF", "BAF_Glasses"};
		displayName = "Medic";
		model = "\GoosUKSF\assault\uksf_des_medic";
		vehicleClass = "sfsg_des";
		weapons[] = {M4A3_CCO_EP1, "Colt1911", "Binocular_Vector", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		magazines[] = {"30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", BAF_L109A1_HE, BAF_L109A1_HE, "SmokeShell"};
		respawnWeapons[] = {M4A3_CCO_EP1, "Colt1911", "Binocular_Vector", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		respawnMagazines[] = {"30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", BAF_L109A1_HE, BAF_L109A1_HE, "SmokeShell"};
	};
	
	class SFSG_des_demo : US_Delta_Force_EP1 {
		faction = BIS_BAF;
		identityTypes[] = {"Language_BAF", "Head_BAF", "BAF_Glasses"};
		displayName = "Demo Specialist";
		model = "\GoosUKSF\assault\uksf_des_2";
		vehicleClass = "sfsg_des";
		canDeactivateMines = "true";
		canCarryBackPack = 1;
		backpack = "";
		weapons[] = {M4A3_CCO_EP1, "Colt1911", "Binocular_Vector", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		magazines[] = {"30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", BAF_L109A1_HE, "SmokeShell", "PipeBomb"};
		respawnWeapons[] = {M4A3_CCO_EP1, "Colt1911", "Binocular_Vector", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		respawnMagazines[] = {"30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", BAF_L109A1_HE, "SmokeShell", "PipeBomb"};
	};
	
	class SFSG_des_mrk : US_Delta_Force_Marksman_EP1 {
		faction = BIS_BAF;
		identityTypes[] = {"Language_BAF", "Head_BAF", "BAF_Glasses"};
		displayName = "Marksman";
		model = "\GoosUKSF\assault\uksf_des_2";
		vehicleClass = "sfsg_des";
		canCarryBackPack = 1;
		backpack = "";
		weapons[] = {"BAF_LRR_scoped", "Colt1911", "Binocular_Vector", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		magazines[] = {"5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", BAF_L109A1_HE, BAF_L109A1_HE, "SmokeShell"};
		respawnWeapons[] = {"BAF_LRR_scoped", "Colt1911", "Binocular_Vector", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		respawnMagazines[] = {"5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "5Rnd_86x70_L115A1", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", BAF_L109A1_HE, BAF_L109A1_HE, "SmokeShell"};
	};
	
	class SFSG_des_jtac : US_Delta_Force_Air_Controller_EP1 {
		faction = BIS_BAF;
		identityTypes[] = {"Language_BAF", "Head_BAF", "BAF_Glasses"};
		displayName = "Operator (JTAC)";
		model = "\GoosUKSF\assault\uksf_des_1";
		vehicleClass = "sfsg_des";
		canCarryBackPack = 1;
		backpack = "";
		weapons[] = {M4A3_RCO_GL_EP1, "Colt1911", "Laserdesignator", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		magazines[] = {"30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "1Rnd_HE_M203", "1Rnd_HE_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", BAF_L109A1_HE, "SmokeShellRed", "SmokeShellGreen", "Laserbatteries"};
		respawnWeapons[] = {M4A3_RCO_GL_EP1, "Colt1911", "Laserdesignator", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		respawnMagazines[] = {"30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "7Rnd_45ACP_1911", "1Rnd_HE_M203", "1Rnd_HE_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", BAF_L109A1_HE, "SmokeShellRed", "SmokeShellGreen", "Laserbatteries"};
	};
	
	class SFSG_mtp_tl : SFSG_des_tl {
		model = "\GoosUKSF\assault\uksf_des_3";
		vehicleClass = "sfsg_mtp";
	};
	
	class SFSG_mtp_op : SFSG_des_op {
		model = "\GoosUKSF\assault\uksf_des_3";
		vehicleClass = "sfsg_mtp";
	};
	
	class SFSG_mtp_ar : SFSG_des_ar {
		model = "\GoosUKSF\assault\uksf_des_4";
		vehicleClass = "sfsg_mtp";
	};
	
	class SFSG_mtp_med : SFSG_des_med {
		model = "\GoosUKSF\assault\sfsg_mtp_medic";
		vehicleClass = "sfsg_mtp";
	};
	
	class SFSG_mtp_demo : SFSG_des_demo {
		model = "\GoosUKSF\assault\uksf_des_4";
		vehicleClass = "sfsg_mtp";
	};
	
	class SFSG_mtp_mrk : SFSG_des_mrk {
		model = "\GoosUKSF\assault\uksf_des_4";
		vehicleClass = "sfsg_mtp";
	};
	
	class SFSG_mtp_jtac : SFSG_des_jtac {
		model = "\GoosUKSF\assault\uksf_des_3";
		vehicleClass = "sfsg_mtp";
	};
	
	class SFSG_wdl_tl : SFSG_des_tl {
		model = "\GoosUKSF\assault\uksf_wdl_1";
		vehicleClass = "sfsg_wdl";
	};
	
	class SFSG_wdl_op : SFSG_des_op {
		model = "\GoosUKSF\assault\uksf_wdl_1";
		vehicleClass = "sfsg_wdl";
	};
	
	class SFSG_wdl_ar : SFSG_des_ar {
		model = "\GoosUKSF\assault\uksf_wdl_2";
		vehicleClass = "sfsg_wdl";
	};
	
	class SFSG_wdl_med : SFSG_des_med {
		model = "\GoosUKSF\assault\uksf_wdl_medic";
		vehicleClass = "sfsg_wdl";
	};
	
	class SFSG_wdl_demo : SFSG_des_demo {
		model = "\GoosUKSF\assault\uksf_wdl_2";
		vehicleClass = "sfsg_wdl";
	};
	
	class SFSG_wdl_mrk : SFSG_des_mrk {
		model = "\GoosUKSF\assault\uksf_wdl_2";
		vehicleClass = "sfsg_wdl";
		weapons[] = {"BAF_LRR_scoped_W", "Colt1911", "Binocular_Vector", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
		respawnWeapons[] = {"BAF_LRR_scoped_W", "Colt1911", "Binocular_Vector", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "itemGPS"};
	};
	
	class SFSG_wdl_jtac : SFSG_des_jtac {
		model = "\GoosUKSF\assault\uksf_wdl_1";
		vehicleClass = "sfsg_wdl";
	};
	
	class SFSG_mtpw_tl : SFSG_des_tl {
		model = "\GoosUKSF\assault\uksf_wdl_3";
		vehicleClass = "sfsg_mtpw";
	};
	
	class SFSG_mtpw_op : SFSG_des_op {
		model = "\GoosUKSF\assault\uksf_wdl_3";
		vehicleClass = "sfsg_mtpw";
	};
	
	class SFSG_mtpw_ar : SFSG_des_ar {
		model = "\GoosUKSF\assault\uksf_wdl_4";
		vehicleClass = "sfsg_mtpw";
	};
	
	class SFSG_mtpw_med : SFSG_des_med {
		model = "\GoosUKSF\assault\sfsg_mtpw_medic";
		vehicleClass = "sfsg_mtpw";
	};
	
	class SFSG_mtpw_demo : SFSG_des_demo {
		model = "\GoosUKSF\assault\uksf_wdl_4";
		vehicleClass = "sfsg_mtpw";
	};
	
	class SFSG_mtpw_mrk : SFSG_wdl_mrk {
		model = "\GoosUKSF\assault\uksf_wdl_4";
		vehicleClass = "sfsg_mtpw";
	};
	
	class SFSG_mtpw_jtac : SFSG_des_jtac {
		model = "\GoosUKSF\assault\uksf_wdl_3";
		vehicleClass = "sfsg_mtpw";
	};
	
	class UKSF_des_tl : SFSG_des_tl {
		model = "\GoosUKSF\assault\uksf_des_3";
		vehicleClass = "uksf_des";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\GoosUKSF\assault\des\uksf_des_co"};
	};
	
	class UKSF_des_op : SFSG_des_op {
		model = "\GoosUKSF\assault\uksf_des_1";
		vehicleClass = "uksf_des";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\GoosUKSF\assault\des\uksf_mtp_co"};
	};
	
	class UKSF_des_ar : SFSG_des_ar {
		model = "\GoosUKSF\assault\uksf_des_2";
		vehicleClass = "uksf_des";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\GoosUKSF\assault\des\uksf_dpm_co"};
	};
	
	class UKSF_des_med : SFSG_des_med {
		model = "\GoosUKSF\assault\uksf_des_medic";
		vehicleClass = "uksf_des";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\GoosUKSF\assault\des\uksf_mtp_co"};
	};
	
	class UKSF_des_demo : SFSG_des_demo {
		model = "\GoosUKSF\assault\uksf_des_4";
		vehicleClass = "uksf_des";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\GoosUKSF\assault\des\uksf_des_co"};
	};
	
	class UKSF_des_mrk : SFSG_des_mrk {
		model = "\GoosUKSF\assault\uksf_des_2";
		vehicleClass = "uksf_des";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\GoosUKSF\assault\des\uksf_mtp_co"};
	};
	
	class UKSF_des_jtac : SFSG_des_jtac {
		model = "\GoosUKSF\assault\uksf_des_1";
		vehicleClass = "uksf_des";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\GoosUKSF\assault\des\uksf_dpm_co"};
	};
	
	class UKSF_wdl_tl : SFSG_des_tl {
		model = "\GoosUKSF\assault\uksf_wdl_3";
		vehicleClass = "uksf_wdl";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\GoosUKSF\assault\wdl\uksf_dpm_co"};
	};
	
	class UKSF_wdl_op : SFSG_des_op {
		model = "\GoosUKSF\assault\uksf_wdl_1";
		vehicleClass = "uksf_wdl";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\GoosUKSF\assault\wdl\uksf_mtp_co"};
	};
	
	class UKSF_wdl_ar : SFSG_des_ar {
		model = "\GoosUKSF\assault\uksf_wdl_2";
		vehicleClass = "uksf_wdl";
	};
	
	class UKSF_wdl_med : SFSG_des_med {
		model = "\GoosUKSF\assault\uksf_wdl_medic";
		vehicleClass = "uksf_wdl";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\GoosUKSF\assault\wdl\uksf_mtp_co"};
	};
	
	class UKSF_wdl_demo : SFSG_des_demo {
		model = "\GoosUKSF\assault\uksf_wdl_4";
		vehicleClass = "uksf_wdl";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\GoosUKSF\assault\wdl\uksf_dpm_co"};
	};
	
	class UKSF_wdl_mrk : SFSG_wdl_mrk {
		model = "\GoosUKSF\assault\uksf_wdl_2";
		vehicleClass = "uksf_wdl";
	};
	
	class UKSF_wdl_jtac : SFSG_des_jtac {
		model = "\GoosUKSF\assault\uksf_wdl_1";
		vehicleClass = "uksf_wdl";
	};
	
	class UKSF_des_tl_l : SFSG_des_tl {
		model = "\GoosUKSF\light\uksf_des_light1";
		vehicleClass = "uksf_des_l";
		portrait = "\Ca\characters\data\portraits\comBarHead_opFor_ca";
	};
	
	class UKSF_des_op_l : SFSG_des_op {
		model = "\GoosUKSF\light\uksf_des_light5";
		vehicleClass = "uksf_des_l";
		portrait = "\Ca\characters\data\portraits\comBarHead_opFor_ca";
	};
	
	class UKSF_des_ar_l : SFSG_des_ar {
		model = "\GoosUKSF\light\uksf_des_light2";
		vehicleClass = "uksf_des_l";
		portrait = "\Ca\characters\data\portraits\comBarHead_opFor_ca";
	};
	
	class UKSF_des_med_l : SFSG_des_med {
		model = "\GoosUKSF\light\uksf_des_light_medic";
		vehicleClass = "uksf_des_l";
		portrait = "\Ca\characters\data\portraits\comBarHead_opFor_ca";
	};
	
	class UKSF_des_demo_l : SFSG_des_demo {
		model = "\GoosUKSF\light\uksf_des_light4";
		vehicleClass = "uksf_des_l";
		portrait = "\Ca\characters\data\portraits\comBarHead_opFor_ca";
	};
	
	class UKSF_des_mrk_l : SFSG_des_mrk {
		model = "\GoosUKSF\light\uksf_des_light6";
		vehicleClass = "uksf_des_l";
		portrait = "\Ca\characters\data\portraits\comBarHead_opFor_ca";
	};
	
	class UKSF_des_jtac_l : SFSG_des_jtac {
		model = "\GoosUKSF\light\uksf_des_light3";
		vehicleClass = "uksf_des_l";
		portrait = "\Ca\characters\data\portraits\comBarHead_opFor_ca";
	};
	
	class UKSF_wdl_tl_l : SFSG_des_tl {
		model = "\GoosUKSF\light\uksf_wdl_light1";
		vehicleClass = "uksf_wdl_l";
		portrait = "\Ca\characters\data\portraits\comBarHead_opFor_ca";
	};
	
	class UKSF_wdl_op_l : SFSG_des_op {
		model = "\GoosUKSF\light\uksf_wdl_light2";
		vehicleClass = "uksf_wdl_l";
		portrait = "\Ca\characters\data\portraits\comBarHead_opFor_ca";
	};
	
	class UKSF_wdl_ar_l : SFSG_des_ar {
		model = "\GoosUKSF\light\uksf_wdl_light3";
		vehicleClass = "uksf_wdl_l";
		portrait = "\Ca\characters\data\portraits\comBarHead_opFor_ca";
	};
	
	class UKSF_wdl_med_l : SFSG_des_med {
		model = "\GoosUKSF\light\uksf_wdl_light_medic";
		vehicleClass = "uksf_wdl_l";
		portrait = "\Ca\characters\data\portraits\comBarHead_opFor_ca";
	};
	
	class UKSF_wdl_demo_l : SFSG_des_demo {
		model = "\GoosUKSF\light\uksf_wdl_light4";
		vehicleClass = "uksf_wdl_l";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\GoosUKSF\assault\wdl\uksf_mtp_co"};
		portrait = "\Ca\characters\data\portraits\comBarHead_opFor_ca";
	};
	
	class UKSF_wdl_mrk_l : SFSG_wdl_mrk {
		model = "\GoosUKSF\light\uksf_wdl_light5";
		vehicleClass = "uksf_wdl_l";
		portrait = "\Ca\characters\data\portraits\comBarHead_opFor_ca";
	};
	
	class UKSF_wdl_jtac_l : SFSG_des_jtac {
		model = "\GoosUKSF\light\uksf_wdl_light6";
		vehicleClass = "uksf_wdl_l";
		portrait = "\Ca\characters\data\portraits\comBarHead_opFor_ca";
	};
	
	class UKSF_wdl_Bergan : CZ_Backpack_EP1 {
		displayName = "Bergan";
		model = "\GoosUKSF\backpacks\uksf_bergan.p3d";
	};
	
	class UKSF_wdl_Bergan2 : CZ_Backpack_EP1 {
		displayName = "Bergan (DPM)";
		model = "\GoosUKSF\backpacks\uksf_bergan_dpm.p3d";
	};
	
	class UKSF_wdl_coyote : US_Patrol_Pack_EP1 {
		displayName = "Patrol Pack (Olive)";
		model = "\GoosUKSF\backpacks\uksf_coyote.p3d";
	};
	
	class UKSF_wdl_backpack : US_Backpack_EP1 {
		displayName = "Backpack (Olive)";
		model = "\GoosUKSF\backpacks\uksf_backpack.p3d";
	};
};
