// config.bin - 13:06:36 06/17/17, generated in 0.05 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#include "CfgPatches.hpp"
#include "CfgVehicleClasses.hpp"
#include "CfgVehicles.hpp"
