// config.bin - 13:01:35 06/17/17, generated in 0.04 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define true	1
#define false	0

#define private		0
#define protected		1
#define public		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define VSoft		0
#define VArmor		1
#define VAir		2

class CfgPatches {
	class CYBP_Camels_Config {
		units[] = {"CYBP_Camel_us", "CYBP_Camel_rus", "CYBP_Camel_civ"};
		weapons[] = {"VickerMGs"};
		requiredVersion = 1.0;
		requiredAddons[] = {"CAAir", "CACharacters2", "CAWeapons", "CYBP_Camels"};
	};
};
class ViewOptics;	// External class reference
class ViewPilot;	// External class reference
class ViewCargo;	// External class reference
class AnimationSources;	// External class reference
class DefaultEventHandlers;	// External class reference

class CfgMovesBasic {
	class DefaultDie;	// External class reference
	
	class ManActions {
		Camel_a2_Pilot = "Camel_a2_Pilot";
	};
};

class CfgMovesMaleSdr : CfgMovesBasic {
	class States {
		class Crew;	// External class reference
		class KIA_Camel_Pilot;	// External class reference
		
		class Camel_a2_Pilot : Crew {
			file = "\CYBP\CYBP_Camels\Data\Anim\Pilot_a2.rtm";
			interpolateTo[] = {"KIA_Camel_Pilot", 1};
		};
	};
};

class CfgFactionClasses {
	class USMC;	// External class reference
	class GUE;	// External class reference
	
	class USArmy : USMC {
		displayName = "US Army";
	};
	
	class RACS : GUE {
		displayName = RACS;
	};
};

class CfgWeapons {
	class TwinVickers;	// External class reference
	class LauncherCore;	// External class reference
	class RocketPods;	// External class reference
	
	class VickerMGs : TwinVickers {
		cursorAim = "\ca\Weapons\Data\clear_empty";
		cursor = "\ca\Weapons\Data\clear_empty";
		magazines[] = {"500Rnd_TwinVickers"};
		begin1[] = {"\CYBP\cybp_camels\Data\Sound\Camel_gun_einfach.wss", 1.20828, 1.05, 900};
		begin2[] = {"\CYBP\cybp_camels\Data\Sound\Camel_gun_einfach.wss", 1.20828, 1, 900};
		soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		reloadTime = 0.065;
		burst = 2;
		aiDispersionCoefY = 21;
		aiDispersionCoefX = 21;
		initSpeed = 740;
		autoFire = true;
		dispersion = 0.0013;
		minRange = 0;
		minRangeProbab = 0.9;
		midRange = 400;
		midRangeProbab = 0.58;
		maxRange = 600;
		maxRangeProbab = 0.04;
	};
	
	class CamelGrenades : RocketPods {
		sound[] = {"\CYBP\cybp_camels\Data\Sound\Camel_granatwurf.wss", db20, 1};
		autoFire = false;
		magazines[] = {"6Rnd_Grenade_Camel"};
		reloadTime = 3;
		aiDispersionCoefY = 21;
		aiDispersionCoefX = 21;
		magazineReloadTime = 0.1;
		dispersion = 0.015;
		minRange = 1;
		minRangeProbab = 0.8;
		midRange = 50;
		midRangeProbab = 0.7;
		maxRange = 150;
		maxRangeProbab = 0.1;
		autoReload = true;
		canLock = "LockNo";
	};
};

class CfgMagazines {
	class VehicleMagazine;	// External class reference
	
	class 500Rnd_TwinVickers : VehicleMagazine {
		tracersEvery = 1;
	};
};

class CfgAmmo {
	class RocketCore;	// External class reference
	class BulletBase;	// External class reference
	
	class B_77x56_Ball : BulletBase {
		tracerScale = 1.2;
		tracerStartTime = 0.03;
		tracerEndTime = 1;
		soundFly[] = {"", db-160, 1};
		soundDefault1[] = {"ca\sounds\weapons\hits\hit_concrete_01", 0.316228, 1, 60};
		soundWood1[] = {"ca\sounds\weapons\hits\hit_wood_01", 0.316228, 1, 60};
		hitWood[] = {"soundWood1", 0.1};
		hitDefault[] = {"soundDefault1", 0.2};
	};
	
	class G_Camel_HE : RocketCore {
		soundHit[] = {"Ca\sounds\Weapons\explosions\GP25_explosion", db15, 1, 800};
	};
};

class CfgVehicles {
	class Plane;	// External class reference
	
	class CYBP_Camel_Base : Plane {
		selectionHRotorStill = "vrtule staticka";
		selectionHRotorMove = "vrtule staticka";
		scope = private;
		crew = "USMC_Soldier_Pilot";
		side = TWest;
		faction = "USArmy";
		DisplayName = "Camel (West)";
		nameSound = "plane";
		accuracy = 0.3;	// accuracy needed to recognize type of this target
		maxSpeed = 188;	// max speed on level road, km/h
		gearRetracting = false;
		flaps = 0;
		airBrake = 0;
		cabinOpening = 0;
		ejectSpeed[] = {0, 0, 0};
		ejectDamageLimit = 0.75;
		armor = 15;
		damageResistance = 0.00453;
		cost = 200000;
		model = "CYBP\CYBP_Camels\CYBP_Camel.p3d";
		picture = "CYBP\CYBP_Camels\data\ico\BIScamel_CA.paa";
		Icon = "CYBP\CYBP_Camels\data\map_ico\icomap_camel_CA.paa";
		mapSize = 8;
		weapons[] = {"VickerMGs", "CamelGrenades"};
		magazines[] = {"500Rnd_TwinVickers", "6Rnd_Grenade_Camel"};
		selectionFireAnim = "zasleh";
		landingSpeed = 75;
		landingAoa = 5.0*3.1415/180;
		irScanGround = true;
		irScanRangeMin = 100;
		irScanRangeMax = 12000;
		flapsFrictionCoef = 2;
		wheelSteeringSensitivity = 0.5;
		driverAction = "Camel_a2_Pilot";
		driverCanSee = "CanSeeEye+CanSeeEar";
		soundDammage[] = {"\CYBP\cybp_camels\Data\Sound\Camel_dammage.wss", 4.0, 1, 400};
		soundLandCrash[] = {"\CYBP\cybp_camels\Data\Sound\Camel_reifen.wss", 5.0, 1, 400};
		soundCrash[] = {"\CYBP\cybp_camels\Data\Sound\Camel_crash.wss", 4.0, 1, 1000};
		soundGetIn[] = {"\CYBP\cybp_camels\Data\Sound\Camel_goin.wss", 4.0, 1, 150};
		soundGetOut[] = {"\CYBP\cybp_camels\Data\Sound\Camel_goout.wss", 20.0, 1.1, 150};
		soundEngineOnInt[] = {"\CYBP\cybp_camels\Data\Sound\Camel_start.wss", 0.452341, 1.0};
		soundEngineOnExt[] = {"\CYBP\cybp_camels\Data\Sound\Camel_start.wss", 0.884328, 1.0, 800};
		soundEngineOffInt[] = {"\CYBP\cybp_camels\Data\Sound\Camel_stop.wss", 0.400341, 1.0};
		soundEngineOffExt[] = {"\CYBP\cybp_camels\Data\Sound\Camel_stop.wss", 0.884328, 1.0, 800};
		insideSoundCoef = 1.0;
		
		class EventHandlers : DefaultEventHandlers {
			fired = "_this execVM ""\CYBP\CYBP_Camels_Config\mg2.sqf"";";
		};
		
		class HitPoints {
			class HitHull {
				armor = 1;
				material = -1;
				name = "telo";
				visual = "trup";
				passThrough = true;
			};
		};
		
		class AnimationSources : AnimationSources {
			class MGHide {
				source = "user";
				animPeriod = 1;
				initPhase = 0;
			};
		};
		
		class Sounds {
			class EngineLowOut {
				sound[] = {"\CYBP\CYBP_Camels\Data\Sound\Camel_engine.wss", 2.02341, 0.8, 1300};
				frequency = "1.0 min (rpm + 0.5)";
				volume = "engineOn*camPos*(rpm factor[0.85, 0])";
			};
			
			class EngineHighOut {
				sound[] = {"\CYBP\CYBP_Camels\Data\Sound\Camel_engine.wss", 2.62341, 1.3, 1900};
				frequency = "1";
				volume = "engineOn*camPos*(rpm factor[0.55, 1.0])";
			};
			
			class ForsageOut {
				sound[] = {"\CYBP\cybp_camels\Data\Sound\Camel_idle1a.wss", 1.49189, 2.0, 1000};
				frequency = "1";
				volume = "engineOn*camPos*(thrust factor[0.5, 1.0])";
				cone[] = {3.14, 3.92, 2.0, 0.4};
			};
			
			class WindNoiseOut {
				sound[] = {"\CYBP\cybp_camels\Data\Sound\Camel_wind.wss", 3.75837, 3.0, 900};
				frequency = "(0.1+(1.2*(speed factor[1, 150])))";
				volume = "camPos*(speed factor[1, 150])";
			};
			
			class EngineLowIn {
				sound[] = {"\CYBP\CYBP_Camels\Data\Sound\Camel_engine.wss", 2.02341, 0.8};
				frequency = "1.0 min (rpm + 0.5)";
				volume = "engineOn*camPos*(rpm factor[0.85, 0])";
			};
			
			class EngineHighIn {
				sound[] = {"\CYBP\CYBP_Camels\Data\Sound\Camel_engine.wss", 2.62341, 1.3};
				frequency = "1";
				volume = "(1-camPos)*(engineOn*(rpm factor[0.55, 1.0]))";
			};
			
			class ForsageIn {
				sound[] = {"\CYBP\cybp_camels\Data\Sound\Camel_idle1a.wss", 1.49189, 2.0};
				frequency = "1";
				volume = "(1-camPos)*(engineOn*(thrust factor[0.8, 1.0]))";
			};
			
			class WindNoiseIn {
				sound[] = {"\CYBP\cybp_camels\Data\Sound\Camel_wind.wss", 3.75837, 3.0};
				frequency = "(0.1+(1.2*(speed factor[1, 150])))";
				volume = "(1-camPos)*(speed factor[1, 150])";
			};
			
			class NoiseIn {
				sound[] = {"ca\sounds\Vehicles\Tracked\M1A1\int\noise2", 0.1, 0.5};
				frequency = "(0.1+(1.2*(speed factor[1, 150])))";
				volume = "(1-camPos)*(speed factor[1, 150])";
			};
		};
		gunAimDown = 0;
		transportSoldier = 0;
		typicalCargo[] = {"USMC_Soldier_Pilot", "USMC_Soldier_Pilot"};
		hiddenSelections[] = {"camo1", "camo2", "camo3"};
		hiddenSelectionsTextures[] = {"CYBP\CYBP_Camels\data\camel_west_co.paa", "", "CYBP\CYBP_Camels\data\clear_empty.paa"};
		extCameraPosition[] = {0, 1.2, -13};
		type = VAir;
		
		// threat (VSoft, VArmor, VAir), how threatening vehicle is to unit types
		threat[] = {0.1, 1, 0.7};

		audible = 8;	// audible - bigger - better heard
		aileronSensitivity = 0.66;	// relative aileron sensitivity
		elevatorSensitivity = 0.33;	// relative elevator sensitivity
		enableGPS = 0;
		envelope[] = {0.0, 0.2, 0.9, 2.1, 2.5, 3.3, 3.5, 3.2, 2.5, 2.0, 1.5, 1.0};
		terrainCoef = 3.0;
		fov = 0.5;
		
		class ViewOptics {
			initAngleX = 0;
			minAngleX = 0;
			maxAngleX = 0;
			initAngleY = 0;
			minAngleY = 0;
			maxAngleY = 0;
			initFov = 0.5;
			minFov = 0.5;
			maxFov = 0.5;
		};
		
		// internal camera viewing limitations
		class ViewPilot : ViewPilot {
			initFov = 1;
			minFov = 0.4;
			maxFov = 1.2;
			initAngleX = 10;
			minAngleX = -45;
			maxAngleX = 85;
			initAngleY = 0;
			minAngleY = -150;
			maxAngleY = 150;
		};
		
		class Reflectors {
			class Left {
				color[] = {0, 0, 0, 1.0};
				ambient[] = {0, 0, 0, 1.0};
				position = "L svetlo";
				direction = "konec L svetla";
				hitpoint = "L svetlo";
				selection = "L svetlo";
				size = 1;
				brightness = 0.25;
			};
			
			class Right {
				color[] = {0, 0, 0, 1.0};
				ambient[] = {0, 0, 0, 1.0};
				position = "P svetlo";
				direction = "konec P svetla";
				hitpoint = "P svetlo";
				selection = "P svetlo";
				size = 1;
				brightness = 0.25;
			};
		};
		
		class Library {
			libTextDesc = "$STR_BISCamelLIB";
		};
		
		class Damage {
			tex[] = {};
			mat[] = {"CYBP\CYBP_Camels\data\camel_west.rvmat", "CYBP\CYBP_Camels\data\camel_west.rvmat", "CYBP\CYBP_Camels\data\camel_west_destruct.rvmat"};
		};
	};
	
	class CYBP_Camel_us : CYBP_Camel_Base {
		scope = public;
		transportSoldier = 0;
	};
	
	class CYBP_Camel_rus : CYBP_Camel_us {
		side = TEast;
		faction = "RU";
		scope = public;
		Crew = "RU_Soldier_Pilot";
		Model = "CYBP\CYBP_Camels\CYBP_Camel";
		hiddenSelectionsTextures[] = {"CYBP\CYBP_Camels\data\camel_east_co.paa", "", "CYBP\CYBP_Camels\data\clear_empty.paa"};
		picture = "CYBP\CYBP_Camels\data\ico\BIScamel2_CA.paa";
		typicalCargo[] = {"RU_Soldier_Pilot"};
		DisplayName = "Camel (East)";
		
		class Library {
			libTextDesc = "$STR_BISCamelLIB";
		};
		
		class Damage {
			tex[] = {};
			mat[] = {"CYBP\CYBP_Camels\data\camel_east.rvmat", "CYBP\CYBP_Camels\data\camel_east.rvmat", "CYBP\CYBP_Camels\data\camel_east_destruct.rvmat"};
		};
	};
	
	class CYBP_Camel_civ : CYBP_Camel_us {
		side = TCivilian;
		faction = CIV;
		Crew = "Pilot";
		Model = "CYBP\CYBP_Camels\CYBP_Camel";
		scope = public;
		weapons[] = {};
		magazines[] = {};
		hiddenSelectionsTextures[] = {"CYBP\CYBP_Camels\data\clear_empty.paa", "", "CYBP\CYBP_Camels\data\clear_empty.paa"};
		picture = "CYBP\CYBP_Camels\data\ico\BIScamel2_CA.paa";
		DisplayName = "Camel (Civil)";
		transportSoldier = 2;
		typicalCargo[] = {"USMC_Soldier_Pilot", "USMC_Soldier_Pilot"};
		cargoGetInAction[] = {"GetInLow"};
		cargoGetOutAction[] = {"GetOutLow"};
		cargoAction[] = {"Mi8_Cargo", "Mi8_Cargo"};
		driverCompartments = "Compartment1";
		cargoCompartments[] = {"Compartment2"};
		memoryPointsGetInCargo = "pos driver";
		memoryPointsGetInCargoDir = "pos driver dir";
		
		class Library {
			libTextDesc = "$STR_BISCamelLIB";
		};
		
		class AnimationSources : AnimationSources {
			class MGHide {
				source = "user";
				animPeriod = 1;
				initPhase = 1;
			};
		};
		
		class Damage {
			tex[] = {};
			mat[] = {"CYBP\CYBP_Camels\data\camel_east.rvmat", "CYBP\CYBP_Camels\data\camel_east.rvmat", "CYBP\CYBP_Camels\data\camel_east_destruct.rvmat"};
		};
	};
};
