// Generated by unRap v1.06 by Kegetys

class CfgFactionClasses {
	class Merc {
		displayName = "Mercenaries";
		priority = 100;
		side = TWest;
	};
	
	class Terrorist {
		displayName = "Terrorists";
		priority = 100;
		side = TGuerrila;
	};
	
	class BB_US_SOF {
		displayName = "US Forces";
		priority = 100;
		side = TWest;
	};
};
