// Generated by unRap v1.06 by Kegetys

class CfgGroups {
	class West {
		name = $STR_WEST;
		
		class US_Special_Forces_Groups {
			name = "U.S. Special Forces";
			
			class Infantry {
				name = "$STR_CfgGroups_West_USMC_Infantry";
				
				class BB_US_Navy_Seals {
					name = "U.S. Navy SEALs";
					faction = BB_US_SOF;
					rarityGroup = 0.01;
					
					class Unit0 {
						side = TWest;
						vehicle = "Navy_SEAL_TL";
						rank = LIEUTENANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TWest;
						vehicle = "Navy_SEAL_MG";
						rank = SERGEANT;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TWest;
						vehicle = "Navy_SEAL_GL";
						rank = SERGEANT;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TWest;
						vehicle = "Navy_SEAL_Marksman";
						rank = SERGEANT;
						position[] = {7, 0, 0};
					};
					
					class Unit4 {
						side = TWest;
						vehicle = "Navy_SEAL_Sabot";
						rank = SERGEANT;
						position[] = {9, 0, 0};
					};
					
					class Unit5 {
						side = TWest;
						vehicle = "Navy_SEAL_Medic";
						rank = SERGEANT;
						position[] = {11, 0, 0};
					};
				};
				
				class BB_SF_Desert {
					name = "U.S. Desert Special Forces";
					faction = BB_US_SOF;
					rarityGroup = 0.01;
					
					class Unit0 {
						side = TWest;
						vehicle = "Desert_SOF_TL";
						rank = LIEUTENANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TWest;
						vehicle = "Desert_SOF_MG";
						rank = SERGEANT;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TWest;
						vehicle = "Desert_SOF_GL";
						rank = SERGEANT;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TWest;
						vehicle = "Desert_SOF_Marksman";
						rank = SERGEANT;
						position[] = {7, 0, 0};
					};
					
					class Unit4 {
						side = TWest;
						vehicle = "Desert_SOF_AT";
						rank = SERGEANT;
						position[] = {9, 0, 0};
					};
					
					class Unit5 {
						side = TWest;
						vehicle = "Desert_SOF_Medic";
						rank = SERGEANT;
						position[] = {11, 0, 0};
					};
				};
			};
		};
		
		class US_Army_Groups {
			name = "U.S. Army";
			
			class Infantry {
				name = "$STR_CfgGroups_West_USMC_Infantry";
				
				class US_Army_InfSquad {
					name = "$STR_CfgGroups_West_USMC_Infantry_USMC_InfSquad";
					faction = BB_US_SOF;
					rarityGroup = 0.5;
					
					class Unit0 {
						side = TWest;
						vehicle = "US_Army_Soldier_SL";
						rank = LIEUTENANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TWest;
						vehicle = "US_Army_Soldier_TL";
						rank = SERGEANT;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TWest;
						vehicle = "US_Army_Soldier_AR";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TWest;
						vehicle = "US_Army_Soldier_LAT";
						rank = CORPORAL;
						position[] = {7, 0, 0};
					};
					
					class Unit4 {
						side = TWest;
						vehicle = "Mercenary_Default20b";
						rank = PRIVATE;
						position[] = {9, 0, 0};
					};
					
					class Unit5 {
						side = TWest;
						vehicle = "US_Army_Soldier_TL";
						rank = SERGEANT;
						position[] = {12, 0, 0};
					};
					
					class Unit6 {
						side = TWest;
						vehicle = "US_Army_Soldier_AR";
						rank = CORPORAL;
						position[] = {14, 0, 0};
					};
					
					class Unit7 {
						side = TWest;
						vehicle = "US_Army_Soldier_LAT";
						rank = CORPORAL;
						position[] = {16, 0, 0};
					};
					
					class Unit8 {
						side = TWest;
						vehicle = "Mercenary_Default20b";
						rank = PRIVATE;
						position[] = {18, 0, 0};
					};
					
					class Unit9 {
						side = TWest;
						vehicle = "US_Army_Soldier_TL";
						rank = SERGEANT;
						position[] = {3, -5, 0};
					};
					
					class Unit10 {
						side = TWest;
						vehicle = "US_Army_Soldier_AR";
						rank = CORPORAL;
						position[] = {5, -5, 0};
					};
					
					class Unit11 {
						side = TWest;
						vehicle = "US_Army_Soldier_LAT";
						rank = CORPORAL;
						position[] = {7, -5, 0};
					};
					
					class Unit12 {
						side = TWest;
						vehicle = "Mercenary_Default20b";
						rank = PRIVATE;
						position[] = {9, -5, 0};
					};
				};
				
				class US_Army_FireTeam {
					name = "$STR_CfgGroups_West_USMC_Infantry_USMC_FireTeam";
					faction = BB_US_SOF;
					rarityGroup = 0.05;
					
					class Unit0 {
						side = TWest;
						vehicle = "US_Army_Soldier_TL";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TWest;
						vehicle = "US_Army_Soldier_AR";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TWest;
						vehicle = "US_Army_Soldier_LAT";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TWest;
						vehicle = "Mercenary_Default20b";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
				};
				
				class US_Army_FireTeam_MG {
					name = "$STR_CfgGroups_West_USMC_Infantry_USMC_FireTeam_MG";
					faction = BB_US_SOF;
					rarityGroup = 0.1;
					
					class Unit0 {
						side = TWest;
						vehicle = "US_Army_Soldier_TL";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TWest;
						vehicle = "US_Army_Soldier_MG";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TWest;
						vehicle = "US_Army_Soldier_AR";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TWest;
						vehicle = "US_Army_Soldier_LAT";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
				};
				
				class US_Army_FireTeam_AT {
					name = "$STR_CfgGroups_West_USMC_Infantry_USMC_FireTeam_AT";
					faction = BB_US_SOF;
					rarityGroup = 0.1;
					
					class Unit0 {
						side = TWest;
						vehicle = "US_Army_Soldier_TL";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TWest;
						vehicle = "US_Army_Soldier_AR";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TWest;
						vehicle = "US_Army_Soldier_AT";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TWest;
						vehicle = "US_Army_Soldier_LAT";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
				};
				
				class US_Army_FireTeam_Support {
					name = "$STR_CfgGroups_West_USMC_Infantry_USMC_FireTeam_Support";
					faction = BB_US_SOF;
					rarityGroup = 0.05;
					
					class Unit0 {
						side = TWest;
						vehicle = "US_Army_Soldier_TL";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TWest;
						vehicle = "US_Army_Soldier_AR";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TWest;
						vehicle = "US_Army_Soldier_LAT";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TWest;
						vehicle = "US_Army_Soldier_Medic";
						rank = CORPORAL;
						position[] = {7, 0, 0};
					};
				};
				
				class US_Army_HeavyATTeam {
					name = "$STR_CfgGroups_West_USMC_Infantry_USMC_HeavyATTeam";
					faction = BB_US_SOF;
					rarityGroup = 0.15;
					
					class Unit0 {
						side = TWest;
						vehicle = "US_Army_Soldier_HAT";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TWest;
						vehicle = "US_Army_Soldier_AT";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TWest;
						vehicle = "US_Army_Soldier_LAT";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
				};
			};
			
			class Motorized {
				name = "$STR_CfgGroups_West_USMC_Motorized";
				
				class US_Army_MotInfSection {
					name = "$STR_CfgGroups_West_USMC_Motorized_USMC_MotInfSection";
					faction = BB_US_SOF;
					rarityGroup = 0.2;
					
					class Unit0 {
						side = TWest;
						vehicle = "US_Army_Soldier_TL";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TWest;
						vehicle = "HMMWV_M2_USArmy";
						rank = SERGEANT;
						position[] = {-5, 0, 0};
					};
					
					class Unit2 {
						side = TWest;
						vehicle = "HMMWV_Mk19_USArmy";
						rank = CORPORAL;
						position[] = {-5, -7, 0};
					};
					
					class Unit3 {
						side = TWest;
						vehicle = "US_Army_Soldier_AR";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit4 {
						side = TWest;
						vehicle = "US_Army_Soldier_AT";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit5 {
						side = TWest;
						vehicle = "US_Army_Soldier_AR";
						rank = CORPORAL;
						position[] = {7, 0, 0};
					};
					
					class Unit6 {
						side = TWest;
						vehicle = "US_Army_Soldier_LAT";
						rank = PRIVATE;
						position[] = {9, 0, 0};
					};
					
					class Unit7 {
						side = TWest;
						vehicle = "Mercenary_Default20b";
						rank = PRIVATE;
						position[] = {11, 0, 0};
					};
				};
				
				class US_Army_MotInfSection_AT {
					name = "$STR_CfgGroups_West_USMC_Motorized_USMC_MotInfSection_AT";
					faction = BB_US_SOF;
					rarityGroup = 0.15;
					
					class Unit0 {
						side = TWest;
						vehicle = "US_Army_Soldier_TL";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TWest;
						vehicle = "HMMWV_TOW_USArmy";
						rank = SERGEANT;
						position[] = {-5, 0, 0};
					};
					
					class Unit2 {
						side = TWest;
						vehicle = "HMMWV_TOW_USArmy";
						rank = CORPORAL;
						position[] = {-5, -7, 0};
					};
					
					class Unit3 {
						side = TWest;
						vehicle = "US_Army_Soldier_AR";
						rank = PRIVATE;
						position[] = {3, 0, 0};
					};
				};
			};
		};
	};
	
	class Guerrila {
		name = $STR_GUERRILA;
		
		class BB_TERROR_GROUP {
			name = "Middle Eastern Terrorists";
			
			class Infantry {
				name = "$STR_CfgGroups_Guerrila_GUE_Infantry";
				
				class TERROR_InfSquad {
					name = "$STR_CfgGroups_Guerrila_GUE_Infantry_GUE_InfSquad";
					faction = "Terrorist";
					rarityGroup = 0.8;
					
					class Unit0 {
						side = TGuerrila;
						vehicle = "Terrorist1";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TGuerrila;
						vehicle = "Terrorist5";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TGuerrila;
						vehicle = "Terrorist9";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TGuerrila;
						vehicle = "Terrorist2";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
					
					class Unit4 {
						side = TGuerrila;
						vehicle = "Terrorist4";
						rank = PRIVATE;
						position[] = {9, 0, 0};
					};
					
					class Unit5 {
						side = TGuerrila;
						vehicle = "Terrorist5";
						rank = PRIVATE;
						position[] = {11, 0, 0};
					};
					
					class Unit6 {
						side = TGuerrila;
						vehicle = "Terrorist3";
						rank = PRIVATE;
						position[] = {13, 0, 0};
					};
				};
				
				class TERROR_InfSquad_Assault {
					name = "$STR_CfgGroups_Guerrila_GUE_Infantry_GUE_InfSquad_Assault";
					faction = "Terrorist";
					rarityGroup = 0.6;
					
					class Unit0 {
						side = TGuerrila;
						vehicle = "Terrorist1";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TGuerrila;
						vehicle = "Terrorist5";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TGuerrila;
						vehicle = "Terrorist10";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TGuerrila;
						vehicle = "Terrorist6";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
					
					class Unit4 {
						side = TGuerrila;
						vehicle = "Terrorist9";
						rank = PRIVATE;
						position[] = {9, 0, 0};
					};
					
					class Unit5 {
						side = TGuerrila;
						vehicle = "Terrorist10";
						rank = PRIVATE;
						position[] = {11, 0, 0};
					};
					
					class Unit6 {
						side = TGuerrila;
						vehicle = "Terrorist6";
						rank = PRIVATE;
						position[] = {13, 0, 0};
					};
					
					class Unit7 {
						side = TGuerrila;
						vehicle = "Terrorist3";
						rank = PRIVATE;
						position[] = {15, 0, 0};
					};
					
					class Unit8 {
						side = TGuerrila;
						vehicle = "Terrorist12";
						rank = PRIVATE;
						position[] = {17, 0, 0};
					};
				};
				
				class TERROR_InfSquad_Weapons {
					name = "$STR_CfgGroups_Guerrila_GUE_Infantry_GUE_InfSquad_Weapons";
					faction = "Terrorist";
					rarityGroup = 0.9;
					
					class Unit0 {
						side = TGuerrila;
						vehicle = "Terrorist2";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TGuerrila;
						vehicle = "Terrorist10";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TGuerrila;
						vehicle = "Terrorist6";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TGuerrila;
						vehicle = "Terrorist10";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
					
					class Unit4 {
						side = TGuerrila;
						vehicle = "Terrorist5";
						rank = PRIVATE;
						position[] = {9, 0, 0};
					};
					
					class Unit5 {
						side = TGuerrila;
						vehicle = "Terrorist6";
						rank = PRIVATE;
						position[] = {11, 0, 0};
					};
				};
				
				class TERROR_InfTeam_1 {
					name = "$STR_CfgGroups_Guerrila_GUE_Infantry_GUE_InfTeam_1";
					faction = "Terrorist";
					rarityGroup = 1.0;
					
					class Unit0 {
						side = TGuerrila;
						vehicle = "Terrorist3";
						rank = CORPORAL;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TGuerrila;
						vehicle = "Terrorist9";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TGuerrila;
						vehicle = "Terrorist6";
						rank = PRIVATE;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TGuerrila;
						vehicle = "Terrorist5";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
				};
				
				class TERROR_InfTeam_2 {
					name = "$STR_CfgGroups_Guerrila_GUE_Infantry_GUE_InfTeam_2";
					faction = "Terrorist";
					rarityGroup = 1.0;
					
					class Unit0 {
						side = TGuerrila;
						vehicle = "Terrorist2";
						rank = CORPORAL;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TGuerrila;
						vehicle = "Terrorist10";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TGuerrila;
						vehicle = "Terrorist5";
						rank = PRIVATE;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TGuerrila;
						vehicle = "Terrorist3";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
				};
				
				class TERROR_InfTeam_AT {
					name = "$STR_CfgGroups_Guerrila_GUE_Infantry_GUE_InfTeam_AT";
					faction = "Terrorist";
					rarityGroup = 0.8;
					
					class Unit0 {
						side = TGuerrila;
						vehicle = "Terrorist6";
						rank = CORPORAL;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TGuerrila;
						vehicle = "Terrorist6";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TGuerrila;
						vehicle = "Terrorist9";
						rank = PRIVATE;
						position[] = {5, 0, 0};
					};
				};
				
				class TERROR_GrpInf_TeamAA {
					name = "$STR_CfgGroups_Guerrila_GUE_Infantry_GUE_GrpInf_TeamAA";
					faction = "Terrorist";
					rarityGroup = 0.2;
					
					class Unit0 {
						side = TGuerrila;
						vehicle = "Terrorist1";
						rank = CORPORAL;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TGuerrila;
						vehicle = "Terrorist7";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TGuerrila;
						vehicle = "Terrorist7";
						rank = PRIVATE;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TGuerrila;
						vehicle = "Terrorist9";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
				};
			};
			
			class Motorized {
				name = "$STR_CfgGroups_Guerrila_GUE_Motorized";
				
				class TERROR_MotInfSection {
					name = "$STR_CfgGroups_Guerrila_GUE_Motorized_GUE_MotInfSection";
					faction = "Terrorist";
					rarityGroup = 0.25;
					
					class Unit0 {
						side = TGuerrila;
						vehicle = "Terrorist2";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TGuerrila;
						vehicle = "Offroad_DSHKM_TERROR";
						rank = CORPORAL;
						position[] = {-5, 0, 0};
					};
					
					class Unit2 {
						side = TGuerrila;
						vehicle = "Offroad_SPG9_TERROR";
						rank = CORPORAL;
						position[] = {-5, -7, 0};
					};
					
					class Unit3 {
						side = TGuerrila;
						vehicle = "Pickup_PK_TERROR";
						rank = CORPORAL;
						position[] = {-5, -14, 0};
					};
					
					class Unit4 {
						side = TGuerrila;
						vehicle = "Terrorist10";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit5 {
						side = TGuerrila;
						vehicle = "Terrorist4";
						rank = PRIVATE;
						position[] = {5, 0, 0};
					};
					
					class Unit6 {
						side = TGuerrila;
						vehicle = "Terrorist11";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
					
					class Unit7 {
						side = TGuerrila;
						vehicle = "Terrorist9";
						rank = PRIVATE;
						position[] = {9, 0, 0};
					};
					
					class Unit8 {
						side = TGuerrila;
						vehicle = "Terrorist3";
						rank = PRIVATE;
						position[] = {11, 0, 0};
					};
				};
			};
		};
	};
	
	class East {
		name = $STR_EAST;
		
		class BB_TERROR_GROUP_EAST {
			name = "Middle Eastern Terrorists";
			
			class Infantry {
				name = "$STR_CfgGroups_Guerrila_GUE_Infantry";
				
				class TERROR_InfSquad {
					name = "$STR_CfgGroups_Guerrila_GUE_Infantry_GUE_InfSquad";
					faction = "Terrorist";
					rarityGroup = 0.8;
					
					class Unit0 {
						side = TEast;
						vehicle = "ETerrorist1";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TEast;
						vehicle = "ETerrorist5";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TEast;
						vehicle = "ETerrorist9";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TEast;
						vehicle = "ETerrorist2";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
					
					class Unit4 {
						side = TEast;
						vehicle = "ETerrorist4";
						rank = PRIVATE;
						position[] = {9, 0, 0};
					};
					
					class Unit5 {
						side = TEast;
						vehicle = "ETerrorist5";
						rank = PRIVATE;
						position[] = {11, 0, 0};
					};
					
					class Unit6 {
						side = TEast;
						vehicle = "ETerrorist3";
						rank = PRIVATE;
						position[] = {13, 0, 0};
					};
				};
				
				class TERROR_InfSquad_Assault {
					name = "$STR_CfgGroups_Guerrila_GUE_Infantry_GUE_InfSquad_Assault";
					faction = "Terrorist";
					rarityGroup = 0.6;
					
					class Unit0 {
						side = TEast;
						vehicle = "ETerrorist1";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TEast;
						vehicle = "ETerrorist5";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TEast;
						vehicle = "ETerrorist10";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TEast;
						vehicle = "ETerrorist6";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
					
					class Unit4 {
						side = TEast;
						vehicle = "ETerrorist9";
						rank = PRIVATE;
						position[] = {9, 0, 0};
					};
					
					class Unit5 {
						side = TEast;
						vehicle = "ETerrorist10";
						rank = PRIVATE;
						position[] = {11, 0, 0};
					};
					
					class Unit6 {
						side = TEast;
						vehicle = "ETerrorist6";
						rank = PRIVATE;
						position[] = {13, 0, 0};
					};
					
					class Unit7 {
						side = TEast;
						vehicle = "ETerrorist3";
						rank = PRIVATE;
						position[] = {15, 0, 0};
					};
					
					class Unit8 {
						side = TEast;
						vehicle = "ETerrorist12";
						rank = PRIVATE;
						position[] = {17, 0, 0};
					};
				};
				
				class TERROR_InfSquad_Weapons {
					name = "$STR_CfgGroups_Guerrila_GUE_Infantry_GUE_InfSquad_Weapons";
					faction = "Terrorist";
					rarityGroup = 0.9;
					
					class Unit0 {
						side = TEast;
						vehicle = "ETerrorist2";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TEast;
						vehicle = "ETerrorist10";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TEast;
						vehicle = "ETerrorist6";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TEast;
						vehicle = "ETerrorist10";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
					
					class Unit4 {
						side = TEast;
						vehicle = "ETerrorist5";
						rank = PRIVATE;
						position[] = {9, 0, 0};
					};
					
					class Unit5 {
						side = TEast;
						vehicle = "ETerrorist6";
						rank = PRIVATE;
						position[] = {11, 0, 0};
					};
				};
				
				class TERROR_InfTeam_1 {
					name = "$STR_CfgGroups_Guerrila_GUE_Infantry_GUE_InfTeam_1";
					faction = "Terrorist";
					rarityGroup = 1.0;
					
					class Unit0 {
						side = TEast;
						vehicle = "ETerrorist3";
						rank = CORPORAL;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TEast;
						vehicle = "ETerrorist9";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TEast;
						vehicle = "ETerrorist6";
						rank = PRIVATE;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TEast;
						vehicle = "ETerrorist5";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
				};
				
				class TERROR_InfTeam_2 {
					name = "$STR_CfgGroups_Guerrila_GUE_Infantry_GUE_InfTeam_2";
					faction = "Terrorist";
					rarityGroup = 1.0;
					
					class Unit0 {
						side = TEast;
						vehicle = "ETerrorist2";
						rank = CORPORAL;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TEast;
						vehicle = "ETerrorist10";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TEast;
						vehicle = "ETerrorist5";
						rank = PRIVATE;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TEast;
						vehicle = "ETerrorist3";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
				};
				
				class TERROR_InfTeam_AT {
					name = "$STR_CfgGroups_Guerrila_GUE_Infantry_GUE_InfTeam_AT";
					faction = "Terrorist";
					rarityGroup = 0.8;
					
					class Unit0 {
						side = TEast;
						vehicle = "ETerrorist6";
						rank = CORPORAL;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TEast;
						vehicle = "ETerrorist6";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TEast;
						vehicle = "ETerrorist9";
						rank = PRIVATE;
						position[] = {5, 0, 0};
					};
				};
				
				class TERROR_GrpInf_TeamAA {
					name = "$STR_CfgGroups_Guerrila_GUE_Infantry_GUE_GrpInf_TeamAA";
					faction = "Terrorist";
					rarityGroup = 0.2;
					
					class Unit0 {
						side = TEast;
						vehicle = "ETerrorist1";
						rank = CORPORAL;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TEast;
						vehicle = "ETerrorist7";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = TEast;
						vehicle = "ETerrorist7";
						rank = PRIVATE;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = TEast;
						vehicle = "ETerrorist9";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
				};
			};
			
			class Motorized {
				name = "$STR_CfgGroups_Guerrila_GUE_Motorized";
				
				class TERROR_MotInfSection {
					name = "$STR_CfgGroups_Guerrila_GUE_Motorized_GUE_MotInfSection";
					faction = "Terrorist";
					rarityGroup = 0.25;
					
					class Unit0 {
						side = TEast;
						vehicle = "ETerrorist2";
						rank = SERGEANT;
						position[] = {0, 5, 0};
					};
					
					class Unit1 {
						side = TEast;
						vehicle = "EOffroad_DSHKM_TERROR";
						rank = CORPORAL;
						position[] = {-5, 0, 0};
					};
					
					class Unit2 {
						side = TEast;
						vehicle = "EOffroad_SPG9_TERROR";
						rank = CORPORAL;
						position[] = {-5, -7, 0};
					};
					
					class Unit3 {
						side = TEast;
						vehicle = "EPickup_PK_TERROR";
						rank = CORPORAL;
						position[] = {-5, -14, 0};
					};
					
					class Unit4 {
						side = TEast;
						vehicle = "ETerrorist10";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit5 {
						side = TEast;
						vehicle = "ETerrorist4";
						rank = PRIVATE;
						position[] = {5, 0, 0};
					};
					
					class Unit6 {
						side = TEast;
						vehicle = "ETerrorist11";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
					
					class Unit7 {
						side = TEast;
						vehicle = "ETerrorist9";
						rank = PRIVATE;
						position[] = {9, 0, 0};
					};
					
					class Unit8 {
						side = TEast;
						vehicle = "ETerrorist3";
						rank = PRIVATE;
						position[] = {11, 0, 0};
					};
				};
			};
		};
	};
};
