// Generated by unRap v1.06 by Kegetys

class CfgGlasses {
	class Pro_Helmet {
		scope = public;
		name = "Pro Helmet";
		model = "\bb_mercs_desert\prohelmet.p3d";
		identityTypes[] = {"Pro_Helmet", 1, "Pro_Helmet1", 1};
		disabled = 1;
	};
	
	class Pro_Helmet_g {
		scope = public;
		name = "Pro Helmet (glasses)";
		model = "\bb_mercs_desert\prohelmet_g.p3d";
		identityTypes[] = {"Pro_Helmet", 1};
		disabled = 1;
	};
	
	class Pro_Helmet_2 {
		scope = public;
		name = "Pro Helmet (goggles)";
		model = "\bb_mercs_desert\prohelmet_2.p3d";
		identityTypes[] = {"Pro_Helmet", 1};
		disabled = 1;
	};
	
	class Kevlar_Helmet {
		scope = public;
		name = "Kevlar Helmet";
		model = "\bb_mercs_desert\kevlar_helmet.p3d";
		identityTypes[] = {"Kevlar_Helmet", 1, "green_mask", 1};
		disabled = 1;
	};
	
	class Kevlar_Helmet_g {
		scope = public;
		name = "Kevlar Helmet (glasses)";
		model = "\bb_mercs_desert\kevlar_helmet_g.p3d";
		identityTypes[] = {"Kevlar_Helmet", 1};
		disabled = 1;
	};
	
	class wdl_helmet {
		scope = public;
		name = "helmet (wdl)";
		model = "\bb_mercs_desert\wdl_helmet.p3d";
		identityTypes[] = {"wdl_helmet", 1};
		disabled = 1;
	};
	
	class Barett {
		scope = public;
		name = "beret (red)";
		model = "\bb_mercs_desert\barett.p3d";
		identityTypes[] = {"Barett", 1};
		disabled = 1;
	};
	
	class US_green_beret {
		scope = public;
		name = "beret (green)";
		model = "\bb_mercs_desert\green_beret.p3d";
		identityTypes[] = {"green_beret", 1};
	};
	
	class US_black_beret {
		scope = public;
		name = "beret (black)";
		model = "\bb_mercs_desert\black_beret.p3d";
		identityTypes[] = {"black_beret", 1};
	};
	
	class Barett_g {
		scope = public;
		name = "Barett (glasses)";
		model = "\bb_mercs_desert\barett_g.p3d";
		identityTypes[] = {"Barett", 1};
		disabled = 1;
	};
	
	class Bdu_cap {
		scope = public;
		name = "Bdu Cap";
		model = "\bb_mercs_desert\bdu_cap.p3d";
		identityTypes[] = {"bdu_cap", 1};
		disabled = 1;
	};
	
	class Bdu_cap_g {
		scope = public;
		name = "Bdu Cap (glasses)";
		model = "\bb_mercs_desert\bdu_cap_g.p3d";
		identityTypes[] = {"bdu_cap", 1};
		disabled = 1;
	};
	
	class b_TacticalGlasses {
		scope = public;
		name = "Tactical Glasses (black)";
		model = "\bb_mercs_desert\TacticalGlasses.p3d";
		identityTypes[] = {"b_TacticalGlasses", 1};
		disabled = 1;
	};
	
	class headset {
		scope = public;
		name = "headset";
		model = "\bb_mercs_desert\headset.p3d";
		identityTypes[] = {"headset", 1};
		disabled = 1;
	};
	
	class headset_g {
		scope = public;
		name = "headset+glasses";
		model = "\bb_mercs_desert\headset_g.p3d";
		identityTypes[] = {"headset", 1};
		disabled = 1;
	};
	
	class gasmask {
		scope = public;
		name = "gas mask";
		model = "\bb_mercs_desert\gasmask.p3d";
		identityTypes[] = {"gasmask", 1};
		disabled = 1;
	};
	
	class gasmask2 {
		scope = public;
		name = "gas mask 2";
		model = "\bb_mercs_desert\gasmask2.p3d";
		identityTypes[] = {"gasmask2", 1, "biohazard2", 1};
		disabled = 1;
	};
	
	class gasmask_helmet {
		scope = public;
		name = "gas mask + helmet";
		model = "\bb_mercs_desert\gasmask_helmet.p3d";
		identityTypes[] = {"gasmask_helmet", 1};
		disabled = 1;
	};
	
	class gasmask_red {
		scope = public;
		name = "gas mask (red glasses)";
		model = "\bb_mercs_desert\gasmask_red.p3d";
		identityTypes[] = {"gasmask_red", 1};
		disabled = 1;
	};
	
	class gasmask_helmet2 {
		scope = public;
		name = "gas mask + helmet 2";
		model = "\bb_mercs_desert\gasmask_helmet2.p3d";
		identityTypes[] = {"gasmask_helmet2", 1, "biohazard", 1};
		disabled = 1;
	};
	
	class pilot_mask {
		scope = public;
		name = "pilot mask";
		model = "\bb_mercs_desert\pilot_mask.p3d";
		identityTypes[] = {"pilot_mask", 1};
		disabled = 1;
	};
	
	class pilot_mask_v {
		scope = public;
		name = "pilot mask + visor";
		model = "\bb_mercs_desert\pilot_mask_v.p3d";
		identityTypes[] = {"pilot_mask_v", 1};
		disabled = 1;
	};
	
	class pilot_v {
		scope = public;
		name = "pilot visor";
		model = "\bb_mercs_desert\pilot_v.p3d";
		identityTypes[] = {"pilot_v", 1};
		disabled = 1;
	};
	
	class skull_cap {
		scope = public;
		name = "skull cap";
		model = "\bb_mercs_desert\skull_cap.p3d";
		identityTypes[] = {"skull_cap", 1};
		disabled = 1;
	};
	
	class skull_cap2 {
		scope = protected;
		name = "skull cap";
		model = "\bb_mercs_desert\skull_cap2.p3d";
		identityTypes[] = {"skull_cap2", 1};
		disabled = 1;
	};
	
	class taliban_hat_shadow {
		scope = protected;
		name = "taliban hat shadow";
		model = "\bb_mercs_desert\taliban_hat_shadow.p3d";
		identityTypes[] = {"taliban_hat_shadow", 1};
		disabled = 1;
	};
	
	class dive_mask {
		scope = public;
		name = "dive mask";
		model = "\bb_mercs_desert\diving_glasses.p3d";
		identityTypes[] = {"dive_mask", 1};
		disabled = 1;
	};
	
	class BlackSun_sof_w {
		scope = protected;
		name = $STR_CFG_GLASSES_SHADES_BLACK;
		model = "\Ca\characters\glasses\BlackSun";
		identityTypes[] = {"SOF_Shades", 1};
		disabled = 1;
	};
	
	class RedSun_sof_w {
		scope = protected;
		name = $STR_CFG_GLASSES_SHADES_RED;
		model = "\Ca\characters\glasses\RedSun";
		identityTypes[] = {"SOF_Shades", 1};
		disabled = 1;
	};
	
	class None_sof_w {
		scope = protected;
		name = $STR_CFG_GLASSES_NONE;
		model = "";
		identityTypes[] = {"SOF_Shades", 2};
		disabled = 2;
	};
	
	class goggles_winter {
		scope = public;
		name = "Combat Goggles";
		model = "\bb_mercs_desert\goggles_winter.p3d";
		identityTypes[] = {"goggles_winter", 1};
		disabled = 1;
	};
};
