// Generated by unRap v1.06 by Kegetys

class CfgHeads {
	class DefaultHead;	// External class reference
	
	class MercHead_tan : DefaultHead {
		model = "\ca\characters\Heads\male\DefaultHead\DefaultHead";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\Characters\Heads\Male\DefaultHead\data\hhl_white.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class MercHead_gas : DefaultHead {
		model = "\ca\characters\Heads\male\DefaultHead\DefaultHead";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\Characters\Heads\Male\DefaultHead\data\hhl_white.rvmat", "bb_mercs_desert\faces\hhl_white_wound1.rvmat", "bb_mercs_desert\faces\hhl_white_wound2.rvmat"};
		};
	};
	
	class Leon_head : DefaultHead {
		model = "\bb_mercs_desert\Leon_Head";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters\heads\male\defaulthead\data\hhl_white.rvmat", "ca\characters\Heads\male\DefaultHead\Data\hhl_Wounds.rvmat", "ca\characters\Heads\male\DefaultHead\Data\hhl_Wounds.rvmat"};
		};
	};
	
	class SFBeardHead : DefaultHead {
		model = "\bb_mercs_desert\beard_head";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\Characters\Heads\Male\DefaultHead\data\hhl_white.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class SFSkullMaskHead : DefaultHead {
		model = "\bb_mercs_desert\skull_mask.p3d";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\Characters\Heads\Male\DefaultHead\data\hhl_white.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class SFSkullMaskHead_Black : DefaultHead {
		model = "\bb_mercs_desert\skull_mask.p3d";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\Characters\Heads\Male\DefaultHead\data\hhl_white.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class SFGreenMaskHead : DefaultHead {
		model = "\bb_mercs_desert\green_mask.p3d";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\Characters\Heads\Male\DefaultHead\data\hhl_white.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class Terrorist_mask : DefaultHead {
		model = "\bb_mercs_desert\MaskHead_1";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\Characters\Heads\Male\DefaultHead\data\hhl_white.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class Terrorist_mask2 : DefaultHead {
		model = "\bb_mercs_desert\MaskHead_2";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\Characters\Heads\Male\DefaultHead\data\hhl_white.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class Taliban_Head : DefaultHead {
		model = "\bb_mercs_desert\Taliban_head";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters\heads\male\blackhead\data\hhl_black.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class Taliban_Head2 : DefaultHead {
		model = "\bb_mercs_desert\Taliban_head2";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters\heads\male\blackhead\data\hhl_black.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class Taliban_Head3 : DefaultHead {
		model = "\bb_mercs_desert\Taliban_head3";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters\heads\male\blackhead\data\hhl_black.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class Taliban_Head4 : DefaultHead {
		model = "\bb_mercs_desert\Taliban_head4";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters\heads\male\blackhead\data\hhl_black.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class YKufiyaMaskHead : DefaultHead {
		model = "\bb_mercs_desert\ykufiya_mask.p3d";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\Characters\Heads\Male\DefaultHead\data\hhl_white.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class MaskHead_winter : DefaultHead {
		model = "\bb_mercs_desert\MaskHead_snow.p3d";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\Characters\Heads\Male\DefaultHead\data\hhl_white.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class MaskHead_winter_Black : DefaultHead {
		model = "\bb_mercs_desert\MaskHead_snow.p3d";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\Characters\Heads\Male\DefaultHead\data\hhl_white.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class MaskHead_snow : DefaultHead {
		model = "\bb_mercs_desert\MaskHead_snow1.p3d";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\Characters\Heads\Male\DefaultHead\data\hhl_white.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
	
	class MaskHead_snow_Black : DefaultHead {
		model = "\bb_mercs_desert\MaskHead_snow1.p3d";
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\Characters\Heads\Male\DefaultHead\data\hhl_white.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds1.rvmat", "ca\characters\heads\male\blackhead\data\hhl_black_Wounds2.rvmat"};
		};
	};
};
