// Generated by unRap v1.06 by Kegetys

class CfgIdentities {
	class Pro_Helmet {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male01EN";
		pitch = 1;
		glasses = "Pro_Helmet";
	};
	
	class Pro_Helmet1 {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male01EN";
		pitch = 1;
		glasses = "Pro_Helmet";
	};
	
	class Kevlar_Helmet {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "Kevlar_Helmet";
	};
	
	class Barett {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male03EN";
		pitch = 1;
		glasses = "Barett";
	};
	
	class green_beret {
		name = "$STR_Anything";
		face = "Default";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "US_green_beret";
	};
	
	class black_beret {
		name = "$STR_Anything";
		face = "Default";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "US_black_beret";
	};
	
	class bdu_cap {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male04EN";
		pitch = 1;
		glasses = BDU_CAP;
	};
	
	class b_TacticalGlasses {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male05EN";
		pitch = 1;
		glasses = "b_TacticalGlasses";
	};
	
	class headset {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male01EN";
		pitch = 1;
		glasses = "headset";
	};
	
	class gasmask {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "gasmask";
	};
	
	class gasmask2 {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "gasmask2";
	};
	
	class gasmask_helmet {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male03EN";
		pitch = 1;
		glasses = "gasmask_helmet";
	};
	
	class gasmask_red {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male04EN";
		pitch = 1;
		glasses = "gasmask_red";
	};
	
	class gasmask_helmet2 {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male03EN";
		pitch = 1;
		glasses = "gasmask_helmet2";
	};
	
	class biohazard {
		name = "$STR_Anything";
		face = "Merc_Face_gas";
		speaker = "Male03EN";
		pitch = 1;
		glasses = "gasmask_helmet2";
	};
	
	class pilot_mask {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male05EN";
		pitch = 1;
		glasses = "pilot_mask";
	};
	
	class pilot_mask_v {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male05EN";
		pitch = 1;
		glasses = "pilot_mask_v";
	};
	
	class pilot_v {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male05EN";
		pitch = 1;
		glasses = "pilot_v";
	};
	
	class biohazard2 {
		name = "$STR_Anything";
		face = "Merc_Face_gas";
		speaker = "Male03EN";
		pitch = 1;
		glasses = "gasmask2";
	};
	
	class wdl_helmet {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "wdl_helmet";
	};
	
	class Gangsta {
		name = "$STR_Anything";
		face = "gangsta_faces";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "RedSun";
	};
	
	class Gangsta2 {
		name = "$STR_Anything";
		face = "gangsta_faces";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "BlueSun";
	};
	
	class GangstaH {
		name = "$STR_Anything";
		face = "gangsta_faces";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "None";
	};
	
	class skull_cap {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "skull_cap";
	};
	
	class skull_cap2 {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "skull_cap2";
	};
	
	class Taliban {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "none";
	};
	
	class Terrorist {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "none";
	};
	
	class TerroristUnmasked {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "none";
	};
	
	class Terror_Boss {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "none";
	};
	
	class taliban_hat_shadow {
		name = "$STR_Anything";
		face = "Merc_Face2";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "taliban_hat_shadow";
	};
	
	class green_mask {
		name = "$STR_Anything";
		face = "Merc_Face1";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "Kevlar_Helmet";
	};
	
	class dive_mask {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "dive_mask";
	};
	
	class SOF_Shades {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "BlackSun_sof_w";
	};
	
	class goggles_winter {
		name = "$STR_Anything";
		face = "Man";
		speaker = "Male02EN";
		pitch = 1;
		glasses = "goggles_winter";
	};
};
