// Generated by unRap v1.06 by Kegetys

class CfgVehicleClasses {
	class Man;	// External class reference
	
	class CAManBase : Man {
		class TalkTopics;	// External class reference
		
		class HitPoints {
			class HitHead;	// External class reference
			class HitBody;	// External class reference
		};
	};
	
	class BB_Mercenary {
		displayName = "Mercenaries (Desert)";
	};
	
	class BB_MercenaryW {
		displayName = "Mercenaries (Woodland)";
	};
	
	class BB_MercenaryB {
		displayName = "Mercenaries (BlackOps)";
	};
	
	class BB_MercenaryP {
		displayName = "Mercenaries (Pilots)";
	};
	
	class BB_MercenaryG {
		displayName = "Gangstas";
	};
	
	class BB_MercenaryTE {
		displayName = "Middle Eastern Terrorists";
	};
	
	class BB_MercenaryEW {
		displayName = "Winter OPFOR";
	};
	
	class BB_MercenaryTE_CARS {
		displayName = "Middle Eastern Terrorists (Cars)";
	};
	
	class BB_MercenaryT {
		displayName = "Taliban";
	};
	
	class BB_Seals {
		displayName = "US Navy SEALs";
	};
	
	class BB_WINTER_SOF {
		displayName = "US SOF Winter";
	};
	
	class BB_US_Army {
		displayName = "US Army (Men)";
	};
	
	class BB_US_Army_Cars {
		displayName = "US Army (Cars)";
	};
	
	class BB_US_SOF_desert {
		displayName = "US SOF Desert";
	};
};
