// config.bin - 12:59:20 06/17/17, generated in 1.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

#include "CfgPatches.hpp"
#include "CfgFactionClasses.hpp"
#include "CfgHeads.hpp"
class Man;	// External class reference
class Custom;	// External class reference
class Default;	// External class reference
#include "CfgFaces.hpp"
#include "CfgIdentities.hpp"
#include "CfgVehicleClasses.hpp"
#include "CfgGlasses.hpp"
#include "CfgVehicles.hpp"
#include "CfgGroups.hpp"
