// Generated by unRap v1.06 by Kegetys

class CfgSounds {
	class police_Siren {
		sound[] = {"\American_Law_Enforcement\sounds\policeSiren2.ogg", 1, 1, 250};
		name = "police_Siren";
		titles[] = {};
	};
	
	class radioSound1 {
		sound[] = {"\American_Law_Enforcement\sounds\policeradio.wav", 1, 1};
		name = "radioSound1";
		titles[] = {};
	};
	
	class radioSound2 {
		sound[] = {"\American_Law_Enforcement\sounds\policeradio2.wav", 1, 1};
		name = "radioSound2";
		titles[] = {};
	};
	
	class radioSound3 {
		sound[] = {"\American_Law_Enforcement\sounds\policeradio2.wav", 1, 1};
		name = "radioSound3";
		titles[] = {};
	};
};
