// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class Land;	// External class reference
	
	class LandVehicle : Land {};
	
	class Car : LandVehicle {
		class HitPoints {
			class HitBody;	// External class reference
			class HitLFWheel;	// External class reference
			class HitLBWheel;	// External class reference
			class HitLMWheel;	// External class reference
			class HitLF2Wheel;	// External class reference
			class HitRFWheel;	// External class reference
			class HitRBWheel;	// External class reference
			class HitRMWheel;	// External class reference
			class HitRF2Wheel;	// External class reference
		};
	};
	
	class VWGolf : Car {};
	
	class CVPI_Patrol : VWGolf {
		hiddenSelections[] = {"red_strobe_1", "red_strobe_2", "white_strobe", "right", "left", "trunklights_right", "trunklights_left", "endflash", "arrow1", "arrow2", "arrow3", "arrow4", "endflash2", "blue_flasher", "blue2_flasher", "red_flasher", "red2_flasher", "flash_1", "flash_2", "trunklights2_right", "trunklights2_left", "led1", "led2", "bulb1", "bulb2", "bulb3", "bulb4", "bulb5", "bulb6", "bulb7", "bulb8", "bulb9", "bulb10", "bulb11", "bulb12", "strobered", "strobeblue", "tail_flashers", "front_lights"};
		extCameraPosition[] = {0, 0.5, -8};
		wheelCircumference = 1.0;
		terraincoef = 1;
		vehicleClass = "American_Law_Enforcement";
		armor = 6;
		maxSpeed = 170;	// max speed on level road, km/h
		model = "\American_Law_Enforcement\CVPI_Highway_Patrol.p3d";
		DisplayName = "CVPI CHP";
		side = TCivilian;
		fuelCapacity = 80;
		unitInfoType = "UnitInfoShip";
		
		class HitPoints : HitPoints {
			class HitBody {
				armor = 1;
				material = -1;
				name = "body_hit";
				visual = "body";
				passThrough = true;
			};
			
			class HitLFWheel {
				armor = 0.3;
				material = -1;
				name = "left_front_wheel_hit";
				visual = "left_front_wheel";
				passThrough = false;
			};
			
			class HitLBWheel {
				armor = 0.3;
				material = -1;
				name = "left_back_wheel_hit";
				visual = "left_back_wheel";
				passThrough = false;
			};
			
			class HitRFWheel {
				armor = 0.3;
				material = -1;
				name = "right_front_wheel_hit";
				visual = "right_front_wheel";
				passThrough = false;
			};
			
			class HitRBWheel {
				armor = 0.3;
				material = -1;
				name = "right_back_wheel_hit";
				visual = "right_back_wheel";
				passThrough = false;
			};
			
			class HitGlass1 {
				armor = 0.05;
				material = -1;
				name = "sklo predni L";
				visual = "sklo predni L";
				passThrough = false;
			};
			
			class HitGlass2 : HitGlass1 {
				name = "sklo predni P";
				visual = "sklo predni P";
			};
		};
		dammageHalf[] = {"American_Law_Enforcement\Data\sklo.paa", "American_Law_Enforcement\Data\sklo_d.paa"};
		dammageFull[] = {"American_Law_Enforcement\Data\sklo.paa", "American_Law_Enforcement\Data\sklo_d.paa"};
		soundEngineOnInt[] = {"American_Law_Enforcement\Sounds\engine-start", 20.0, 1.0};
		soundEngineOnExt[] = {"American_Law_Enforcement\Sounds\engine-start", 20.0, 1.0, 250};
		soundEngineOffInt[] = {"ca\sounds\vehicles\Wheeled\GOLF\int\int-golf-stop-1", 0.562341, 1.0};
		soundEngineOffExt[] = {"ca\sounds\vehicles\Wheeled\GOLF\ext\ext-golf-stop-1", 0.562341, 1.0, 250};
		
		class Library {
			libTextDesc = "American Law Enforcement";
		};
		
		class Damage {
			tex[] = {};
			mat[] = {};
		};
		destrType = "DestructWreck";
		
		class AnimationSources {
			class door_r1 {
				animPeriod = 1;
			};
			
			class door_l1 : door_r1 {};
			
			class door_l2 : door_r1 {};
			
			class door_r2 : door_r1 {};
			
			class kapota : door_r1 {};
			
			class kufr : door_r1 {};
			
			class patolamp {
				animPeriod = 0.1;
			};
			
			class slow_func {
				source = "user";
				animPeriod = 0.5;
				initPhase = 0;
			};
		};
		
		class UserActions {
			class LightbarOn {
				displayName = "Lightbar On";
				position = "police_lights_axis";
				radius = 5;
				onlyforplayer = 1;
				condition = "this animationPhase ""policeLightbar"" < 0.5 && driver this == player";
				statement = "this animate [""policeLightbar"",1]";
			};
			
			class LightbarOff {
				displayName = "Lightbar Off";
				position = "police_lights_axis";
				radius = 5;
				onlyforplayer = 1;
				condition = "this animationPhase ""policeLightbar"" >= 0.5 && driver this == player";
				statement = "this animate [""policeLightbar"",0]";
			};
			
			class SirensOn {
				displayName = "Siren On";
				position = "police_sirens_axis";
				radius = 5;
				onlyforplayer = 1;
				condition = "this animationPhase ""policeSirens"" < 0.5 && driver this == player";
				statement = "this animate [""policeSirens"",1]";
			};
			
			class SirensOff {
				displayName = "Siren Off";
				position = "police_sirens_axis";
				radius = 5;
				onlyforplayer = 1;
				condition = "this animationPhase ""policeSirens"" >= 0.5 && driver this == player";
				statement = "this animate [""policeSirens"",0]";
			};
		};
		
		class Light {
			ambient[] = {0.3, 0.15, 0.0, 1.0};
			brightness = 110.0;
			color[] = {1.0, 0.5, 0.0, 1.0};
			position = "ohniste";
			shape = "koulesvetlo";
			size = 0.3;
		};
		
		class EventHandlers {
			init = "handel = [_this select 0,""Main""] execVM ""\American_Law_Enforcement\scripts\police_lightbar.sqf""; handel = [_this select 0,""tail_head""] execVM ""\American_Law_Enforcement\scripts\police_lightbar.sqf""; handel = [_this select 0,""Liberty""] execVM ""\American_Law_Enforcement\scripts\police_lightbar.sqf""; handel = [_this select 0,""Avengers""] execVM ""\American_Law_Enforcement\scripts\police_lightbar.sqf""; handel = [_this select 0,""tail_flash""] execVM ""\American_Law_Enforcement\scripts\police_lightbar.sqf""; handel = [_this select 0,""Vector""] execVM ""\American_Law_Enforcement\scripts\police_lightbar.sqf""; handel = [_this select 0,""Federals""] execVM ""\American_Law_Enforcement\scripts\police_lightbar.sqf""; handel = [_this select 0,""directional""] execVM ""\American_Law_Enforcement\scripts\police_lightbar.sqf""; handel = [_this select 0] execVM ""\American_Law_Enforcement\scripts\police_sirens.sqf""; handle = [_this select 0] execVM ""\American_Law_Enforcement\scripts\police_radio.sqf""";
		};
		
		class SoundEvents {
			class AccelerationIn {
				sound[] = {"American_Law_Enforcement\Sounds\engine-acc", db-1, 1.0};
				limit = 0.15;
				expression = "engineOn*(1-camPos)*2*gmeterZ*((speed factor[1.5, 5]) min (speed factor[5, 1.5]))";
			};
			
			class AccelerationOut {
				sound[] = {"American_Law_Enforcement\Sounds\engine-acc", db-5, 1.0, 250};
				limit = 0.15;
				expression = "engineOn*camPos*2*gmeterZ*((speed factor[1.5, 5]) min (speed factor[5, 1.5]))";
			};
		};
		
		class Sounds {
			class Engine {
				sound[] = {"American_Law_Enforcement\Sounds\engine-low", db-8, 1.0, 300};
				frequency = "(randomizer*0.05+1.25)*rpm";
				volume = "camPos*engineOn*((rpm factor[0.25, 0.4]) min (rpm factor[0.6, 0.45]))";
			};
			
			class EngineHighOut {
				sound[] = {"American_Law_Enforcement\Sounds\engine-high", db-8, 0.8, 450};
				frequency = "(randomizer*0.05+1.1)*rpm";
				volume = "camPos*engineOn*(rpm factor[0.5, 0.9])";
			};
			
			class IdleOut {
				sound[] = {"American_Law_Enforcement\Sounds\engine-idle", db-10, 1.0, 100};
				frequency = "1";
				volume = "engineOn*camPos*(rpm factor[0.4, 0])";
			};
			
			class TiresRockOut {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\ext\ext-tires-rock2", db-25, 1.0, 40};
				frequency = "1";
				volume = "camPos*rock*(speed factor[4, 20])";
			};
			
			class TiresSandOut {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\ext\ext-tires-sand2", db-25, 1.0, 40};
				frequency = "1";
				volume = "camPos*sand*(speed factor[4, 20])";
			};
			
			class TiresGrassOut {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\ext\ext-tires-grass3", db-25, 1.0, 40};
				frequency = "1";
				volume = "camPos*grass*(speed factor[4, 20])";
			};
			
			class TiresMudOut {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\ext\ext-tires-mud2", db-25, 1.0, 40};
				frequency = "1";
				volume = "camPos*mud*(speed factor[4, 20])";
			};
			
			class TiresGravelOut {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\ext\ext-tires-gravel2", db-25, 1.0, 40};
				frequency = "1";
				volume = "camPos*gravel*(speed factor[4, 20])";
			};
			
			class TiresAsphaltOut {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\ext\ext-tires-asphalt3", db-25, 1.0, 40};
				frequency = "1";
				volume = "camPos*asphalt*(speed factor[4, 20])";
			};
			
			class NoiseOut {
				sound[] = {"ca\sounds\Vehicles\Wheeled\Noises\ext\noise2", db-25, 1.0, 40};
				frequency = "1";
				volume = "camPos*(damper0 max 0.036)*(speed factor[0, 8])";
			};
			
			class EngineLowIn {
				sound[] = {"American_Law_Enforcement\Sounds\engine-low", db-3, 1.0};
				frequency = "(randomizer*0.05+1.3)*rpm";
				volume = "(1-camPos)*engineOn*((rpm factor[0.3, 0.5]) min (rpm factor[0.7, 0.52]))";
			};
			
			class EngineHighIn {
				sound[] = {"American_Law_Enforcement\Sounds\engine-high", db-3, 0.95};
				frequency = "(randomizer*0.05+1.2)*rpm";
				volume = "(1-camPos)*engineOn*(rpm factor[0.6, 1.0])";
			};
			
			class IdleIn {
				sound[] = {"American_Law_Enforcement\Sounds\engine-idle", db-5, 1.0};
				frequency = "1";
				volume = "(1-camPos)*engineOn*(rpm factor[0.4, 0])";
			};
			
			class TiresRockIn {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\int\int-tires-rock2", 0.0707946, 1.0};
				frequency = "1";
				volume = "(1-camPos)*rock*(speed factor[2, 20])";
			};
			
			class TiresSandIn {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\int\int-tires-sand2", 0.0707946, 1.0};
				frequency = "1";
				volume = "(1-camPos)*sand*(speed factor[2, 20])";
			};
			
			class TiresGrassIn {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\int\int-tires-grass3", 0.0707946, 1.0};
				frequency = "1";
				volume = "(1-camPos)*grass*(speed factor[2, 20])";
			};
			
			class TiresMudIn {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\int\int-tires-mud2", 0.0707946, 1.0};
				frequency = "1";
				volume = "(1-camPos)*mud*(speed factor[2, 20])";
			};
			
			class TiresGravelIn {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\int\int-tires-gravel2", 0.0707946, 1.0};
				frequency = "1";
				volume = "(1-camPos)*gravel*(speed factor[2, 20])";
			};
			
			class TiresAsphaltIn {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\int\int-tires-asphalt3", db-25, 1.0};
				frequency = "1";
				volume = "(1-camPos)*asphalt*(speed factor[2, 20])";
			};
			
			class NoiseIn {
				sound[] = {"ca\sounds\Vehicles\Wheeled\Noises\int\int-noise2", 0.1, 1.0};
				frequency = "1";
				volume = "(damper0 max 0.03)*(speed factor[0, 8])*(1-camPos)";
			};
			
			class Movement {
				sound = "soundEnviron";
				frequency = "1";
				volume = "0";
			};
		};
	};
	
	class CVPI_Trooper_Patrol : CVPI_Patrol {
		model = "\American_Law_Enforcement\CVPI_Trooper_Patrol.p3d";
		DisplayName = "CVPI Texas State Trooper";
	};
	
	class CVPI_TrooperSL_Patrol : CVPI_Patrol {
		model = "\American_Law_Enforcement\CVPI_TrooperSL_Patrol.p3d";
		DisplayName = "CVPI Trooper Slicktop";
	};
	
	class CVPI_NYPD_Patrol : CVPI_Patrol {
		model = "\American_Law_Enforcement\CVPI_NYPD_Patrol.p3d";
		DisplayName = "CVPI NYPD Patrol Car";
	};
	
	class CVPI_HighwaySL_Patrol : CVPI_Patrol {
		model = "\American_Law_Enforcement\CVPI_HighwaySL_Patrol.p3d";
		DisplayName = "CVPI Highway Slicktop";
	};
	
	class CVPI_UnmarkedB_Patrol : CVPI_Patrol {
		model = "\American_Law_Enforcement\CVPI_UnmarkedB_Patrol.p3d";
		DisplayName = "CVPI Unmarked Black";
	};
	
	class CVPI_UnmarkedG_Patrol : CVPI_Patrol {
		model = "\American_Law_Enforcement\CVPI_UnmarkedG_Patrol.p3d";
		DisplayName = "CVPI Unmarked Dark Grey";
	};
	
	class CVPI_LAPD_Patrol : CVPI_Patrol {
		model = "\American_Law_Enforcement\CVPI_LAPD_Patrol.p3d";
		DisplayName = "CVPI LAPD Patrol Car";
	};
	
	class CVPI_UnmarkedW_Patrol : CVPI_Patrol {
		model = "\American_Law_Enforcement\CVPI_UnmarkedW_Patrol.p3d";
		DisplayName = "CVPI Unmarked White";
	};
	
	class CVPI_LAPDSL_Patrol : CVPI_Patrol {
		model = "\American_Law_Enforcement\CVPI_LAPDSL_Patrol.p3d";
		DisplayName = "CVPI LAPD Slicktop Car";
	};
	
	class CVPI_NYPDSL_Patrol : CVPI_Patrol {
		model = "\American_Law_Enforcement\CVPI_NYPDSL_Patrol.p3d";
		DisplayName = "CVPI NYPD Slicktop Car";
	};
};
