// config.bin - 12:55:37 06/17/17, generated in 0.05 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define true	1
#define false	0

#include "CfgPatches.hpp"
#include "CfgSounds.hpp"
#include "CfgVehicleClasses.hpp"
#include "CfgVehicles.hpp"
