// Generated by unRap v1.06 by Kegetys

class CfgAmmo {
	class Default;	// External class reference
	class BulletCore;	// External class reference
	class BulletBase;	// External class reference
	class B_762x51_Ball;	// External class reference
	
	class RH_B_762x51_SD_hk417 : B_762x51_Ball {
		hit = 11;
		typicalSpeed = 320;
		airFriction = -0.0007;
		cartridge = "FxCartridge_762";
		visibleFire = 0.07;	// how much is visible when this weapon is fired
		audibleFire = 0.07;
		visibleFireTime = 2;	// how long is it visible
	};
};
