// Generated by unRap v1.06 by Kegetys

class CfgMagazines {
	class Default;	// External class reference
	class CA_Magazine;	// External class reference
	
	class RH_20Rnd_762x51_hk417 : CA_Magazine {
		scope = public;
		displayName = $STR_DN_20RND_STANAG;
		picture = "\RH_hk416\inv\m_hk417.paa";
		ammo = "B_762x51_noTracer";
		count = 20;
		initSpeed = 789;
		descriptionShort = "20Rnd 762x51 Hk417 Mag ";
	};
	
	class RH_20Rnd_762x51_SD_hk417 : CA_Magazine {
		scope = public;
		displayName = "20Rnd. STANAG SD";
		picture = "\RH_hk416\inv\m_hk417.paa";
		descriptionShort = "20Rnd 762x51 SD Hk417 Mag ";
		ammo = "RH_B_762x51_SD_hk417";
		count = 20;
		initSpeed = 750;
	};
};
