// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class RH_hk416_cfg {
		units[] = {"RHhk416ammobox"};
		weapons[] = {"RH_hk416", "RH_hk416aim", "RH_hk416acog", "RH_hk416eotech", "RH_hk416sd", "RH_hk416sdaim", "RH_hk416sdeotech", "RH_hk416gl", "RH_hk416glaim", "RH_hk416glacog", "RH_hk416glaeotech", "RH_hk416sdgl", "RH_hk416sdglaim", "RH_hk416sdgleotech", "RH_hk416s", "RH_hk416saim", "RH_hk416seotech", "RH_hk416sacog", "RH_hk416sgl", "RH_hk416sglaim", "RH_hk416sgleotech", "RH_hk416sglacog", "RH_ctar21", "RH_ctar21glacog", "RH_ctar21m", "RH_ctar21mgl", "RH_star21", "RH_hk417", "RH_hk417aim", "RH_hk417acog", "RH_hk417eotech", "RH_hk417sp", "RH_hk417sd", "RH_hk417sdaim", "RH_hk417sdacog", "RH_hk417sdeotech", "RH_hk417sdsp", "RH_hk417s", "RH_hk417saim", "RH_hk417sacog", "RH_hk417seotech", "RH_hk417sgl", "RH_hk417sglaim", "RH_hk417sglacog", "RH_hk417sgleotech", "RH_acr", "RH_acracog", "RH_acraim", "RH_acreotech", "RH_acrgl", "RH_acrglacog", "RH_acrglaim", "RH_acrgleotech", "RH_acrb", "RH_acrbacog", "RH_acrbaim", "RH_acrbeotech", "RH_acrbgl", "RH_acrbglacog", "RH_acrbglaim", "RH_acrbgleotech", "RH_mas", "RH_masacog", "RH_masaim", "RH_maseotech", "RH_masb", "RH_masbacog", "RH_masbaim", "RH_masbeotech", "RH_massd", "RH_massdacog", "RH_massdaim", "RH_massdeotech", "RH_masbsd", "RH_masbsdacog", "RH_masbsdaim", "RH_masbsdeotech"};
		requiredVersion = 1.02;
		requiredAddons[] = {"CAweapons"};
	};
};
