// Generated by unRap v1.06 by Kegetys

class cfgVehicles {
	class ReammoBox;	// External class reference
	
	class RHhk416ammobox : ReammoBox {
		scope = public;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		model = "\ca\weapons\AmmoBoxes\USBasicWeapons.p3d";
		displayName = "RH Hk416 weapons box";
		
		class TransportMagazines {
			class _xx_30Rnd_556x45_Stanag {
				magazine = "30Rnd_556x45_Stanag";
				count = 200;
			};
			
			class _xx_30Rnd_556x45_StanagSD {
				magazine = "30Rnd_556x45_StanagSD";
				count = 200;
			};
			
			class _xx_RH_20Rnd_762x51_hk417 {
				magazine = "RH_20Rnd_762x51_hk417";
				count = 200;
			};
			
			class _xx_RH_20Rnd_762x51_SD_hk417 {
				magazine = "RH_20Rnd_762x51_SD_hk417";
				count = 200;
			};
			
			class _xx_20Rnd_762x51_DMR {
				magazine = "20Rnd_762x51_DMR";
				count = 200;
			};
			
			class _xx_1rnd_HE_M203 {
				magazine = "1rnd_HE_M203";
				count = 30;
			};
			
			class _xx_HandGrenade_West {
				magazine = "HandGrenade_West";
				count = 50;
			};
			
			class _xx_FlareWhite_M203 {
				magazine = "FlareWhite_M203";
				count = 6;
			};
			
			class _xx_FlareRed_M203 {
				magazine = "FlareRed_M203";
				count = 6;
			};
			
			class _xx_FlareGreen_M203 {
				magazine = "FlareGreen_M203";
				count = 6;
			};
			
			class _xx_FlareYellow_M203 {
				magazine = "FlareYellow_M203";
				count = 6;
			};
		};
		
		class TransportWeapons {
			class _xx_RH_hk416 {
				weapon = "RH_hk416";
				count = 6;
			};
			
			class _xx_RH_hk416s {
				weapon = "RH_hk416s";
				count = 6;
			};
			
			class _xx_RH_hk416saim {
				weapon = "RH_hk416saim";
				count = 6;
			};
			
			class _xx_RH_hk416seotech {
				weapon = "RH_hk416seotech";
				count = 6;
			};
			
			class _xx_RH_hk416sacog {
				weapon = "RH_hk416sacog";
				count = 6;
			};
			
			class _xx_RH_hk416GL {
				weapon = "RH_hk416GL";
				count = 6;
			};
			
			class _xx_RH_hk416GLACOG {
				weapon = "RH_hk416GLACOG";
				count = 6;
			};
			
			class _xx_RH_hk416GLAim {
				weapon = "RH_hk416GLaim";
				count = 6;
			};
			
			class _xx_RH_hk416GLeotech {
				weapon = "RH_hk416GLeotech";
				count = 6;
			};
			
			class _xx_RH_hk416sGL {
				weapon = "RH_hk416sGL";
				count = 6;
			};
			
			class _xx_RH_hk416sGLACOG {
				weapon = "RH_hk416sGLACOG";
				count = 6;
			};
			
			class _xx_RH_hk416sGLAim {
				weapon = "RH_hk416sGLaim";
				count = 6;
			};
			
			class _xx_RH_hk416sGLeotech {
				weapon = "RH_hk416sGLeotech";
				count = 6;
			};
			
			class _xx_RH_hk416SD {
				weapon = "RH_hk416SD";
				count = 6;
			};
			
			class _xx_RH_hk416SDAIM {
				weapon = "RH_hk416SDAIM";
				count = 6;
			};
			
			class _xx_RH_hk416SDeotech {
				weapon = "RH_hk416SDeotech";
				count = 6;
			};
			
			class _xx_RH_hk416SDGL {
				weapon = "RH_hk416SDGL";
				count = 6;
			};
			
			class _xx_RH_hk416SDGLAIM {
				weapon = "RH_hk416SDGLAIM";
				count = 6;
			};
			
			class _xx_RH_hk416SDGLeotech {
				weapon = "RH_hk416SDGLeotech";
				count = 6;
			};
			
			class _xx_RH_hk416AIM {
				weapon = "RH_hk416AIM";
				count = 6;
			};
			
			class _xx_RH_hk416ACOG {
				weapon = "RH_hk416ACOG";
				count = 6;
			};
			
			class _xx_RH_hk416eotech {
				weapon = "RH_hk416eotech";
				count = 6;
			};
			
			class _xx_RH_ctar21 {
				weapon = "RH_ctar21";
				count = 6;
			};
			
			class _xx_RH_ctar21glacog {
				weapon = "RH_ctar21glacog";
				count = 6;
			};
			
			class _xx_RH_ctar21m {
				weapon = "RH_ctar21m";
				count = 6;
			};
			
			class _xx_RH_ctar21mgl {
				weapon = "RH_ctar21mgl";
				count = 6;
			};
			
			class _xx_RH_star21 {
				weapon = "RH_star21";
				count = 6;
			};
			
			class _xx_RH_hk417 {
				weapon = "RH_hk417";
				count = 6;
			};
			
			class _xx_RH_hk417s {
				weapon = "RH_hk417s";
				count = 6;
			};
			
			class _xx_RH_hk417saim {
				weapon = "RH_hk417saim";
				count = 6;
			};
			
			class _xx_RH_hk417seotech {
				weapon = "RH_hk417seotech";
				count = 6;
			};
			
			class _xx_RH_hk417sacog {
				weapon = "RH_hk417sacog";
				count = 6;
			};
			
			class _xx_RH_hk417sGL {
				weapon = "RH_hk417sGL";
				count = 6;
			};
			
			class _xx_RH_hk417sGLACOG {
				weapon = "RH_hk417sGLACOG";
				count = 6;
			};
			
			class _xx_RH_hk417sGLAim {
				weapon = "RH_hk417sGLaim";
				count = 6;
			};
			
			class _xx_RH_hk417sGLeotech {
				weapon = "RH_hk417sGLeotech";
				count = 6;
			};
			
			class _xx_RH_hk417SD {
				weapon = "RH_hk417SD";
				count = 6;
			};
			
			class _xx_RH_hk417SDAIM {
				weapon = "RH_hk417SDAIM";
				count = 6;
			};
			
			class _xx_RH_hk417SDeotech {
				weapon = "RH_hk417SDeotech";
				count = 6;
			};
			
			class _xx_RH_hk417sdsp {
				weapon = "RH_hk417sdsp";
				count = 6;
			};
			
			class _xx_RH_hk417sp {
				weapon = "RH_hk417sp";
				count = 6;
			};
			
			class _xx_RH_hk417sdACOG {
				weapon = "RH_hk417sdACOG";
				count = 6;
			};
			
			class _xx_RH_hk417AIM {
				weapon = "RH_hk417AIM";
				count = 6;
			};
			
			class _xx_RH_hk417ACOG {
				weapon = "RH_hk417ACOG";
				count = 6;
			};
			
			class _xx_RH_hk417eotech {
				weapon = "RH_hk417eotech";
				count = 6;
			};
			
			class _xx_RH_mas {
				weapon = "RH_mas";
				count = 6;
			};
			
			class _xx_RH_masSD {
				weapon = "RH_masSD";
				count = 6;
			};
			
			class _xx_RH_masSDAIM {
				weapon = "RH_masSDAIM";
				count = 6;
			};
			
			class _xx_RH_masSDeotech {
				weapon = "RH_masSDeotech";
				count = 6;
			};
			
			class _xx_RH_massdACOG {
				weapon = "RH_massdACOG";
				count = 6;
			};
			
			class _xx_RH_masAIM {
				weapon = "RH_masAIM";
				count = 6;
			};
			
			class _xx_RH_masACOG {
				weapon = "RH_masACOG";
				count = 6;
			};
			
			class _xx_RH_maseotech {
				weapon = "RH_maseotech";
				count = 6;
			};
			
			class _xx_RH_masb {
				weapon = "RH_masb";
				count = 6;
			};
			
			class _xx_RH_masbSD {
				weapon = "RH_masbSD";
				count = 6;
			};
			
			class _xx_RH_masbSDAIM {
				weapon = "RH_masbSDAIM";
				count = 6;
			};
			
			class _xx_RH_masbSDeotech {
				weapon = "RH_masbSDeotech";
				count = 6;
			};
			
			class _xx_RH_masbsdACOG {
				weapon = "RH_masbsdACOG";
				count = 6;
			};
			
			class _xx_RH_masbAIM {
				weapon = "RH_masbAIM";
				count = 6;
			};
			
			class _xx_RH_masbACOG {
				weapon = "RH_masbACOG";
				count = 6;
			};
			
			class _xx_RH_masbeotech {
				weapon = "RH_masbeotech";
				count = 6;
			};
			
			class _xx_RH_acr {
				weapon = "RH_acr";
				count = 6;
			};
			
			class _xx_RH_acrAIM {
				weapon = "RH_acrAIM";
				count = 6;
			};
			
			class _xx_RH_acrACOG {
				weapon = "RH_acrACOG";
				count = 6;
			};
			
			class _xx_RH_acreotech {
				weapon = "RH_acreotech";
				count = 6;
			};
			
			class _xx_RH_acrgl {
				weapon = "RH_acrgl";
				count = 6;
			};
			
			class _xx_RH_acrglAIM {
				weapon = "RH_acrglAIM";
				count = 6;
			};
			
			class _xx_RH_acrglACOG {
				weapon = "RH_acrglACOG";
				count = 6;
			};
			
			class _xx_RH_acrgleotech {
				weapon = "RH_acrgleotech";
				count = 6;
			};
			
			class _xx_RH_acrb {
				weapon = "RH_acrb";
				count = 6;
			};
			
			class _xx_RH_acrbAIM {
				weapon = "RH_acrbAIM";
				count = 6;
			};
			
			class _xx_RH_acrbACOG {
				weapon = "RH_acrbACOG";
				count = 6;
			};
			
			class _xx_RH_acrbeotech {
				weapon = "RH_acrbeotech";
				count = 6;
			};
			
			class _xx_RH_acrbgl {
				weapon = "RH_acrbgl";
				count = 6;
			};
			
			class _xx_RH_acrbglAIM {
				weapon = "RH_acrbglAIM";
				count = 6;
			};
			
			class _xx_RH_acrbglACOG {
				weapon = "RH_acrbglACOG";
				count = 6;
			};
			
			class _xx_RH_acrbgleotech {
				weapon = "RH_acrbgleotech";
				count = 6;
			};
		};
	};
};
