// Generated by unRap v1.06 by Kegetys

class cfgWeapons {
	class Default;	// External class reference
	class PistolCore;	// External class reference
	class Pistol;	// External class reference
	class RifleCore;	// External class reference
	class MGunCore;	// External class reference
	class LauncherCore;	// External class reference
	class GrenadeCore;	// External class reference
	class CannonCore;	// External class reference
	class Launcher;	// External class reference
	
	class GrenadeLauncher : Default {};
	
	class RocketPods : LauncherCore {};
	
	class MissileLauncher : LauncherCore {};
	
	class MGun : MGunCore {};
	
	class Rifle : RifleCore {};
	
	class M16_base : Rifle {
		class Single : Mode_SemiAuto {};
		
		class Burst : Mode_Burst {};
		
		class FullAuto : Mode_FullAuto {};
	};
	
	class M4A1 : M16_base {};
	
	class M4SPR : M4A1 {};
	
	class M16A2 : M16_base {};
	
	class RH_hk416 : M4A1 {
		scope = public;
		model = "\RH_hk416\RH_hk416.p3d";
		picture = "\RH_hk416\inv\hk416.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		optics = true;
		opticsDisablePeripherialVision = true;
		displayName = HK416;
		handAnim[] = {"OFP2_ManSkeleton", "\RH_hk416\Anim\Hk416_anim.rtm"};
		reloadMagazineSound[] = {"\RH_hk416\sound\Hk416_Reload.wss", 0.056234, 1, 20};
		magazines[] = {"30Rnd_556x45_Stanag", "30Rnd_556x45_StanagSD", "20Rnd_556x45_Stanag", "30Rnd_556x45_G36", "100Rnd_556x45_BetaCMag", "30Rnd_556x45_G36SD"};
		modes[] = {"Single", "FullAuto"};
		
		class Single : Single {
			begin1[] = {"\RH_hk416\sound\hk416.wss", 1.77828, 1, 1000};
			soundBegin[] = {"begin1", 1};
			reloadtime = 0.071;
			dispersion = 0.0025;
			recoil = "RH_hk416Recoil";
			recoilProne = "RH_assaultRiflesBasePronehk";
			minRange = 2;
			minRangeProbab = 0.1;
			midRange = 250;
			midRangeProbab = 0.7;
			maxRange = 400;
			maxRangeProbab = 0.05;
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\RH_hk416\sound\hk416.wss", 1.77828, 1, 1000};
			soundBegin[] = {"begin1", 1};
			reloadtime = 0.071;
			recoil = "RH_hk416Recoil";
			recoilProne = "RH_assaultRiflesBasePronehk";
			dispersion = 0.0025;
			minRange = 2;
			minRangeProbab = 0.1;
			midRange = 60;
			midRangeProbab = 0.7;
			maxRange = 90;
			maxRangeProbab = 0.05;
		};
	};
	
	class RH_hk416s : RH_hk416 {
		displayName = "Hk416 Cqb";
		model = "\RH_hk416\RH_hk416s.p3d";
		picture = "\RH_hk416\inv\hk416s.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\RH_hk416\Anim\hk416cqb_anim.rtm"};
	};
	
	class RH_hk416saim : RH_hk416s {
		displayName = "Hk416 Cqb Aimpoint";
		model = "\RH_hk416\RH_hk416saim.p3d";
		picture = "\RH_hk416\inv\hk416saim.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_hk416seotech : RH_hk416s {
		displayName = "Hk416 Cqb Eotech";
		model = "\RH_hk416\RH_hk416seotech.p3d";
		picture = "\RH_hk416\inv\hk416seotech.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_hk416sacog : RH_hk416s {
		displayName = "Hk416 Cqb Acog";
		model = "\RH_hk416\RH_hk416sacog.p3d";
		picture = "\RH_hk416\inv\hk416sacog.paa";
		modelOptics = "\RH_hk416\NWD_acog_ta31f.p3d";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 189;
				distanceZoomMax = 189;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_hk416sd : RH_hk416 {
		fireLightDuration = 0.0;
		fireLightIntensity = 0.0;
		displayName = "Hk416 SD";
		model = "\RH_hk416\RH_hk416sd.p3d";
		picture = "\RH_hk416\inv\hk416sd.paa";
		opticsDisablePeripherialVision = true;
		magazines[] = {"30Rnd_556x45_StanagSD", "30Rnd_556x45_G36SD", "30Rnd_556x45_Stanag", "20Rnd_556x45_Stanag"};
		modes[] = {"Single", "FullAuto"};
		
		class Single : Single {
			begin1[] = {"\RH_hk416\sound\hk416sd.wss", 1.0, 1, 300};
			soundBegin[] = {"begin1", 1};
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\RH_hk416\sound\hk416sd.wss", 1.0, 1, 300};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class RH_hk416sdaim : RH_hk416sd {
		displayName = "Hk416 SD Aimpoint";
		model = "\RH_hk416\RH_hk416sdaim.p3d";
		picture = "\RH_hk416\inv\hk416sdaim.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_hk416sdeotech : RH_hk416sd {
		displayName = "Hk416 SD Eotech";
		model = "\RH_hk416\RH_hk416sdeotech.p3d";
		picture = "\RH_hk416\inv\hk416sdeotech.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_hk416aim : RH_hk416 {
		displayName = "Hk416 Aimpoint";
		model = "\RH_hk416\RH_hk416aim.p3d";
		picture = "\RH_hk416\inv\hk416aim.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_hk416eotech : RH_hk416 {
		displayName = "Hk416 Eotech";
		model = "\RH_hk416\RH_hk416eotech.p3d";
		picture = "\RH_hk416\inv\hk416eotech.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_hk416acog : RH_hk416 {
		displayName = "Hk416 Acog";
		model = "\RH_hk416\RH_hk416acog.p3d";
		picture = "\RH_hk416\inv\hk416acog.paa";
		modelOptics = "\RH_hk416\NWD_acog_ta31f.p3d";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 189;
				distanceZoomMax = 189;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_hk416gl : RH_hk416 {
		displayName = "Hk416 AG36";
		model = "\RH_hk416\RH_hk416gl.p3d";
		picture = "\RH_hk416\inv\hk416gl.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk416Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk416Muzzle : RH_hk416 {};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = AG36;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_hk416glaim : RH_hk416 {
		displayName = "HK416 Aimpoint AG36";
		model = "\RH_hk416\RH_hk416glaim.p3d";
		picture = "\RH_hk416\inv\hk416glaim.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk416Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk416Muzzle : RH_hk416 {
			opticsDisablePeripherialVision = true;
			distanceZoomMin = 100;
			distanceZoomMax = 100;
		};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = AG36;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_hk416gleotech : RH_hk416 {
		displayName = "Hk416 Eotech AG36";
		model = "\RH_hk416\RH_hk416gleotech.p3d";
		picture = "\RH_hk416\inv\Hk416gleotech.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk416Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk416Muzzle : RH_hk416 {
			opticsDisablePeripherialVision = true;
			distanceZoomMin = 100;
			distanceZoomMax = 100;
		};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = AG36;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_hk416glacog : RH_hk416 {
		displayName = "Hk416 Acog AG36";
		model = "\RH_hk416\RH_hk416glacog.p3d";
		picture = "\RH_hk416\inv\hk416glacog.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk416Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk416Muzzle : RH_hk416 {
			modelOptics = "\RH_hk416\NWD_acog_ta31f";
			
			class OpticsModes {
				class ACOG {
					opticsID = 1;
					useModelOptics = 1;
					opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
					opticsZoomMin = 0.071945;
					opticsZoomMax = 0.071945;
					opticsZoomInit = 0.071945;
					memoryPointCamera = "opticView";
					visionMode[] = {"Normal"};
					opticsFlare = "true";
					opticsDisablePeripherialVision = "true";
					distanceZoomMin = 189;
					distanceZoomMax = 189;
					cameraDir = "";
				};
				
				class Kolimator : ACOG {
					opticsID = 2;
					useModelOptics = 0;
					opticsFlare = "false";
					opticsDisablePeripherialVision = "false";
					opticsZoomMin = 0.25;
					opticsZoomMax = 1.1;
					opticsZoomInit = 0.5;
					memoryPointCamera = "eye";
					visionMode[] = {};
				};
			};
		};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = AG36;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_hk416sgl : RH_hk416s {
		displayName = "Hk416 Cqb M203";
		model = "\RH_hk416\RH_hk416sgl.p3d";
		picture = "\RH_hk416\inv\hk416sgl.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk416Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk416Muzzle : RH_hk416s {};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = M203;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_hk416sglaim : RH_hk416s {
		displayName = "HK416 Cqb Aimpoint M203";
		model = "\RH_hk416\RH_hk416sglaim.p3d";
		picture = "\RH_hk416\inv\hk416sglaim.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk416Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk416Muzzle : RH_hk416s {
			opticsDisablePeripherialVision = true;
			distanceZoomMin = 100;
			distanceZoomMax = 100;
		};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = M203;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_hk416sgleotech : RH_hk416s {
		displayName = "Hk416 Cqb Eotech M203";
		model = "\RH_hk416\RH_hk416sgleotech.p3d";
		picture = "\RH_hk416\inv\Hk416sgleotech.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk416Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk416Muzzle : RH_hk416s {
			opticsDisablePeripherialVision = true;
			distanceZoomMin = 100;
			distanceZoomMax = 100;
		};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = M203;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_hk416sglacog : RH_hk416s {
		displayName = "Hk416 Cqb Acog M203";
		model = "\RH_hk416\RH_hk416sglacog.p3d";
		picture = "\RH_hk416\inv\hk416sglacog.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk416Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk416Muzzle : RH_hk416s {
			modelOptics = "\RH_hk416\NWD_acog_ta31f";
			
			class OpticsModes {
				class ACOG {
					opticsID = 1;
					useModelOptics = 1;
					opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
					opticsZoomMin = 0.071945;
					opticsZoomMax = 0.071945;
					opticsZoomInit = 0.071945;
					memoryPointCamera = "opticView";
					visionMode[] = {"Normal"};
					opticsFlare = "true";
					opticsDisablePeripherialVision = "true";
					distanceZoomMin = 189;
					distanceZoomMax = 189;
					cameraDir = "";
				};
				
				class Kolimator : ACOG {
					opticsID = 2;
					useModelOptics = 0;
					opticsFlare = "false";
					opticsDisablePeripherialVision = "false";
					opticsZoomMin = 0.25;
					opticsZoomMax = 1.1;
					opticsZoomInit = 0.5;
					memoryPointCamera = "eye";
					visionMode[] = {};
				};
			};
		};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = M203;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_hk416sdgl : RH_hk416sd {
		displayName = "Hk416 SD AG36";
		model = "\RH_hk416\RH_hk416sdgl.p3d";
		picture = "\RH_hk416\inv\hk416sdgl.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk416Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk416Muzzle : RH_hk416sd {};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = AG36;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_hk416sdglaim : RH_hk416sd {
		displayName = "HK416 SD Aimpoint AG36";
		model = "\RH_hk416\RH_hk416sdglaim.p3d";
		picture = "\RH_hk416\inv\hk416sdglaim.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk416Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk416Muzzle : RH_hk416sd {
			opticsDisablePeripherialVision = true;
			distanceZoomMin = 100;
			distanceZoomMax = 100;
		};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = AG36;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_hk416sdgleotech : RH_hk416sd {
		displayName = "Hk416 SD Eotech AG36";
		model = "\RH_hk416\RH_hk416sdgleotech.p3d";
		picture = "\RH_hk416\inv\hk416sdgleotech.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk416Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk416Muzzle : RH_hk416sd {
			opticsDisablePeripherialVision = true;
			distanceZoomMin = 100;
			distanceZoomMax = 100;
		};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = AG36;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_hk417 : RH_hk416 {
		displayName = "Hk417";
		model = "\RH_hk416\RH_hk417.p3d";
		picture = "\RH_hk416\inv\hk417.paa";
		handAnim[] = {"OFP2_ManSkeleton"};
		descriptionShort = "HK417 is a battle rifle designed and manufactured in Germany by HK. It is essentially an enlarged HK416. Chambered for the 7.62x51mm NATO round";
		reloadMagazineSound[] = {"\RH_hk416\sound\Hk416_Reload.wss", 0.056234, 1, 20};
		magazines[] = {"RH_20Rnd_762x51_hk417", "20Rnd_762x51_DMR"};
		modes[] = {"Single", "FullAuto"};
		
		class Single : Single {
			begin1[] = {"\RH_hk416\sound\hk417.wss", 1.77828, 1, 1000};
			soundBegin[] = {"begin1", 1};
			dispersion = 0.0015;
			reloadTime = 0.1;
			recoil = "RH_Hk417_Recoil";
			recoilProne = "RH_Hk417_RecoilProne";
			minRange = 2;
			minRangeProbab = 0.1;
			midRange = 250;
			midRangeProbab = 0.7;
			maxRange = 400;
			maxRangeProbab = 0.5;
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\RH_hk416\sound\hk417.wss", 1.77828, 1, 1000};
			soundBegin[] = {"begin1", 1};
			dispersion = 0.004;
			reloadTime = 0.1;
			recoil = "RH_Hk417_Recoil";
			recoilProne = "RH_Hk417_RecoilProne";
			minRange = 2;
			minRangeProbab = 0.1;
			midRange = 50;
			midRangeProbab = 0.58;
			maxRange = 100;
			maxRangeProbab = 0.04;
		};
	};
	
	class RH_hk417aim : RH_hk417 {
		displayName = "Hk417 Aimpoint";
		model = "\RH_hk416\RH_hk417aim.p3d";
		picture = "\RH_hk416\inv\hk417aim.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_hk417eotech : RH_hk417 {
		displayName = "Hk417 Eotech";
		model = "\RH_hk416\RH_hk417eotech.p3d";
		picture = "\RH_hk416\inv\hk417eotech.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_hk417acog : RH_hk417 {
		displayName = "Hk417 Acog";
		model = "\RH_hk416\RH_hk417acog.p3d";
		picture = "\RH_hk416\inv\hk417acog.paa";
		modelOptics = "\RH_hk416\NWD_acog_ta31f.p3d";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 189;
				distanceZoomMax = 189;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_hk417sp : RH_hk417 {
		displayName = "Hk417 Sniper";
		model = "\RH_hk416\RH_hk417sp.p3d";
		picture = "\RH_hk416\inv\hk417sp.paa";
		modelOptics = "\RH_hk416\fnc_875x_illum_round_mildot.p3d";
		optics = true;
		weaponInfoType = "RscWeaponZeroing";
		
		class OpticsModes {
			class StepScope {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.033574;
				opticsZoomMax = 0.087666;
				opticsZoomInit = 0.087666;
				memoryPointCamera = "eye";
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 325;
				distanceZoomMax = 325;
				cameraDir = "";
				visionMode[] = {"Normal"};
				discreteDistance[] = {100, 200, 300, 400, 500, 600, 700, 800};
				discreteDistanceInitIndex = 2;
			};
		};
	};
	
	class RH_hk417s : RH_hk417 {
		displayName = "Hk417 Cqb";
		model = "\RH_hk416\RH_hk417s.p3d";
		picture = "\RH_hk416\inv\hk417s.paa";
		handAnim[] = {"OFP2_ManSkeleton"};
	};
	
	class RH_hk417saim : RH_hk417s {
		displayName = "Hk417 Cqb Aimpoint";
		model = "\RH_hk416\RH_hk417saim.p3d";
		picture = "\RH_hk416\inv\hk417saim.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_hk417seotech : RH_hk417s {
		displayName = "Hk417 Cqb Eotech";
		model = "\RH_hk416\RH_hk417seotech.p3d";
		picture = "\RH_hk416\inv\hk417seotech.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_hk417sacog : RH_hk417s {
		displayName = "Hk417 Cqb Acog";
		model = "\RH_hk416\RH_hk417sacog.p3d";
		picture = "\RH_hk416\inv\hk417sacog.paa";
		modelOptics = "\RH_hk416\NWD_acog_ta31f.p3d";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 189;
				distanceZoomMax = 189;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_hk417sd : RH_hk417 {
		fireLightDuration = 0.0;
		fireLightIntensity = 0.0;
		displayName = "Hk417 SD";
		model = "\RH_hk416\RH_hk417sd.p3d";
		picture = "\RH_hk416\inv\hk417sd.paa";
		opticsDisablePeripherialVision = true;
		magazines[] = {"RH_20Rnd_762x51_SD_hk417", "RH_20Rnd_762x51_hk417", "20Rnd_762x51_DMR"};
		modes[] = {"Single", "FullAuto"};
		
		class Single : Single {
			begin1[] = {"\RH_hk416\sound\hk417sd.wss", 1.0, 1, 300};
			soundBegin[] = {"begin1", 1};
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\RH_hk416\sound\hk417sd.wss", 1.0, 1, 300};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class RH_hk417sdaim : RH_hk417sd {
		displayName = "Hk417 SD Aimpoint";
		model = "\RH_hk416\RH_hk417sdaim.p3d";
		picture = "\RH_hk416\inv\hk417sdaim.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_hk417sdeotech : RH_hk417sd {
		displayName = "Hk417 SD Eotech";
		model = "\RH_hk416\RH_hk417sdeotech.p3d";
		picture = "\RH_hk416\inv\hk417sdeotech.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_hk417sdacog : RH_hk417sd {
		displayName = "Hk417 SD Acog";
		model = "\RH_hk416\RH_hk417sdacog.p3d";
		picture = "\RH_hk416\inv\hk417sdacog.paa";
		modelOptics = "\RH_hk416\NWD_acog_ta31f.p3d";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 189;
				distanceZoomMax = 189;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_hk417sdsp : RH_hk417sd {
		displayName = "Hk417 SD Sniper";
		model = "\RH_hk416\RH_hk417sdsp.p3d";
		picture = "\RH_hk416\inv\hk417sdsp.paa";
		modelOptics = "\RH_hk416\fnc_875x_illum_round_mildot.p3d";
		optics = true;
		weaponInfoType = "RscWeaponZeroing";
		
		class OpticsModes {
			class StepScope {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.033574;
				opticsZoomMax = 0.087666;
				opticsZoomInit = 0.087666;
				memoryPointCamera = "eye";
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 325;
				distanceZoomMax = 325;
				cameraDir = "";
				visionMode[] = {"Normal"};
				discreteDistance[] = {100, 200, 300, 400, 500, 600, 700, 800};
				discreteDistanceInitIndex = 2;
			};
		};
	};
	
	class RH_hk417sgl : RH_hk417s {
		displayName = "Hk417c AG36";
		model = "\RH_hk416\RH_hk417sgl.p3d";
		picture = "\RH_hk416\inv\hk417sgl.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk417Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk417Muzzle : RH_hk417s {};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = AG36;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_hk417sglaim : RH_hk417s {
		displayName = "Hk417c Aimpoint AG36";
		model = "\RH_hk416\RH_hk417sglaim.p3d";
		picture = "\RH_hk416\inv\hk417sglaim.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk417Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk417Muzzle : RH_hk417 {
			opticsDisablePeripherialVision = true;
			distanceZoomMin = 100;
			distanceZoomMax = 100;
		};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = AG36;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_hk417sgleotech : RH_hk417s {
		displayName = "Hk417c Eotech AG36";
		model = "\RH_hk416\RH_hk417sgleotech.p3d";
		picture = "\RH_hk416\inv\hk417sgleotech.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk417Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk417Muzzle : RH_hk417s {
			opticsDisablePeripherialVision = true;
			distanceZoomMin = 100;
			distanceZoomMax = 100;
		};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = AG36;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_hk417sglacog : RH_hk417s {
		displayName = "Hk417c Acog AG36";
		model = "\RH_hk416\RH_hk417sglacog.p3d";
		picture = "\RH_hk416\inv\hk417sglacog.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M16GL.rtm"};
		muzzles[] = {"RH_hk417Muzzle", "RH_AG36Muzzle"};
		dexterity = 1.59;
		
		class RH_hk417Muzzle : RH_hk417s {
			modelOptics = "\RH_hk416\NWD_acog_ta31f";
			
			class OpticsModes {
				class ACOG {
					opticsID = 1;
					useModelOptics = 1;
					opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
					opticsZoomMin = 0.071945;
					opticsZoomMax = 0.071945;
					opticsZoomInit = 0.071945;
					memoryPointCamera = "opticView";
					visionMode[] = {"Normal"};
					opticsFlare = "true";
					opticsDisablePeripherialVision = "true";
					distanceZoomMin = 189;
					distanceZoomMax = 189;
					cameraDir = "";
				};
				
				class Kolimator : ACOG {
					opticsID = 2;
					useModelOptics = 0;
					opticsFlare = "false";
					opticsDisablePeripherialVision = "false";
					opticsZoomMin = 0.25;
					opticsZoomMax = 1.1;
					opticsZoomInit = 0.5;
					memoryPointCamera = "eye";
					visionMode[] = {};
				};
			};
		};
		
		class RH_AG36Muzzle : GrenadeLauncher {
			displayName = AG36;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_ctar21 : RH_hk416 {
		displayName = "CTAR 21";
		model = "\RH_hk416\RH_ctar21.p3d";
		picture = "\RH_hk416\inv\ctar21.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\CA\weapons\Data\Anim\Bizon.rtm"};
		reloadMagazineSound[] = {"\RH_hk416\sound\ctar21_Reload.wss", 0.056234, 1, 20};
		modes[] = {"Single", "FullAuto"};
		
		class Single : Single {
			begin1[] = {"\RH_hk416\sound\ctar21.wss", 1.77828, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\RH_hk416\sound\ctar21.wss", 1.77828, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class RH_ctar21glacog : RH_ctar21 {
		displayName = "CTAR 21 Acog M203";
		model = "\RH_hk416\RH_ctar21glacog.p3d";
		picture = "\RH_hk416\inv\ctar21glacog.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\RH_hk416\Anim\RH_scargl.rtm"};
		dexterity = 1.59;
		muzzles[] = {"RH_ctar21Muzzle", "RH_M203Muzzle"};
		
		class RH_ctar21Muzzle : RH_ctar21 {
			modelOptics = "\RH_hk416\NWD_acog_ta31f.p3d";
			
			class OpticsModes {
				class ACOG {
					opticsID = 1;
					useModelOptics = 1;
					opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
					opticsZoomMin = 0.071945;
					opticsZoomMax = 0.071945;
					opticsZoomInit = 0.071945;
					memoryPointCamera = "opticView";
					visionMode[] = {"Normal"};
					opticsFlare = "true";
					opticsDisablePeripherialVision = "true";
					distanceZoomMin = 189;
					distanceZoomMax = 189;
					cameraDir = "";
				};
				
				class Kolimator : ACOG {
					opticsID = 2;
					useModelOptics = 0;
					opticsFlare = "false";
					opticsDisablePeripherialVision = "false";
					opticsZoomMin = 0.25;
					opticsZoomMax = 1.1;
					opticsZoomInit = 0.5;
					memoryPointCamera = "eye";
					visionMode[] = {};
				};
			};
		};
		
		class RH_M203Muzzle : GrenadeLauncher {
			displayName = M203;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_ctar21m : RH_ctar21 {
		displayName = "CTAR 21 Mars";
		model = "\RH_hk416\RH_ctar21m.p3d";
		picture = "\RH_hk416\inv\ctar21m.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
		irDistance = 100;
	};
	
	class RH_ctar21mgl : RH_ctar21 {
		displayName = "CTAR 21 Mars M203";
		model = "\RH_hk416\RH_ctar21mgl.p3d";
		picture = "\RH_hk416\inv\ctar21mgl.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
		irDistance = 100;
		handAnim[] = {"OFP2_ManSkeleton", "\RH_hk416\Anim\RH_scargl.rtm"};
		muzzles[] = {"RH_ctar21Muzzle", "RH_M203Muzzle"};
		dexterity = 1.59;
		
		class RH_ctar21Muzzle : RH_ctar21m {};
		
		class RH_M203Muzzle : GrenadeLauncher {
			displayName = M203;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_star21 : RH_ctar21 {
		displayName = "STAR 21 Acog";
		model = "\RH_hk416\RH_star21.p3d";
		picture = "\RH_hk416\inv\star21.paa";
		modelOptics = "\RH_hk416\NWD_acog_ta31f.p3d";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 189;
				distanceZoomMax = 189;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_mas : RH_hk416 {
		displayName = "Magpul Masada";
		model = "\RH_hk416\RH_mas.p3d";
		picture = "\RH_hk416\inv\mas.paa";
		handAnim[] = {"OFP2_ManSkeleton"};
		reloadMagazineSound[] = {"\RH_hk416\sound\ctar21_Reload.wss", 0.056234, 1, 20};
		modes[] = {"Single", "FullAuto"};
		
		class Single : Single {
			begin1[] = {"\RH_hk416\sound\acr.wss", 1.77828, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\RH_hk416\sound\acr.wss", 1.77828, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class RH_masaim : RH_mas {
		displayName = "Magp Masada Aimpoint";
		model = "\RH_hk416\RH_masaim.p3d";
		picture = "\RH_hk416\inv\masaim.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_maseotech : RH_mas {
		displayName = "Magp Masada Eotech";
		model = "\RH_hk416\RH_maseotech.p3d";
		picture = "\RH_hk416\inv\maseotech.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_masacog : RH_mas {
		displayName = "Magp Masada Acog";
		model = "\RH_hk416\RH_masacog.p3d";
		picture = "\RH_hk416\inv\masacog.paa";
		modelOptics = "\RH_hk416\NWD_acog_ta31f.p3d";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 189;
				distanceZoomMax = 189;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_massd : RH_mas {
		fireLightDuration = 0.0;
		fireLightIntensity = 0.0;
		displayName = "Masada SD";
		model = "\RH_hk416\RH_massd.p3d";
		picture = "\RH_hk416\inv\massd.paa";
		opticsDisablePeripherialVision = true;
		magazines[] = {"30Rnd_556x45_StanagSD", "30Rnd_556x45_G36SD", "30Rnd_556x45_Stanag", "20Rnd_556x45_Stanag"};
		modes[] = {"Single", "FullAuto"};
		
		class Single : Single {
			begin1[] = {"\RH_hk416\sound\massd.wss", 1.0, 1, 300};
			soundBegin[] = {"begin1", 1};
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\RH_hk416\sound\massd.wss", 1.0, 1, 300};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class RH_massdaim : RH_massd {
		displayName = "Masada SD Aimpoint";
		model = "\RH_hk416\RH_massdaim.p3d";
		picture = "\RH_hk416\inv\massdaim.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_massdeotech : RH_massd {
		displayName = "Masada SD Eotech";
		model = "\RH_hk416\RH_massdeotech.p3d";
		picture = "\RH_hk416\inv\massdeotech.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_massdacog : RH_massd {
		displayName = "Masada SD Acog";
		model = "\RH_hk416\RH_massdacog.p3d";
		picture = "\RH_hk416\inv\massdacog.paa";
		modelOptics = "\RH_hk416\NWD_acog_ta31f.p3d";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 189;
				distanceZoomMax = 189;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_masb : RH_mas {
		displayName = "Magp Masada Black";
		model = "\RH_hk416\RH_masb.p3d";
		picture = "\RH_hk416\inv\masb.paa";
		handAnim[] = {"OFP2_ManSkeleton"};
	};
	
	class RH_masbaim : RH_masb {
		displayName = "Magp Masada Aimpoint Black";
		model = "\RH_hk416\RH_masbaim.p3d";
		picture = "\RH_hk416\inv\masbaim.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_masbeotech : RH_masb {
		displayName = "Magp Masada Eotech Black";
		model = "\RH_hk416\RH_masbeotech.p3d";
		picture = "\RH_hk416\inv\masbeotech.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_masbacog : RH_masb {
		displayName = "Magp Masada Acog Black";
		model = "\RH_hk416\RH_masbacog.p3d";
		picture = "\RH_hk416\inv\masbacog.paa";
		modelOptics = "\RH_hk416\NWD_acog_ta31f.p3d";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 189;
				distanceZoomMax = 189;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_masbsd : RH_masb {
		fireLightDuration = 0.0;
		fireLightIntensity = 0.0;
		displayName = "Masada SD Black";
		model = "\RH_hk416\RH_masbsd.p3d";
		picture = "\RH_hk416\inv\masbsd.paa";
		opticsDisablePeripherialVision = true;
		magazines[] = {"30Rnd_556x45_StanagSD", "30Rnd_556x45_G36SD", "30Rnd_556x45_Stanag", "20Rnd_556x45_Stanag"};
		modes[] = {"Single", "FullAuto"};
		
		class Single : Single {
			begin1[] = {"\RH_hk416\sound\massd.wss", 1.0, 1, 300};
			soundBegin[] = {"begin1", 1};
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\RH_hk416\sound\massd.wss", 1.0, 1, 300};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class RH_masbsdaim : RH_masbsd {
		displayName = "Masada SD Aimpoint Black";
		model = "\RH_hk416\RH_masbsdaim.p3d";
		picture = "\RH_hk416\inv\masbsdaim.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_masbsdeotech : RH_masbsd {
		displayName = "Masada SD Eotech Black";
		model = "\RH_hk416\RH_masbsdeotech.p3d";
		picture = "\RH_hk416\inv\masbsdeotech.paa";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_masbsdacog : RH_masbsd {
		displayName = "Masada SD Acog Black";
		model = "\RH_hk416\RH_masbsdacog.p3d";
		picture = "\RH_hk416\inv\masbsdacog.paa";
		modelOptics = "\RH_hk416\NWD_acog_ta31f.p3d";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 189;
				distanceZoomMax = 189;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_acr : RH_hk416 {
		displayName = "Bushmaster ACR";
		model = "\RH_hk416\RH_acr.p3d";
		picture = "\RH_hk416\inv\acr.paa";
		handAnim[] = {"OFP2_ManSkeleton"};
		reloadMagazineSound[] = {"\RH_hk416\sound\ctar21_Reload.wss", 0.056234, 1, 20};
		modes[] = {"Single", "FullAuto"};
		
		class Single : Single {
			begin1[] = {"\RH_hk416\sound\acr.wss", 1.77828, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\RH_hk416\sound\acr.wss", 1.77828, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class RH_acraim : RH_acr {
		displayName = "Bush ACR Aimpoint";
		model = "\RH_hk416\RH_acraim.p3d";
		picture = "\RH_hk416\inv\acraim.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\RH_hk416\Anim\RH_acrgrip.rtm"};
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_acreotech : RH_acr {
		displayName = "Bush ACR Eotech";
		model = "\RH_hk416\RH_acreotech.p3d";
		picture = "\RH_hk416\inv\acreotech.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\RH_hk416\Anim\RH_acrgrip.rtm"};
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_acracog : RH_acr {
		displayName = "Bush ACR Acog";
		model = "\RH_hk416\RH_acracog.p3d";
		picture = "\RH_hk416\inv\acracog.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\RH_hk416\Anim\RH_acrgrip.rtm"};
		modelOptics = "\RH_hk416\NWD_acog_ta31f.p3d";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 189;
				distanceZoomMax = 189;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_acrgl : RH_acr {
		displayName = "Bush ACR ELGM";
		model = "\RH_hk416\RH_acrgl.p3d";
		picture = "\RH_hk416\inv\acrgl.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\RH_hk416\Anim\RH_scargl.rtm"};
		muzzles[] = {"RH_acrMuzzle", "RH_ELGMMuzzle"};
		dexterity = 1.59;
		
		class RH_acrMuzzle : RH_acr {};
		
		class RH_ELGMMuzzle : GrenadeLauncher {
			displayName = ELGM;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_acrglaim : RH_acrgl {
		displayName = "Bush ACR Aimpoint ELGM";
		model = "\RH_hk416\RH_acrglaim.p3d";
		picture = "\RH_hk416\inv\acrglaim.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\RH_hk416\Anim\RH_scargl.rtm"};
		muzzles[] = {"RH_acrMuzzle", "RH_ELGMMuzzle"};
		dexterity = 1.59;
		
		class RH_acrMuzzle : RH_acr {
			opticsDisablePeripherialVision = true;
			distanceZoomMin = 100;
			distanceZoomMax = 100;
		};
		
		class RH_ELGMMuzzle : GrenadeLauncher {
			displayName = ELGM;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_acrgleotech : RH_acrgl {
		displayName = "Bush ACR Eotech ELGM";
		model = "\RH_hk416\RH_acrgleotech.p3d";
		picture = "\RH_hk416\inv\acrgleotech.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\RH_hk416\Anim\RH_scargl.rtm"};
		muzzles[] = {"RH_acrMuzzle", "RH_ELGMMuzzle"};
		dexterity = 1.59;
		
		class RH_acrMuzzle : RH_acr {
			opticsDisablePeripherialVision = true;
			distanceZoomMin = 100;
			distanceZoomMax = 100;
		};
		
		class RH_ELGMMuzzle : GrenadeLauncher {
			displayName = ELGM;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_acrglacog : RH_acrgl {
		displayName = "Bush ACR Acog ELGM";
		model = "\RH_hk416\RH_acrglacog.p3d";
		picture = "\RH_hk416\inv\acrglacog.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\RH_hk416\Anim\RH_scargl.rtm"};
		muzzles[] = {"RH_acrMuzzle", "RH_ELGMMuzzle"};
		dexterity = 1.59;
		
		class RH_acrMuzzle : RH_acr {
			modelOptics = "\RH_hk416\NWD_acog_ta31f.p3d";
			
			class OpticsModes {
				class ACOG {
					opticsID = 1;
					useModelOptics = 1;
					opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
					opticsZoomMin = 0.071945;
					opticsZoomMax = 0.071945;
					opticsZoomInit = 0.071945;
					memoryPointCamera = "opticView";
					visionMode[] = {"Normal"};
					opticsFlare = "true";
					opticsDisablePeripherialVision = "true";
					distanceZoomMin = 189;
					distanceZoomMax = 189;
					cameraDir = "";
				};
				
				class Kolimator : ACOG {
					opticsID = 2;
					useModelOptics = 0;
					opticsFlare = "false";
					opticsDisablePeripherialVision = "false";
					opticsZoomMin = 0.25;
					opticsZoomMax = 1.1;
					opticsZoomInit = 0.5;
					memoryPointCamera = "eye";
					visionMode[] = {};
				};
			};
		};
		
		class RH_ELGMMuzzle : GrenadeLauncher {
			displayName = ELGM;
			magazines[] = {"1Rnd_HE_M203", "FlareWhite_M203", "FlareGreen_M203", "FlareRed_M203", "FlareYellow_M203", "1Rnd_Smoke_M203", "1Rnd_SmokeRed_M203", "1Rnd_SmokeGreen_M203", "1Rnd_SmokeYellow_M203"};
			sound[] = {"\RH_hk416\sound\AG36.wss", db-5, 1};
			reloadMagazineSound[] = {"\RH_hk416\sound\AG36_Reload.wss", 0.056234, 1, 20};
			magazineReloadTime = 0;
			reloadTime = 0.1;
			recoil = "RH_AG36GLbase";
			optics = true;
			modelOptics = "-";
			cameraDir = "GL look";
			memoryPointCamera = "GL eye";
			opticsZoomMin = 0.22;
			opticsZoomMax = 0.95;
			opticsZoomInit = 0.42;
		};
	};
	
	class RH_acrb : RH_acr {
		displayName = "Bushmaster ACR Black";
		model = "\RH_hk416\RH_acrb.p3d";
		picture = "\RH_hk416\inv\acrb.paa";
	};
	
	class RH_acrbaim : RH_acraim {
		displayName = "Bush ACR Aimpoint Black";
		model = "\RH_hk416\RH_acrbaim.p3d";
		picture = "\RH_hk416\inv\acrbaim.paa";
	};
	
	class RH_acrbeotech : RH_acreotech {
		displayName = "Bush ACR Eotech Black";
		model = "\RH_hk416\RH_acrbeotech.p3d";
		picture = "\RH_hk416\inv\acrbeotech.paa";
	};
	
	class RH_acrbacog : RH_acracog {
		displayName = "Bush ACR Acog Black";
		model = "\RH_hk416\RH_acrbacog.p3d";
		picture = "\RH_hk416\inv\acrbacog.paa";
	};
	
	class RH_acrbgl : RH_acrgl {
		displayName = "Bush ACR ELGM Black";
		model = "\RH_hk416\RH_acrbgl.p3d";
		picture = "\RH_hk416\inv\acrbgl.paa";
	};
	
	class RH_acrbglaim : RH_acrglaim {
		displayName = "Bush ACR Aimpoint ELGM Black";
		model = "\RH_hk416\RH_acrbglaim.p3d";
		picture = "\RH_hk416\inv\acrbglaim.paa";
	};
	
	class RH_acrbgleotech : RH_acrgleotech {
		displayName = "Bush ACR Eotech ELGM Black";
		model = "\RH_hk416\RH_acrbgleotech.p3d";
		picture = "\RH_hk416\inv\acrbgleotech.paa";
	};
	
	class RH_acrbglacog : RH_acrglacog {
		displayName = "Bush ACR Acog ELGM Black";
		model = "\RH_hk416\RH_acrbglacog.p3d";
		picture = "\RH_hk416\inv\acrbglacog.paa";
	};
};
