// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class arma1_sf_port_patch {
		units[] = {"arma1_us_soldier_sabass", "arma1_us_soldier_sabmark", "arma1_us_soldier_sabot"};
		weapons[] = {};
		requiredVersion = 1.0;
		requiredAddons[] = {};
	};
};
