// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class RH_m14 {
		units[] = {"RHm14box"};
		weapons[] = {"RH_m14", "RH_m14acog", "RH_m14aim", "RH_m14eot", "RH_m21", "RH_sc2", "RH_sc2acog", "RH_sc2aim", "RH_sc2eot", "RH_sc2shd", "RH_sc2sp", "RH_m1s", "RH_m1sacog", "RH_m1saim", "RH_m1seot", "RH_m1sshd", "RH_m1ssp", "RH_m1st", "RH_m1stacog", "RH_m1staim", "RH_m1steot", "RH_m1stshd", "RH_m1stsp"};
		requiredVersion = 1.0;
		requiredAddons[] = {"CAweapons"};
	};
};
