// Generated by unRap v1.06 by Kegetys

class cfgRecoils {
	RH_M14Recoil[] = {0, 0.013, 0.015, 0.02, 0.013, 0.015, 0.1, 0.009, 0.015, 0.12, 0, 0};
	RH_M14prRecoil[] = {0, 0.012, 0.01, 0.013, 0.012, 0.01, 0.07, 0.007, 0, 0.12, 0, 0};
};
