// Generated by unRap v1.06 by Kegetys

class cfgVehicles {
	class ReammoBox;	// External class reference
	
	class RHm14box : ReammoBox {
		scope = public;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		model = "\ca\weapons\AmmoBoxes\USBasicWeapons.p3d";
		displayName = "RH M14 weapons box";
		
		class TransportMagazines {
			class _xx_20Rnd_762x51_DMR {
				magazine = "20Rnd_762x51_DMR";
				count = 200;
			};
			
			class _xx_HandGrenade_West {
				magazine = "HandGrenade_West";
				count = 50;
			};
		};
		
		class TransportWeapons {
			class _xx_RH_m14 {
				weapon = "RH_m14";
				count = 6;
			};
			
			class _xx_RH_m14acog {
				weapon = "RH_m14acog";
				count = 6;
			};
			
			class _xx_RH_m14aim {
				weapon = "RH_m14aim";
				count = 6;
			};
			
			class _xx_RH_m14eot {
				weapon = "RH_m14eot";
				count = 6;
			};
			
			class _xx_RH_m21 {
				weapon = "RH_m21";
				count = 6;
			};
			
			class _xx_RH_sc2 {
				weapon = "RH_sc2";
				count = 6;
			};
			
			class _xx_RH_sc2acog {
				weapon = "RH_sc2acog";
				count = 6;
			};
			
			class _xx_RH_sc2aim {
				weapon = "RH_sc2aim";
				count = 6;
			};
			
			class _xx_RH_sc2eot {
				weapon = "RH_sc2eot";
				count = 6;
			};
			
			class _xx_RH_sc2shd {
				weapon = "RH_sc2shd";
				count = 6;
			};
			
			class _xx_RH_sc2sp {
				weapon = "RH_sc2sp";
				count = 6;
			};
			
			class _xx_RH_m1s {
				weapon = "RH_m1s";
				count = 6;
			};
			
			class _xx_RH_m1sacog {
				weapon = "RH_m1sacog";
				count = 6;
			};
			
			class _xx_RH_m1saim {
				weapon = "RH_m1saim";
				count = 6;
			};
			
			class _xx_RH_m1seot {
				weapon = "RH_m1seot";
				count = 6;
			};
			
			class _xx_RH_m1sshd {
				weapon = "RH_m1sshd";
				count = 6;
			};
			
			class _xx_RH_m1ssp {
				weapon = "RH_m1ssp";
				count = 6;
			};
			
			class _xx_RH_m1st {
				weapon = "RH_m1st";
				count = 6;
			};
			
			class _xx_RH_m1stacog {
				weapon = "RH_m1stacog";
				count = 6;
			};
			
			class _xx_RH_m1staim {
				weapon = "RH_m1staim";
				count = 6;
			};
			
			class _xx_RH_m1steot {
				weapon = "RH_m1steot";
				count = 6;
			};
			
			class _xx_RH_m1stshd {
				weapon = "RH_m1stshd";
				count = 6;
			};
			
			class _xx_RH_m1stsp {
				weapon = "RH_m1stsp";
				count = 6;
			};
		};
	};
};
