// Generated by unRap v1.06 by Kegetys

class cfgWeapons {
	class Default;	// External class reference
	class PistolCore;	// External class reference
	class Pistol;	// External class reference
	class RifleCore;	// External class reference
	class MGunCore;	// External class reference
	class LauncherCore;	// External class reference
	class GrenadeCore;	// External class reference
	class CannonCore;	// External class reference
	class Launcher;	// External class reference
	class GrenadeLauncher;	// External class reference
	class RocketPods;	// External class reference
	class MissileLaunche;	// External class reference
	class MGun;	// External class reference
	class Rifle;	// External class reference
	
	class RH_m14 : Rifle {
		scope = public;
		model = "\RH_m14\RH_m14.p3d";
		picture = "\RH_m14\inv\m14.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		optics = true;
		opticsDisablePeripherialVision = true;
		displayName = M14;
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M24.rtm"};
		reloadMagazineSound[] = {"\RH_m14\Sound\M14_Reload.wss", 0.056234, 1, 20};
		magazines[] = {"20Rnd_762x51_DMR"};
		modes[] = {"Single", "FullAuto"};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\RH_m14\Sound\m14.wss", 1.77828, 1, 1000};
			soundBegin[] = {"begin1", 1};
			soundBurst = 1;
			soundContinuous = 0;
			multiplier = 1;
			burst = 1;
			dispersion = 7.125e-005;
			reloadTime = 0.1;
			recoil = "RH_M14Recoil";
			recoilProne = "RH_M14prRecoil";
			aiRateOfFire = 0.6;	// delay between shots at given distance
			aiRateOfFireDistance = 550;
			minRange = 2;
			minRangeProbab = 0.1;
			midRange = 400;
			midRangeProbab = 0.7;
			maxRange = 650;
			maxRangeProbab = 0.05;
		};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\RH_m14\Sound\m14.wss", 1.77828, 1, 1000};
			soundBegin[] = {"begin1", 1};
			dispersion = 0.000285;
			reloadTime = 0.1;
			recoil = "RH_M14Recoil";
			recoilProne = "RH_M14prRecoil";
			minRange = 2;
			minRangeProbab = 0.1;
			midRange = 60;
			midRangeProbab = 0.7;
			maxRange = 90;
			maxRangeProbab = 0.05;
		};
		
		class Library {
			libTextDesc = "The M14 rifle more formally the United States Rifle, Caliber 7.62 mm, M14 is an American selective fire battle rifle firing 7.62 × 51 mm NATO ammunition. Although largely superseded in military use by the M16 rifle, it remains in limited front line service with the United States Army, Marine Corps, and Navy. The M14 also provides the basis for the M21 and XM25 sniper rifles not to be confused with the XM25 grenade launcher.Mk14 EBR is shorter, more tactical version of the M14, with a retractable stock and multiple rails for more accessories.";
		};
	};
	
	class RH_m14acog : RH_m14 {
		scope = public;
		model = "\RH_m14\RH_m14acog.p3d";
		picture = "\RH_m14\inv\m14acog.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		modelOptics = "\RH_m14\NWD_acog_ta31f.p3d";
		displayName = "M14 Acog";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 100;
				distanceZoomMax = 100;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_m14aim : RH_m14 {
		scope = public;
		model = "\RH_m14\RH_m14aim.p3d";
		picture = "\RH_m14\inv\m14aim.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		displayName = "M14 Aimpoint";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_m14eot : RH_m14 {
		scope = public;
		model = "\RH_m14\RH_m14eot.p3d";
		picture = "\RH_m14\inv\m14eot.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		displayName = "M14 Eotech";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_m21 : RH_m14 {
		scope = public;
		model = "\RH_m14\RH_m21.p3d";
		picture = "\RH_m14\inv\m21.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		modelOptics = "\RH_m14\fnc_10x_round_mildot";
		opticsZoomMin = 0.029624;
		opticsZoomMax = 0.08222;
		opticsZoomInit = 0.08222;
		distanceZoomMin = 329;
		distanceZoomMax = 329;
		optics = true;
		displayName = M21;
		magazines[] = {"20Rnd_762x51_DMR"};
		modes[] = {"Single"};
	};
	
	class RH_sc2 : RH_m14 {
		scope = public;
		model = "\RH_m14\RH_sc2.p3d";
		picture = "\RH_m14\inv\sc2.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		displayName = "Socom II";
	};
	
	class RH_sc2acog : RH_sc2 {
		scope = public;
		model = "\RH_m14\RH_sc2acog.p3d";
		picture = "\RH_m14\inv\sc2acog.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		modelOptics = "\RH_m14\NWD_acog_ta31f.p3d";
		displayName = "Socom II Acog";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 100;
				distanceZoomMax = 100;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_sc2aim : RH_sc2 {
		scope = public;
		model = "\RH_m14\RH_sc2aim.p3d";
		picture = "\RH_m14\inv\sc2aim.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		displayName = "Socom II Aimpoint";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_sc2eot : RH_sc2 {
		scope = public;
		model = "\RH_m14\RH_sc2eot.p3d";
		picture = "\RH_m14\inv\sc2eot.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		displayName = "Socom II Eotech";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_sc2shd : RH_sc2 {
		scope = public;
		model = "\RH_m14\RH_sc2shd.p3d";
		picture = "\RH_m14\inv\sc2shd.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		opticsZoomInit = 0.249;
		opticsZoomMin = 0.0623;
		opticsZoomMax = 0.249;
		distanceZoomMin = 189;
		distanceZoomMax = 189;
		optics = true;
		modelOptics = "\RH_m14\NWD_shortdot_cqb.p3d";
		displayName = "Socom II Shortdot";
	};
	
	class RH_sc2sp : RH_sc2 {
		scope = public;
		model = "\RH_m14\RH_sc2sp.p3d";
		picture = "\RH_m14\inv\sc2sp.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		modelOptics = "\RH_m14\fnc_10x_round_mildot";
		opticsZoomMin = 0.029624;
		opticsZoomMax = 0.08222;
		opticsZoomInit = 0.08222;
		distanceZoomMin = 329;
		distanceZoomMax = 329;
		optics = true;
		displayName = "Socom II SP";
	};
	
	class RH_m1s : RH_m14 {
		scope = public;
		model = "\RH_m14\RH_m1s.p3d";
		picture = "\RH_m14\inv\m1s.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\RH_m14\Anim\RH_m14cs.rtm"};
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		displayName = M1SE1;
	};
	
	class RH_m1sacog : RH_m1s {
		scope = public;
		model = "\RH_m14\RH_m1sacog.p3d";
		picture = "\RH_m14\inv\m1sacog.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		modelOptics = "\RH_m14\NWD_acog_ta31f.p3d";
		displayName = "M1SE1 Acog";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 100;
				distanceZoomMax = 100;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_m1saim : RH_m1s {
		scope = public;
		model = "\RH_m14\RH_m1saim.p3d";
		picture = "\RH_m14\inv\m1saim.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		displayName = "M1SE1 Aimpoint";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_m1seot : RH_m1s {
		scope = public;
		model = "\RH_m14\RH_m1seot.p3d";
		picture = "\RH_m14\inv\m1seot.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		displayName = "M1SE1 Eotech";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_m1sshd : RH_m1s {
		scope = public;
		model = "\RH_m14\RH_m1sshd.p3d";
		picture = "\RH_m14\inv\m1sshd.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		opticsZoomInit = 0.249;
		opticsZoomMin = 0.0623;
		opticsZoomMax = 0.249;
		distanceZoomMin = 189;
		distanceZoomMax = 189;
		optics = true;
		modelOptics = "\RH_m14\NWD_shortdot_cqb.p3d";
		displayName = "M1SE1 Shortdot";
	};
	
	class RH_m1ssp : RH_m1s {
		scope = public;
		model = "\RH_m14\RH_m1ssp.p3d";
		picture = "\RH_m14\inv\m1ssp.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		modelOptics = "\RH_m14\fnc_10x_round_mildot";
		opticsZoomMin = 0.029624;
		opticsZoomMax = 0.08222;
		opticsZoomInit = 0.08222;
		distanceZoomMin = 329;
		distanceZoomMax = 329;
		optics = true;
		displayName = "M1SE1 SP";
	};
	
	class RH_m1st : RH_m14 {
		scope = public;
		model = "\RH_m14\RH_m1st.p3d";
		picture = "\RH_m14\inv\m1st.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\RH_m14\Anim\RH_m14cs.rtm"};
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		displayName = "M1SE1 Tan";
	};
	
	class RH_m1stacog : RH_m1st {
		scope = public;
		model = "\RH_m14\RH_m1stacog.p3d";
		picture = "\RH_m14\inv\m1stacog.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		modelOptics = "\RH_m14\NWD_acog_ta31f.p3d";
		displayName = "M1SE1 Tan Acog";
		
		class OpticsModes {
			class ACOG {
				opticsID = 1;
				useModelOptics = 1;
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
				opticsZoomMin = 0.071945;
				opticsZoomMax = 0.071945;
				opticsZoomInit = 0.071945;
				memoryPointCamera = "opticView";
				visionMode[] = {"Normal"};
				opticsFlare = "true";
				opticsDisablePeripherialVision = "true";
				distanceZoomMin = 100;
				distanceZoomMax = 100;
				cameraDir = "";
			};
			
			class Kolimator : ACOG {
				opticsID = 2;
				useModelOptics = 0;
				opticsFlare = "false";
				opticsDisablePeripherialVision = "false";
				opticsZoomMin = 0.25;
				opticsZoomMax = 1.1;
				opticsZoomInit = 0.5;
				memoryPointCamera = "eye";
				visionMode[] = {};
			};
		};
	};
	
	class RH_m1staim : RH_m1st {
		scope = public;
		model = "\RH_m14\RH_m1staim.p3d";
		picture = "\RH_m14\inv\m1staim.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		displayName = "M1SE1 Tan Aimpoint";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_m1steot : RH_m1st {
		scope = public;
		model = "\RH_m14\RH_m1steot.p3d";
		picture = "\RH_m14\inv\m1steot.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		displayName = "M1SE1 Tan Eotech";
		opticsDisablePeripherialVision = true;
		distanceZoomMin = 100;
		distanceZoomMax = 100;
	};
	
	class RH_m1stshd : RH_m1st {
		scope = public;
		model = "\RH_m14\RH_m1stshd.p3d";
		picture = "\RH_m14\inv\m1stshd.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		opticsZoomInit = 0.249;
		opticsZoomMin = 0.0623;
		opticsZoomMax = 0.249;
		distanceZoomMin = 189;
		distanceZoomMax = 189;
		optics = true;
		modelOptics = "\RH_m14\NWD_shortdot_cqb.p3d";
		displayName = "M1SE1 Tan Shortdot";
	};
	
	class RH_m1stsp : RH_m1st {
		scope = public;
		model = "\RH_m14\RH_m1stsp.p3d";
		picture = "\RH_m14\inv\m1stsp.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		modelOptics = "\RH_m14\fnc_10x_round_mildot";
		opticsZoomMin = 0.029624;
		opticsZoomMax = 0.08222;
		opticsZoomInit = 0.08222;
		distanceZoomMin = 329;
		distanceZoomMax = 329;
		optics = true;
		displayName = "M1SE1 Tan SP";
	};
};
