// config.bin - 13:29:00 06/17/17, generated in 0.09 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

#include "CfgPatches.hpp"
#include "cfgRecoils.hpp"
#include "Mode_SemiAuto.hpp"
#include "Mode_Burst.hpp"
#include "Mode_FullAuto.hpp"
#include "cfgWeapons.hpp"
#include "cfgVehicles.hpp"
