// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class MAP_EU {
		units[] = {};
		weapons[] = {};
		requiredAddons[] = {"CAData", "CAMisc", "CAMisc2", "CAMisc3", "CABuildings", "CABuildings2", "CAStructures", "CASigns2", "CARoads2", "CARocks2", CAA10, "CAAir", "CAAir2", "CAAir3", "CAWheeled", "CAWheeled2", "CAWater2", "CATracked", "CACharacters2"};
		requiredVersion = 1.02;
	};
};
