// Generated by unRap v1.06 by Kegetys

class CfgVehicleClasses {
	class MAP_EUPlants {
		displayName = "MAP: EU-Plants";
	};
	
	class MAP_EURocks {
		displayName = "MAP: EU-Rocks";
	};
	
	class MAP_EURoads {
		displayName = "MAP: EU-Roads";
	};
	
	class MAP_EUSWalk {
		displayName = "MAP: EU-SWalks";
	};
	
	class MAP_EUHouses {
		displayName = "MAP: EU-Houses";
	};
	
	class MAP_EUIndus {
		displayName = "MAP: EU-Industry";
	};
	
	class MAP_EURail {
		displayName = "MAP: EU-Rails";
	};
	
	class MAP_EUMilitary {
		displayName = "MAP: EU-Military";
	};
	
	class MAP_EURuins {
		displayName = "MAP: EU-Ruins";
	};
	
	class MAP_EUWalls {
		displayName = "MAP: EU-Walls";
	};
	
	class MAP_EUMisc {
		displayName = "MAP: EU-Misc";
	};
	
	class MAP_EUSigns {
		displayName = "MAP: EU-Signs";
	};
	
	class MAP_EUInter {
		displayName = "MAP: EU-Interieur";
	};
	
	class MAP_EUWater {
		displayName = "MAP: EU-Water";
	};
};
