// Generated by unRap v1.06 by Kegetys

class CfgAmmo {
	class RocketCore;	// External class reference
	
	class GyroGrenade : RocketCore {
		model = "\ca\Weapons\M67";
		hit = 20;
		indirectHit = 18;
		indirectHitRange = 7;
		soundHit[] = {"Ca\sounds\Weapons\explosions\grenade_new1", db24, 1, 1000};
		soundFly[] = {"Ca\sounds\Weapons\explosions\noise", db-80, 1, 20};
		CraterEffects = "GrenadeCrater";
		explosionEffects = "GrenadeExplosion";
		visibleFire = 18;	// how much is visible when this weapon is fired
		audibleFire = 18;
		visibleFireTime = 3;	// how long is it visible
		explosive = true;
		cost = 10;
		initTime = 0;
		thrustTime = 0;
		thrust = 0;
		whistleDist = 0;
	};
};
