// Generated by unRap v1.06 by Kegetys

class CfgMagazines {
	class Default;	// External class reference
	
	class CA_Magazine : Default {};
	
	class VehicleMagazine : CA_Magazine {};
	
	class 3Rnd_GyroGrenade : VehicleMagazine {
		scope = public;
		displayName = "Grenade";
		ammo = "GyroGrenade";
		count = 3;
		initSpeed = 3;
		maxLeadSpeed = 200;	// max estimated speed km/h
		nameSound = "grenade";
	};
};
