// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class All {};
	
	class AllVehicles : All {};
	
	class Air : AllVehicles {
		class ViewPilot;	// External class reference
	};
	
	class Plane : Air {
		class AnimationSources;	// External class reference
	};
	
	class CSJ_GyroP : Plane {
		scope = public;
		faction = CIV;
		crew = "Pilot";
		cabinOpening = 0;
		driverAction = "UH60_Pilot";
		vehicleClass = "CSJ_Air";
		model = "\CSJ_GyroAC\CSJ_GyroP";
		displayName = "AutoGyro";
		getInAction = "GetInLow";
		transportSoldier = 0;
		picture = "\CSJ_GyroAC\data\gyropic.paa";
		Icon = "\CSJ_GyroAC\data\gyroIcon.paa";
		gearRetracting = false;
		nameSound = "plane";
		mapSize = 8;
		fov = 0.5;
		side = TCivilian;
		soundEngine[] = {"\CSJ_GyroAC\camel1.wss", 5.62341, 1.8};
		insideSoundCoef = 1;
		airBrake = 0;
		flaps = 0;
		wheelSteeringSensitivity = 0.25;
		nightVision = false;
		preferRoads = false;
		showWeaponCargo = 0;
		camouflage = 8;	// how dificult to spot - bigger - better spotable
		audible = 5;	// audible - bigger - better heard
		driverCanSee = 2+8;
		maxSpeed = 150;	// max speed on level road, km/h
		landingSpeed = 80;
		landingAoa = "rad 2";
		armor = 20;
		ejectSpeed[] = {0, 0, 0};
		ejectDamageLimit = 0.8;
		cost = 1000;
		formationX = 8;
		formationZ = 8;
		castCargoShadow = false;
		castCommanderShadow = 0;
		castDriverShadow = true;
		castGunnerShadow = false;
		hideWeaponsDriver = true;
		hideWeaponsCargo = true;
		
		// threat (VSoft, VArmor, VAir), how threatening vehicle is to unit types
		threat[] = {0, 0, 0};

		aileronSensitivity = 0.1;	// relative aileron sensitivity
		elevatorSensitivity = 0.12;	// relative elevator sensitivity
		noseDownCoef = 0;	// how much goes nose down during turns
		brakeDistance = 10;	// vehicle movement precision
		dammageHalf[] = {};
		dammageFull[] = {};
		extCameraPosition[] = {0, 0, -5};
		
		class Library {
			libTextDesc = "Auto_Gyro (CSJ)";
		};
		
		// internal camera viewing limitations
		class ViewPilot : ViewPilot {
			initFov = 1;
			minFov = 0.3;
			maxFov = 1.2;
			initAngleX = 25;
			minAngleX = -65;
			maxAngleX = 80;
			initAngleY = 0;
			minAngleY = -155;
			maxAngleY = 155;
		};
		
		class AnimationSources : AnimationSources {};
		
		class Reflectors {};
		weapons[] = {"GyroGrenadeLauncher"};
		magazines[] = {"3Rnd_GyroGrenade"};
		
		class UserActions {
			class rotateLeft {
				displayName = "rotate aircraft left";
				position = "osa leve smerovky";
				onlyforplayer = 0;
				radius = 2;
				condition = "(Count (Crew this)==0) and ((getpos this select 2) <1) and (!isengineon this)";
				statement = "this exec ""\CSJ_GyroAC\scripts\CSJ_rotateGyroLeft.sqs"" ";
			};
			
			class rotateRight {
				displayName = "rotate aircraft right";
				position = "osa leve smerovky";
				onlyforplayer = 0;
				radius = 2;
				condition = "(Count (Crew this)==0) and ((getpos this select 2) <1) and (!isengineon this)";
				statement = "this exec ""\CSJ_GyroAC\scripts\CSJ_rotateGyroRight.sqs"" ";
			};
			
			class push {
				displayName = "push aircraft";
				position = "osa leve smerovky";
				onlyforplayer = 0;
				radius = 2;
				condition = "(Count (Crew this)==0) and ((getpos this select 2) <1) and (!isengineon this)";
				statement = "this exec ""\CSJ_GyroAC\scripts\CSJ_moveGyro.sqs"" ";
			};
		};
		
		class EventHandlers {};
	};
	
	class CSJ_GyroCover : CSJ_GyroP {
		model = "\CSJ_GyroAC\CSJ_GyroCover";
		displayName = "AutoGyro enclosed";
		
		class Library {
			libTextDesc = "Auto_Gyro  Enclosed(CSJ)";
		};
	};
	
	class Helicopter : Air {
		class AnimationSources;	// External class reference
		class Turrets;	// External class reference
	};
	
	class CSJ_GyroC : Helicopter {
		scope = public;
		model = "\CSJ_GyroAC\CSJ_GyroC.p3d";
		displayName = "Mozzie";
		mapSize = 8;
		side = TCivilian;
		cabinOpening = 0;
		hiddenSelections[] = {"0", "1", "2", "3", "4", "5"};
		vehicleClass = "CSJ_Air";
		picture = "\CSJ_GyroAC\data\MozPic.paa";
		maxSpeed = 120;	// max speed on level road, km/h
		Icon = "\CSJ_GyroAC\data\Cicon.paa";
		nameSound = "chopper";
		faction = CIV;
		crew = "Pilot";
		accuracy = 0.3;	// accuracy needed to recognize type of this target
		armor = 30;
		damageResistance = 0.003;
		cost = 100000;
		mainRotorSpeed = 1;
		backRotorSpeed = 1;
		transportSoldier = 0;
		cargoAction[] = {};
		transportAmmo = 0;
		supplyRadius = 2.5;
		type = "VAir";
		fov = 0.5;
		driverAction = "UH60_Pilot";
		hasGunner = false;
		
		class Turrets {};
		insideSoundCoef = 1;
		formationX = 8;
		formationZ = 8;
		
		// threat (VSoft, VArmor, VAir), how threatening vehicle is to unit types
		threat[] = {0, 0, 0};

		extCameraPosition[] = {0, 0, -5};
		soundGetIn[] = {"", 0.1, 1};
		soundGetOut[] = {"", 0.1, 1};
		soundEngine[] = {"\CSJ_GyroAC\UH1_v1.wss", 10.1189, 2};
		typicalCargo[] = {};
		weapons[] = {"GyroGrenadeLauncher"};
		magazines[] = {"3Rnd_GyroGrenade"};
		transportMaxMagazines = 0;
		transportMaxWeapons = 0;
		forceHideDriver = true;
		castDriverShadow = true;
		
		// internal camera viewing limitations
		class ViewPilot : ViewPilot {
			initFov = 1;
			minFov = 0.3;
			maxFov = 1.2;
			initAngleX = 35;
			minAngleX = -45;
			maxAngleX = 80;
			initAngleY = 0;
			minAngleY = -155;
			maxAngleY = 155;
		};
		
		class Library {
			libTextDesc = "CSJ_Mozzie";
		};
		dammageHalf[] = {};
		dammageFull[] = {};
		
		class Reflectors {};
		
		class AnimationSources : AnimationSources {};
		
		class UserActions {};
		
		class EventHandlers {};
	};
};
