// Generated by unRap v1.06 by Kegetys

class cfgWeapons {
	class RocketPods;	// External class reference
	
	class GyroGrenadeLauncher : RocketPods {
		scope = protected;
		displayName = "Grenades";
		cursorAim = "\ca\Weapons\Data\clear_empty";
		cursor = "\ca\Weapons\Data\clear_empty";
		autoFire = false;
		sound[] = {"", db20, 1};
		magazines[] = {"3Rnd_GyroGrenade"};
		reloadTime = 3;
		magazineReloadTime = 5;
		dispersion = 0;
		minRange = 1;
		minRangeProbab = 0.8;
		midRange = 50;
		midRangeProbab = 0.7;
		maxRange = 150;
		maxRangeProbab = 0.1;
		autoReload = true;
		canLock = LockNo;
	};
};
