// config.bin - 13:01:03 06/17/17, generated in 0.06 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define true	1
#define false	0

#define private		0
#define protected		1
#define public		2

#define LockNo		0
#define LockCadet		1
#define LockYes		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#include "CfgVehicleClasses.hpp"
#include "CfgPatches.hpp"
#include "CfgAmmo.hpp"
#include "CfgMagazines.hpp"
#include "cfgWeapons.hpp"
#include "CfgVehicles.hpp"
