// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class RH_de_cfg {
		units[] = {"RHpammobox"};
		weapons[] = {"RH_deagle", "RH_deagleg", "RH_deagles", "RH_deaglem", "RH_deaglemz", "RH_deaglemzb", "RH_browninghp", "RH_mk22", "RH_mk22sd", "RH_mk22v", "RH_mk22vsd", "RH_usp", "RH_uspsd", "RH_m1911", "RH_m1911sd", "RH_m1911old", "RH_uspm", "RH_m93r", "RH_m9", "RH_m9sd", "RH_m9c", "RH_m9sdc", "RH_vz61", "RH_muzi", "RH_g18", "RH_g17", "RH_tec9", "RH_tt33", "RH_mk2", "RH_p38", "RH_ppk", "RH_p226", "RH_p226s", "RH_anac", "RH_anacg", "RH_bull", "RH_python", "RH_g19", "RH_g19t"};
		requiredAddons[] = {"CAweapons"};
		requiredVersion = 1.02;
	};
};
