// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class All;	// External class reference
	class AllVehicles;	// External class reference
	class ThingEffect;	// External class reference
	class Land;	// External class reference
	class Man;	// External class reference
	class CAManBase;	// External class reference
	class ReammoBox;	// External class reference
	class SoldierWB;	// External class reference
	
	class USBasicAmmunitionBox : ReammoBox {};
	
	class RHpistammobox : USBasicAmmunitionBox {
		displayName = "RH Pistol Ammo Box";
		
		class TransportWeapons {
			class xxRH_deagle {
				weapon = "RH_deagle";
				count = 3;
			};
			
			class xxRH_Deagleg {
				weapon = "RH_Deagleg";
				count = 3;
			};
			
			class xxRH_Deagles {
				weapon = "RH_Deagles";
				count = 3;
			};
			
			class xxRH_deaglem {
				weapon = "RH_deaglem";
				count = 3;
			};
			
			class xxRH_Deaglemz {
				weapon = "RH_Deaglemz";
				count = 3;
			};
			
			class xxRH_Deaglemzb {
				weapon = "RH_Deaglemzb";
				count = 3;
			};
			
			class xxRH_browninghp {
				weapon = "RH_browninghp";
				count = 3;
			};
			
			class xxRH_anac {
				weapon = "RH_anac";
				count = 3;
			};
			
			class xxRH_anacg {
				weapon = "RH_anacg";
				count = 3;
			};
			
			class xxRH_bull {
				weapon = "RH_bull";
				count = 3;
			};
			
			class xxRH_python {
				weapon = "RH_python";
				count = 3;
			};
			
			class xxRH_mk22 {
				weapon = "RH_mk22";
				count = 3;
			};
			
			class xxRH_mk22sd {
				weapon = "RH_mk22sd";
				count = 3;
			};
			
			class xxRH_mk22v {
				weapon = "RH_mk22v";
				count = 3;
			};
			
			class xxRH_mk22vsd {
				weapon = "RH_mk22vsd";
				count = 3;
			};
			
			class xxRH_usp {
				weapon = "RH_usp";
				count = 3;
			};
			
			class xxRH_uspsd {
				weapon = "RH_uspsd";
				count = 3;
			};
			
			class xxRH_uspm {
				weapon = "RH_uspm";
				count = 3;
			};
			
			class xxRH_m1911 {
				weapon = "RH_m1911";
				count = 3;
			};
			
			class xxRH_m1911sd {
				weapon = "RH_m1911sd";
				count = 3;
			};
			
			class xxRH_m1911old {
				weapon = "RH_m1911old";
				count = 3;
			};
			
			class xxRH_m9 {
				weapon = "RH_m9";
				count = 3;
			};
			
			class xxRH_m9sd {
				weapon = "RH_m9sd";
				count = 3;
			};
			
			class xxRH_m9c {
				weapon = "RH_m9c";
				count = 3;
			};
			
			class xxRH_m9csd {
				weapon = "RH_m9csd";
				count = 3;
			};
			
			class xxRH_m93r {
				weapon = "RH_m93r";
				count = 3;
			};
			
			class xxRH_g17 {
				weapon = "RH_g17";
				count = 3;
			};
			
			class xxRH_g17sd {
				weapon = "RH_g17sd";
				count = 3;
			};
			
			class xxRH_g18 {
				weapon = "RH_g18";
				count = 3;
			};
			
			class xxRH_g19 {
				weapon = "RH_g19";
				count = 3;
			};
			
			class xxRH_g19t {
				weapon = "RH_g19t";
				count = 3;
			};
			
			class xxRH_tt33 {
				weapon = "RH_tt33";
				count = 3;
			};
			
			class xxRH_mk2 {
				weapon = "RH_mk2";
				count = 3;
			};
			
			class xxRH_p226 {
				weapon = "RH_p226";
				count = 3;
			};
			
			class xxRH_p226s {
				weapon = "RH_p226s";
				count = 3;
			};
			
			class xxRH_p38 {
				weapon = "RH_p38";
				count = 3;
			};
			
			class xxRH_ppk {
				weapon = "RH_ppk";
				count = 3;
			};
			
			class xxRH_vz61 {
				weapon = "RH_vz61";
				count = 3;
			};
			
			class xxRH_tec9 {
				weapon = "RH_tec9";
				count = 3;
			};
			
			class xxRH_muzi {
				weapon = "RH_muzi";
				count = 3;
			};
		};
		
		class TransportMagazines {
			class xxRH_7Rnd_50_AE {
				magazine = "RH_7Rnd_50_AE";
				count = 25;
			};
			
			class xxRH_6Rnd_44_Mag {
				magazine = "RH_6Rnd_44_Mag";
				count = 25;
			};
			
			class xxRH_6Rnd_357_Mag {
				magazine = "RH_6Rnd_357_Mag";
				count = 25;
			};
			
			class xxRH_8Rnd_9x19_Mk {
				magazine = "RH_8Rnd_9x19_Mk";
				count = 25;
			};
			
			class xxRH_8Rnd_9x19_Mksd {
				magazine = "RH_8Rnd_9x19_Mksd";
				count = 25;
			};
			
			class xxRH_8Rnd_762_tt33 {
				magazine = "RH_8Rnd_762_tt33";
				count = 25;
			};
			
			class xxRH_10Rnd_22LR_mk2 {
				magazine = "RH_10Rnd_22LR_mk2";
				count = 25;
			};
			
			class xxRH_7Rnd_32cal_ppk {
				magazine = "RH_7Rnd_32cal_ppk";
				count = 25;
			};
			
			class xxRH_8Rnd_9x19_P38 {
				magazine = "RH_8Rnd_9x19_P38";
				count = 25;
			};
			
			class xxRH_13Rnd_9x19_BHP {
				magazine = "RH_13Rnd_9x19_BHP";
				count = 25;
			};
			
			class xx15Rnd_9x19_M9 {
				magazine = "15Rnd_9x19_M9";
				count = 25;
			};
			
			class xx15Rnd_9x19_M9SD {
				magazine = "15Rnd_9x19_M9SD";
				count = 25;
			};
			
			class xxRH_17Rnd_9x19_g17 {
				magazine = "RH_17Rnd_9x19_g17";
				count = 25;
			};
			
			class xxRH_17Rnd_9x19_g17SD {
				magazine = "RH_17Rnd_9x19_g17SD";
				count = 25;
			};
			
			class xxRH_19Rnd_9x19_g18 {
				magazine = "RH_19Rnd_9x19_g18";
				count = 25;
			};
			
			class xxRH_33Rnd_9x19_g18 {
				magazine = "RH_33Rnd_9x19_g18";
				count = 25;
			};
			
			class xxRH_20Rnd_9x19_M93 {
				magazine = "RH_20Rnd_9x19_M93";
				count = 25;
			};
			
			class xxRH_20Rnd_32cal_vz61 {
				magazine = "RH_20Rnd_32cal_vz61";
				count = 25;
			};
			
			class xxRH_12Rnd_45cal_usp {
				magazine = "RH_12Rnd_45cal_usp";
				count = 25;
			};
			
			class xxRH_8Rnd_45cal_m1911 {
				magazine = "RH_8Rnd_45cal_m1911";
				count = 25;
			};
			
			class xxRH_15Rnd_9x19_usp {
				magazine = "RH_15Rnd_9x19_usp";
				count = 25;
			};
			
			class xxRH_15Rnd_9x19_uspsd {
				magazine = "RH_15Rnd_9x19_uspsd";
				count = 25;
			};
			
			class xxRH_30Rnd_9x19_tec {
				magazine = "RH_30Rnd_9x19_tec";
				count = 25;
			};
			
			class xxRH_32Rnd_9x19_Muzi {
				magazine = "RH_32Rnd_9x19_Muzi";
				count = 25;
			};
		};
	};
};
