// Generated by unRap v1.06 by Kegetys

class cfgWeapons {
	class Default;	// External class reference
	class PistolCore;	// External class reference
	class Pistol;	// External class reference
	
	class RH_deagle : Pistol {
		scope = public;
		model = "\RH_de\RH_deagle.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\de.paa";
		minRange = 2;
		minRangeProbab = 0.1;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.04;
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		optics = "true";
		dexterity = 1.85;
		displayName = "Desert Eagle";
		begin1[] = {"\RH_de\sound\desert_eagle_shot.wss", 0.794328, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\de_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_7Rnd_50_AE"};
		dispersion = 0.0085;
		ffCount = 1;
		recoil = "deagleBase";
		reloadTime = 0.2;
		aiRateOfFire = 2.9;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		
		class Library {
			libTextDesc = "The Desert Eagle is a large caliber gas-operated semi-automatic pistol manufactured in Israel by IMI (Israel Military Industries) for Magnum Research, Inc.Magnum Research, based in the USA, developed and patented the original Desert Eagle design and this design was further refined by IMI. Manufacturing was moved to Saco Defense in the state of Maine from 1995 to 2000, but shifted back to Israel when Saco was acquired by General Dynamics.";
		};
	};
	
	class RH_Deagleg : RH_deagle {
		displayName = "Desert Eagle Gold";
		model = "\RH_de\RH_deagleg.p3d";
		picture = "\RH_de\inv\deg.paa";
	};
	
	class RH_Deagles : RH_deagle {
		displayName = "Desert Eagle Silver";
		model = "\RH_de\RH_deagles.p3d";
		picture = "\RH_de\inv\des.paa";
	};
	
	class RH_Deaglem : RH_deagle {
		displayName = "Desert Eagle Modern";
		model = "\RH_de\RH_deaglem.p3d";
		picture = "\RH_de\inv\dem.paa";
	};
	
	class RH_Deaglemz : RH_deagle {
		displayName = "Desert Eagle Modern Muzzle";
		model = "\RH_de\RH_deaglemz.p3d";
		picture = "\RH_de\inv\demz.paa";
	};
	
	class RH_Deaglemzb : RH_deagle {
		displayName = "Desert Eagle Modern Big Muzzle";
		model = "\RH_de\RH_deaglemzb.p3d";
		picture = "\RH_de\inv\demzb.paa";
	};
	
	class RH_anac : Pistol {
		scope = public;
		displayName = "Colt Anaconda ";
		model = "\RH_de\RH_anac.p3d";
		picture = "\RH_de\inv\anac.paa";
		modelOptics = "-";
		minRange = 2;
		minRangeProbab = 0.1;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.04;
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		optics = "true";
		dexterity = 1.85;
		begin1[] = {"\RH_de\sound\anac.wss", 0.794328, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\bullreload.wss", 0.1, 1, 20};
		magazines[] = {"RH_6Rnd_44_Mag"};
		dispersion = 0.0085;
		ffCount = 1;
		recoil = "RH_45ACP_PistolRecoil";
		reloadTime = 0.2;
		aiRateOfFire = 2.9;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
	};
	
	class RH_anacg : RH_anac {
		displayName = "Colt Anaconda Gold ";
		model = "\RH_de\RH_anacg.p3d";
		picture = "\RH_de\inv\anacg.paa";
	};
	
	class RH_bull : Pistol {
		scope = public;
		displayName = "Taurus Raging Bull";
		model = "\RH_de\RH_bull.p3d";
		picture = "\RH_de\inv\bull.paa";
		modelOptics = "-";
		minRange = 2;
		minRangeProbab = 0.1;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.04;
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		optics = "true";
		dexterity = 1.85;
		begin1[] = {"\RH_de\sound\bull.wss", 0.794328, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\bullreload.wss", 0.1, 1, 20};
		magazines[] = {"RH_6Rnd_44_Mag"};
		dispersion = 0.0085;
		ffCount = 1;
		recoil = "RH_45ACP_PistolRecoil";
		reloadTime = 0.2;
		aiRateOfFire = 2.9;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
	};
	
	class RH_python : Pistol {
		scope = public;
		displayName = "Colt Python";
		model = "\RH_de\RH_python.p3d";
		picture = "\RH_de\inv\python.paa";
		modelOptics = "-";
		minRange = 2;
		minRangeProbab = 0.1;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.04;
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		optics = "true";
		dexterity = 1.85;
		begin1[] = {"\RH_de\sound\python.wss", 0.794328, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\bullreload.wss", 0.1, 1, 20};
		magazines[] = {"RH_6Rnd_357_Mag"};
		dispersion = 0.0085;
		ffCount = 1;
		recoil = "RH_45ACP_PistolRecoil";
		reloadTime = 0.2;
		aiRateOfFire = 2.9;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
	};
	
	class RH_browninghp : Pistol {
		scope = public;
		model = "\RH_de\RH_browninghp.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\browninghp.paa";
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		minRange = 2;
		minRangeProbab = 0.2;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.2;
		optics = "true";
		displayName = "Browning HP";
		begin1[] = {"\RH_de\sound\browninghp.wss", 0.794328, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\p226_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_13Rnd_9x19_bhp"};
		dispersion = 0.011;
		ffCount = 1;
		recoil = "RH_9x19_PistolRecoil";
		aiRateOfFire = 2.0;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		
		class Library {
			libTextDesc = "The Browning Hi-Power is a single-action, 9mm semi-automatic handgun. It is based on a design by American firearms inventor John Browning, and later improved by Dieudonné Saive at Fabrique Nationale (FN) of Herstal, Belgium. Browning died in 1926, several years before the design was finalized. The Hi-Power is one of the most widely used military pistols of all time,[3] having been used by the armed forces of over 50 countries.";
		};
	};
	
	class RH_p226 : Pistol {
		scope = public;
		model = "\RH_de\RH_p226.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\p226.paa";
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		minRange = 2;
		minRangeProbab = 0.2;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.2;
		optics = "true";
		displayName = "Sig P226";
		begin1[] = {"\RH_de\sound\p226.wss", 0.794328, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\p226_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_15Rnd_9x19_usp", "RH_15Rnd_9x19_uspsd"};
		dispersion = 0.011;
		ffCount = 1;
		recoil = "RH_9x19_PistolRecoil";
		aiRateOfFire = 2.0;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		
		class Library {
			libTextDesc = "The SIG Sauer P226 is a full-sized, service-type pistol chambered for the 9x19mm Parabellum, .40 S&W, and .357 SIG. Its design is based on the SIG Sauer P220.The P226 was designed for entry into the XM9 Service Pistol Trials, which were held by the US Army in 1984 on behalf of the US armed forces to find a replacement for the M1911A1. Only the Beretta 92F and the SIG P226 satisfactorily completed the trials. According to a GAO report, Beretta was awarded the M9 contract for the 92F due to better durability during endurance testing and a lower total package price. The P226 cost less per pistol than the 92F, but SIG's package price with magazines and spare parts was higher than Beretta's. The Navy SEALs, however, chose to adopt the P226 later after a repetition of failures with some issued Beretta M9s.";
		};
	};
	
	class RH_p226s : RH_p226 {
		displayName = "Sig P226 Silver ";
		model = "\RH_de\RH_p226s.p3d";
		picture = "\RH_de\inv\p226s.paa";
	};
	
	class RH_p38 : Pistol {
		scope = public;
		model = "\RH_de\RH_p38.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\p38.paa";
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		minRange = 1;
		minRangeProbab = 0.5;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.2;
		optics = "true";
		displayName = P38;
		begin1[] = {"\RH_de\sound\p38.wss", 0.794328, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\p38_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_8Rnd_9x19_P38"};
		dispersion = 0.011;
		ffCount = 1;
		recoil = "RH_pistolBase";
		aiRateOfFire = 2.0;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		
		class Library {
			libTextDesc = "The P38 was the first locked-breech pistol to use a double-action trigger. The shooter could load a round into the chamber, use the de-cocking lever to safely lower the hammer without firing the round, and carry the weapon loaded with the hammer down. A pull of the trigger, with the hammer down, fired the first shot and the operation of the pistol ejected the fired round and reloaded a fresh round into the chamber, all features found in many modern day handguns.";
		};
	};
	
	class RH_ppk : Pistol {
		scope = public;
		model = "\RH_de\RH_ppk.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\ppk.paa";
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		minRange = 2;
		minRangeProbab = 0.2;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.04;
		optics = "true";
		displayName = PPK;
		begin1[] = {"\RH_de\sound\ppk.wss", 0.794328, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\ppk_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_7Rnd_32cal_ppk"};
		dispersion = 0.011;
		ffCount = 1;
		recoil = "RH_vz61Recoil";
		aiRateOfFire = 2.0;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		
		class Library {
			libTextDesc = "The PP and the PPK were among the world's first, successful double action semi-automatic pistols that were widely copied, but still made by Walther. The design inspired other pistols, among them the Soviet Makarov, the Hungarian FEG PA-63, and the Czech CZ50. Although it was an excellent semi-automatic pistol, it had competitors in its time. The Mauser HSC pistol and the Sauer 38H pistol (a.k.a. model H), were successful in their own rights. Sauer pistol production ended at war's end, but the refined SIG P230 and the P232, owe much to the Walther PPK.";
		};
	};
	
	class RH_mk22 : Pistol {
		scope = public;
		model = "\RH_de\RH_mk22.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\mk22.paa";
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		minRange = 2;
		minRangeProbab = 0.2;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.04;
		optics = "true";
		displayName = "Mk22";
		begin1[] = {"\RH_de\sound\mk22.wss", 0.794328, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\mk22_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_8Rnd_9x19_Mk", "RH_8Rnd_9x19_Mksd"};
		dispersion = 0.011;
		ffCount = 1;
		recoil = "RH_9x19_PistolRecoil";
		aiRateOfFire = 2.0;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		
		class Library {
			libTextDesc = "The Smith and Wesson Model 39 was developed for the US Army service pistol trials of 1949.It went on the market in 1955 and was the first of Smith Wesson's first generation semi-automatic pistols.The Model 39 was manufactured with an anodized aluminum frame with a curved backstrap and a blued carbon steel slide that carries the manual safety. The grip is of three pieces made of two walnut wood panels joined by a metal backstrap. It has a magazine release located at the rear of the trigger guard, similar to the M1911A1 it was designed to replace.";
		};
	};
	
	class RH_mk22sd : Pistol {
		scope = public;
		model = "\RH_de\RH_mk22sd.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\mk22sd.paa";
		fireLightDuration = 0.0;
		fireLightIntensity = 0.0;
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		minRange = 2;
		minRangeProbab = 0.2;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.04;
		optics = "true";
		displayName = "Mk22 sd";
		begin1[] = {"\RH_de\sound\mk22sd.wss", 0.316228, 1, 200};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\mk22_reload.wss", 0.031623, 1, 20};
		magazines[] = {"RH_8Rnd_9x19_Mksd", "RH_8Rnd_9x19_Mk"};
		dispersion = 0.011;
		ffCount = 1;
		recoil = "RH_9x19_PistolRecoil";
		aiRateOfFire = 2.0;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		
		class Library {
			libTextDesc = "The Smith and Wesson Model 39 was developed for the US Army service pistol trials of 1949,It went on the market in 1955 and was the first of Smith Wesson's first generation semi-automatic pistols,The Model 39 was manufactured with an anodized aluminum frame with a curved backstrap and a blued carbon steel slide that carries the manual safety.The grip is of three pieces made of two walnut wood panels joined by a metal backstrap.It has a magazine release located at the rear of the trigger guard, similar to the M1911A1 it was designed to replace.";
		};
	};
	
	class RH_mk22v : RH_mk22 {
		displayName = "MK22v ";
		model = "\RH_de\RH_mk22v.p3d";
		picture = "\RH_de\inv\mk22v.paa";
	};
	
	class RH_mk22vsd : RH_mk22sd {
		displayName = "Mk22vsd ";
		model = "\RH_de\RH_mk22vsd.p3d";
		picture = "\RH_de\inv\mk22vsd.paa";
	};
	
	class RH_usp : Pistol {
		scope = public;
		model = "\RH_de\RH_usp.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\usp.paa";
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		minRange = 2;
		minRangeProbab = 0.2;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.2;
		optics = "true";
		displayName = USP;
		begin1[] = {"\RH_de\sound\usp.wss", 0.794328, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\usp_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_15Rnd_9x19_usp", "RH_15Rnd_9x19_uspsd"};
		dispersion = 0.011;
		ffCount = 1;
		recoil = "RH_9x19_PistolRecoil";
		aiRateOfFire = 2.0;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		
		class Library {
			libTextDesc = "The Heckler Koch USP (Universale Selbstladepistole, or Universal Self-loading Pistol) is a semi-automatic pistol designed by the German arms manufacturer Heckler Koch.When Heckler Koch introduced the USP in 1993, it marked the first time HK chose to incorporate many traditional handgun design elements, such as elements of John Browning's M1911, in one pistol. Two principles guided its development — the first being the use of molded polymer material, and the second being the creation of a pistol paradigm.";
		};
		
		class FlashLight {
			color[] = {0.9, 0.9, 0.7, 0.9};
			ambient[] = {0.1, 0.1, 0.1, 1.0};
			position = "flash dir";
			direction = "flash";
			angle = 30;
			scale[] = {1, 1, 0.5};
			brightness = 0.1;
		};
	};
	
	class RH_uspsd : Pistol {
		scope = public;
		model = "\RH_de\RH_uspsd.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\uspsd.paa";
		fireLightDuration = 0.0;
		fireLightIntensity = 0.0;
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		minRange = 2;
		minRangeProbab = 0.2;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.04;
		optics = "true";
		displayName = "USP sd";
		begin1[] = {"\RH_de\sound\uspsd.wss", 0.316228, 1, 200};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\usp_reload.wss", 0.031623, 1, 20};
		magazines[] = {"RH_15Rnd_9x19_uspsd", "RH_15Rnd_9x19_usp"};
		dispersion = 0.0081;
		ffCount = 1;
		recoil = "RH_9x19_PistolRecoil";
		aiRateOfFire = 0.5;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		
		class Library {
			libTextDesc = "The Heckler Koch USP (Universale Selbstladepistole, or Universal Self-loading Pistol) is a semi-automatic pistol designed by the German arms manufacturer Heckler Koch.When Heckler Koch introduced the USP in 1993, it marked the first time HK chose to incorporate many traditional handgun design elements, such as elements of John Browning's M1911, in one pistol. Two principles guided its development — the first being the use of molded polymer material, and the second being the creation of a pistol paradigm.";
		};
		
		class FlashLight {
			color[] = {0.9, 0.9, 0.7, 0.9};
			ambient[] = {0.1, 0.1, 0.1, 1.0};
			position = "flash dir";
			direction = "flash";
			angle = 30;
			scale[] = {1, 1, 0.5};
			brightness = 0.1;
		};
	};
	
	class RH_uspm : Pistol {
		scope = public;
		model = "\RH_de\RH_uspm.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\uspm.paa";
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		minRange = 2;
		minRangeProbab = 0.2;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.2;
		optics = "true";
		displayName = "USP Match";
		begin1[] = {"\RH_de\sound\uspm.wss", 0.794328, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\usp_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_12Rnd_45cal_usp"};
		dispersion = 0.008;
		ffCount = 1;
		recoil = "RH_45ACP_PistolRecoil";
		aiRateOfFire = 2.0;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		
		class Library {
			libTextDesc = "The USP Match (9 mm Parabellum, .40 SW, .45 ACP) is specifically designed to appeal to target shooters. In addition to the features offered on the Expert, the Match distinguishes itself by its barrel weight, or compensator, which replaces the elongated slide found on the Expert. The compensator provides counterbalance to the weapon's recoil, greatly improving follow up target tracking. The USP Match was discontinued in 2001.";
		};
	};
	
	class RH_m1911 : Pistol {
		scope = public;
		model = "\RH_de\RH_m1911.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\colt.paa";
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		minRange = 2;
		minRangeProbab = 0.2;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.2;
		optics = "true";
		displayName = "Kimber M1911";
		begin1[] = {"\RH_de\sound\m1911.wss", 0.794328, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\m1911_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_8Rnd_45cal_m1911", "7Rnd_45ACP_1911"};
		dispersion = 0.0085;
		ffCount = 1;
		aiRateOfFire = 2.0;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		recoil = "RH_45ACP_PistolRecoil";
		
		class Library {
			libTextDesc = "The M1911 is a single-action, semiautomatic handgun chambered for the .45 ACP cartridge. It was designed by John M. Browning, and was the standard-issue side arm for the United States armed forces from 1911 to 1985. It was widely used in World War I, World War II, the Korean War and the Vietnam War. Its formal designation as of 1940 was Automatic Pistol, Caliber .45, M1911 for the original Model of 1911 or Automatic Pistol, Caliber .45, M1911A1 for the M1911A1, adopted in 1924. The designation changed to Pistol, Caliber .45, Automatic, M1911A1 in the Vietnam era. In total, the United States procured around 2.7 million M1911 and M1911A1 pistols during its service life. This is modern version of M1911 by Kimber manufacturer";
		};
	};
	
	class RH_m1911sd : Pistol {
		scope = public;
		model = "\RH_de\RH_m1911sd.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\coltsd.paa";
		fireLightDuration = 0.0;
		fireLightIntensity = 0.0;
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		minRange = 2;
		minRangeProbab = 0.2;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.2;
		optics = "true";
		displayName = "Kimber M1911 SD";
		begin1[] = {"\RH_de\sound\m1911sd.wss", 0.316228, 1, 200};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\m1911_reload.wss", 0.031623, 1, 20};
		magazines[] = {"RH_8Rnd_45cal_m1911", "7Rnd_45ACP_1911"};
		dispersion = 0.0075;
		ffCount = 1;
		recoil = "RH_45ACP_PistolRecoil";
		aiRateOfFire = 2.0;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		
		class Library {
			libTextDesc = "The M1911 is a single-action, semiautomatic handgun chambered for the .45 ACP cartridge. It was designed by John M. Browning, and was the standard-issue side arm for the United States armed forces from 1911 to 1985. It was widely used in World War I, World War II, the Korean War and the Vietnam War. Its formal designation as of 1940 was Automatic Pistol, Caliber .45, M1911 for the original Model of 1911 or Automatic Pistol, Caliber .45, M1911A1 for the M1911A1, adopted in 1924. The designation changed to Pistol, Caliber .45, Automatic, M1911A1 in the Vietnam era. In total, the United States procured around 2.7 million M1911 and M1911A1 pistols during its service life. This is modern version of M1911 by Kimber manufacturer";
		};
	};
	
	class RH_m1911old : Pistol {
		scope = public;
		model = "\RH_de\RH_m1911old.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\coltold.paa";
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		minRange = 2;
		minRangeProbab = 0.2;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.04;
		optics = "true";
		displayName = "M1911 old";
		begin1[] = {"\RH_de\sound\m1911old.wss", 0.794328, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\m1911_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_8Rnd_45cal_m1911", "7Rnd_45ACP_1911"};
		dispersion = 0.0085;
		ffCount = 1;
		aiRateOfFire = 2.0;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		recoil = "RH_45ACP_PistolRecoil";
		
		class Library {
			libTextDesc = "The M1911 is a single-action, semiautomatic handgun chambered for the .45 ACP cartridge. It was designed by John M. Browning, and was the standard-issue side arm for the United States armed forces from 1911 to 1985. It was widely used in World War I, World War II, the Korean War and the Vietnam War. Its formal designation as of 1940 was Automatic Pistol, Caliber .45, M1911 for the original Model of 1911 or Automatic Pistol, Caliber .45, M1911A1 for the M1911A1, adopted in 1924. The designation changed to Pistol, Caliber .45, Automatic, M1911A1 in the Vietnam era. In total, the United States procured around 2.7 million M1911 and M1911A1 pistols during its service life.";
		};
	};
	
	class RH_tt33 : Pistol {
		scope = public;
		model = "\RH_de\RH_tt33.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\tt33.paa";
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		minRange = 2;
		minRangeProbab = 0.5;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.2;
		optics = "true";
		displayName = TT33;
		begin1[] = {"\RH_de\sound\TT33.wss", 0.794328, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\tt33_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_8Rnd_762_tt33"};
		dispersion = 0.0085;
		ffCount = 1;
		aiRateOfFire = 1.5;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		recoil = "RH_762x25_PistolRecoil";
		
		class Library {
			libTextDesc = "The TT33 is a semi-automatic pistol developed by Fedor Tokarev as a service pistol for the Soviet military to replace the Nagant M1895 revolvers in use since tsarist times.The TT-33 (Tokarev-Tula) was an improved design of the TT-30 which was the first major-employed automatic pistol in the Soviet forces, but few TT-30's were built before the update in 1933. The TT-33 was widely used by Soviet troops during World War II, but did not completely replace the Nagant until that war.The TT-33 is chambered for the 7.62 x 25 mm Tokarev cartridge, which was itself based on the similar 7.63 mm Mauser cartridge used in the Mauser C96 pistol. Able to withstand tremendous abuse, large numbers of the TT-33 were produced during WWII and well into the 1950s.";
		};
	};
	
	class RH_mk2 : Pistol {
		scope = public;
		model = "\RH_de\RH_mk2.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\mk2.paa";
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		minRange = 2;
		minRangeProbab = 0.2;
		midRange = 30;
		midRangeProbab = 0.8;
		maxRange = 50;
		maxRangeProbab = 0.04;
		optics = "true";
		displayName = "Ruger Mk2";
		begin1[] = {"\RH_de\sound\Mk2.wss", 0.316228, 1, 200};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\mk2_reload.wss", 0.031623, 1, 20};
		magazines[] = {"RH_10Rnd_22LR_mk2"};
		dispersion = 0.0085;
		ffCount = 1;
		aiRateOfFire = 2.0;	// delay between shots at given distance
		aiRateOfFireDistance = 50;
		recoil = "RH_LowRecoil";
		
		class Library {
			libTextDesc = "The Ruger rimfire semiautomatic pistols are some of the most popular handguns made, with over 3 million sold. They are manufactured by Sturm, Ruger Company.The most prevalent model is the MK II, pronounced Mark Two, made from 1982 to 2005. Previous models include the Standard, Ruger's first model, made from 1949 to 1982, and the MK I Target, made from 1951 to 1982. Variations include the Target models, which have heavier barrels and adjustable sights, and the 22/45 models, which have a polymer frame with a grip-angle that matches the Colt 1911 rather than the steel frame's Luger P08-like layout. The MK II was removed from production in 2004, when it was replaced by the MK III. All Ruger rimfire pistols are chambered in .22 Long Rifle only.";
		};
	};
	
	class RH_m93r : Pistol {
		scope = public;
		model = "\RH_de\RH_m93r.p3d";
		modelOptics = "-";
		optics = true;
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		dexterity = 1.75;
		displayName = "Beretta M93R";
		picture = "\RH_de\inv\m93.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		reloadMagazineSound[] = {"\RH_de\sound\m93r_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_20Rnd_9x19_M93", "15Rnd_9x19_M9", "15Rnd_9x19_M9SD"};
		modes[] = {"Single", "Burst"};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\RH_de\Sound\m93r.wss", 0.794328, 1, 700};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			dispersion = 0.011;
			reloadTime = 0.055;
			recoil = "RH_9x19_PistolRecoil";
			recoilProne = "RH_9x19_PistolRecoil";
			ffCount = 1;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 0.5;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.1;
			midRange = 30;
			midRangeProbab = 0.7;
			maxRange = 50;
			maxRangeProbab = 0.05;
		};
		
		class Burst : Mode_Burst {
			begin1[] = {"\RH_de\Sound\m93r.wss", 0.794328, 1, 700};
			soundBegin[] = {"begin1", 1};
			autofire = false;
			soundBurst = 0;
			soundContinuous = 0;
			burst = 3;
			dispersion = 0.011;
			reloadTime = 0.055;
			recoil = "RH_Glock_Auto_Recoil";
			recoilProne = "RH_Glock_Auto_Recoil";
			ffCount = 3;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 0.055;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.6;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 20;
			maxRangeProbab = 0.2;
		};
		
		class Library {
			libTextDesc = "Beretta Model 93R is a selective-fire machine pistol. The R stands for Raffica which means burst in Italian. It was designed in the 70s and meant for police and military use, offering extra firepower in a small package. It is perfect for concealed carry purposes such as VIP protection, or for close quarters fighting such as room-to-room searches.";
		};
	};
	
	class RH_m9 : Pistol {
		scope = public;
		model = "\RH_de\RH_m9.p3d";
		modelOptics = "-";
		optics = true;
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		dexterity = 1.75;
		displayName = "Beretta M9";
		picture = "\RH_de\inv\m9.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		reloadMagazineSound[] = {"\RH_de\sound\m93r_reload.wss", 0.1, 1, 20};
		magazines[] = {"15Rnd_9x19_M9", "15Rnd_9x19_M9SD", "RH_20Rnd_9x19_M93"};
		modes[] = {"Single"};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\RH_de\Sound\m93r.wss", 0.794328, 1, 700};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			dispersion = 0.011;
			reloadTime = 0.05;
			recoil = "RH_9x19_PistolRecoil";
			recoilProne = "RH_9x19_PistolRecoil";
			ffCount = 1;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 2.0;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.5;
			midRange = 30;
			midRangeProbab = 0.7;
			maxRange = 50;
			maxRangeProbab = 0.2;
		};
		
		class Library {
			libTextDesc = "The M9 handgun, formally Pistol, Semiautomatic, 9mm, M9, is a 9mm pistol of the U.S. military adopted in the 1980s. It is essentially a mil-spec Beretta 92F, later the 92FS.";
		};
	};
	
	class RH_m9sd : Pistol {
		scope = public;
		model = "\RH_de\RH_m9sd.p3d";
		modelOptics = "-";
		optics = true;
		fireLightDuration = 0;
		fireLightIntensity = 0;
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		dexterity = 1.75;
		displayName = "Beretta M9SD";
		picture = "\RH_de\inv\m9sd.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		reloadMagazineSound[] = {"\RH_de\sound\m93r_reload.wss", 0.031623, 1, 20};
		magazines[] = {"15Rnd_9x19_M9SD", "15Rnd_9x19_M9", "RH_20Rnd_9x19_M93"};
		modes[] = {"Single"};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\RH_de\Sound\m9sd.wss", 0.316228, 1, 200};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			dispersion = 0.011;
			reloadTime = 0.05;
			recoil = "RH_9x19_PistolRecoil";
			recoilProne = "RH_9x19_PistolRecoil";
			ffCount = 1;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 0.5;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.5;
			midRange = 30;
			midRangeProbab = 0.7;
			maxRange = 50;
			maxRangeProbab = 0.2;
		};
		
		class Library {
			libTextDesc = "The M9 handgun, formally Pistol, Semiautomatic, 9mm, M9, is a 9mm pistol of the U.S. military adopted in the 1980s. It is essentially a mil-spec Beretta 92F, later the 92FS.";
		};
	};
	
	class RH_m9c : RH_m9 {
		displayName = "Beretta M9 Camo ";
		model = "\RH_de\RH_m9c.p3d";
		picture = "\RH_de\inv\m9c.paa";
	};
	
	class RH_m9csd : RH_m9sd {
		displayName = "Beretta M9SD Camo ";
		model = "\RH_de\RH_m9csd.p3d";
		picture = "\RH_de\inv\m9csd.paa";
	};
	
	class RH_g18 : Pistol {
		scope = public;
		model = "\RH_de\RH_g18.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\g18.paa";
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		optics = "true";
		displayName = "Glock 18";
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\glock_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_19Rnd_9x19_g18", "RH_33Rnd_9x19_g18", "RH_17Rnd_9x19_g17", "17Rnd_9x19_glock17"};
		modes[] = {"Single", "FullAuto"};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\RH_de\sound\glock.wss", 0.794328, 1, 700};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			dispersion = 0.011;
			reloadTime = 0.05;
			recoil = "RH_9x19_PistolRecoil";
			recoilProne = "RH_9x19_PistolRecoil";
			ffCount = 1;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 1.5;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.3;
			midRange = 30;
			midRangeProbab = 0.7;
			maxRange = 50;
			maxRangeProbab = 0.4;
		};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\RH_de\sound\glock.wss", 0.794328, 1, 700};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			multiplier = 1;
			burst = 1;
			dispersion = 0.011;
			reloadTime = 0.05;
			recoil = "RH_Glock_Auto_Recoil";
			recoilProne = "RH_Glock_Auto_Recoil";
			ffCount = 3;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			autofire = 2;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 0.001;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.7;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 20;
			maxRangeProbab = 0.2;
		};
		
		class Library {
			libTextDesc = "The Glock 18 is a handgun manufactured by Glock. It is much like a Glock 17 with a fire selector switch on its slide that enables it to fire in semi-automatic or fully automatic modes. Rotating the switch toward the bottom of the frame allows for fully automatic fire, while rotating it to the top switches the gun to semi-automatic. The Glock 18 appears identical to the Glock 17, with the addition of the fire selector. However, the internal dimensions of the main parts of the Glock 18 are slightly different from the Glock 17, and are not interchangeable. This was done by Glock so that the Glock 17 could not be considered a semi-automatic version of the Glock 18.";
		};
	};
	
	class RH_g17 : Pistol {
		scope = public;
		model = "\RH_de\RH_g17.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\g17.paa";
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		optics = "true";
		displayName = "Glock 17";
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\glock_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_17Rnd_9x19_g17", "17Rnd_9x19_glock17", "RH_19Rnd_9x19_g18", "RH_33Rnd_9x19_g18"};
		modes[] = {"Single"};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\RH_de\sound\glock.wss", 0.794328, 1, 700};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			dispersion = 0.011;
			reloadTime = 0.05;
			recoil = "RH_9x19_PistolRecoil";
			recoilProne = "RH_9x19_PistolRecoil";
			ffCount = 1;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 2.0;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.5;
			midRange = 30;
			midRangeProbab = 0.7;
			maxRange = 50;
			maxRangeProbab = 0.2;
		};
		
		class Library {
			libTextDesc = "The Glock 17 is a handgun manufactured by Glock. It is much like a Glock 17 with a fire selector switch on its slide that enables it to fire in semi-automatic or fully automatic modes. Rotating the switch toward the bottom of the frame allows for fully automatic fire, while rotating it to the top switches the gun to semi-automatic. The Glock 18 appears identical to the Glock 17, with the addition of the fire selector. However, the internal dimensions of the main parts of the Glock 18 are slightly different from the Glock 17, and are not interchangeable. This was done by Glock so that the Glock 17 could not be considered a semi-automatic version of the Glock 18; rather they are two separate pistols.";
		};
	};
	
	class RH_g17sd : RH_g17 {
		scope = public;
		model = "\RH_de\RH_g17sd.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\g17sd.paa";
		fireLightDuration = 0;
		fireLightIntensity = 0;
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		optics = "true";
		displayName = "Glock 17 SD";
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\glock_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_17Rnd_9x19_g17SD", "15Rnd_9x19_M9SD", "RH_17Rnd_9x19_g17", "RH_33Rnd_9x19_g18", "17Rnd_9x19_glock17"};
		modes[] = {"Single"};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\RH_de\Sound\m9sd.wss", 0.316228, 1, 200};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			dispersion = 0.011;
			reloadTime = 0.05;
			recoil = "RH_9x19_PistolRecoil";
			recoilProne = "RH_9x19_PistolRecoil";
			ffCount = 1;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 2.0;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.5;
			midRange = 30;
			midRangeProbab = 0.7;
			maxRange = 50;
			maxRangeProbab = 0.2;
		};
		
		class Library {
			libTextDesc = "The Glock 17 is a handgun manufactured by Glock. It is much like a Glock 17 with a fire selector switch on its slide that enables it to fire in semi-automatic or fully automatic modes. Rotating the switch toward the bottom of the frame allows for fully automatic fire, while rotating it to the top switches the gun to semi-automatic. The Glock 18 appears identical to the Glock 17, with the addition of the fire selector. However, the internal dimensions of the main parts of the Glock 18 are slightly different from the Glock 17, and are not interchangeable. This was done by Glock so that the Glock 17 could not be considered a semi-automatic version of the Glock 18; rather they are two separate pistols.";
		};
	};
	
	class RH_g19 : Pistol {
		scope = public;
		model = "\RH_de\RH_g19.p3d";
		modelOptics = "-";
		picture = "\RH_de\inv\g19.paa";
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		optics = "true";
		displayName = "Glock 19";
		drySound[] = {"\ca\Weapons\Data\Sound\T33_dry_v1", 0.01, 1, 20};
		reloadMagazineSound[] = {"\RH_de\sound\glock_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_17Rnd_9x19_g17", "17Rnd_9x19_glock17", "RH_19Rnd_9x19_g18", "RH_33Rnd_9x19_g18"};
		modes[] = {"Single"};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\RH_de\sound\glock.wss", 0.794328, 1, 700};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			dispersion = 0.011;
			reloadTime = 0.05;
			recoil = "RH_9x19_PistolRecoil";
			recoilProne = "RH_9x19_PistolRecoil";
			ffCount = 1;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 2.0;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.5;
			midRange = 30;
			midRangeProbab = 0.7;
			maxRange = 50;
			maxRangeProbab = 0.2;
		};
		
		class Library {
			libTextDesc = "The Glock 17 is a handgun manufactured by Glock. It is much like a Glock 17 with a fire selector switch on its slide that enables it to fire in semi-automatic or fully automatic modes. Rotating the switch toward the bottom of the frame allows for fully automatic fire, while rotating it to the top switches the gun to semi-automatic. The Glock 18 appears identical to the Glock 17, with the addition of the fire selector. However, the internal dimensions of the main parts of the Glock 18 are slightly different from the Glock 17, and are not interchangeable. This was done by Glock so that the Glock 17 could not be considered a semi-automatic version of the Glock 18; rather they are two separate pistols.";
		};
	};
	
	class RH_g19t : RH_g19 {
		model = "\RH_de\RH_g19t.p3d";
		picture = "\RH_de\inv\g19t.paa";
		displayName = "Glock 19 Tan";
	};
	
	class RH_vz61 : Pistol {
		scope = public;
		model = "\RH_de\RH_vz61.p3d";
		modelOptics = "-";
		optics = true;
		distanceZoomMin = 56;
		distanceZoomMax = 56;
		dexterity = 1.75;
		displayName = "Vz61 Skorpion";
		picture = "\RH_de\inv\vz61.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		reloadMagazineSound[] = {"\RH_de\sound\vz61_reload.wss", 0.1, 1, 20};
		magazines[] = {"RH_20Rnd_32cal_vz61", "20Rnd_B_765x17_Ball", "10Rnd_B_765x17_Ball"};
		modes[] = {"Single", "Fullauto"};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\RH_de\Sound\vz61.wss", 1.77828, 1, 900};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			dispersion = 0.015;
			reloadTime = 0.07;
			recoil = "RH_vz61Recoil";
			recoilProne = "RH_vz61Recoil";
			ffCount = 1;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			autofire = false;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 1.5;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.4;
			midRange = 30;
			midRangeProbab = 0.7;
			maxRange = 50;
			maxRangeProbab = 0.4;
		};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\RH_de\Sound\vz61.wss", 1.77828, 1, 900};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			burst = 1;
			dispersion = 0.015;
			reloadTime = 0.07;
			recoil = "RH_vz61Recoil";
			recoilProne = "RH_vz61Recoil";
			ffCount = 1;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			autofire = 2;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 0.1;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.7;
			midRange = 20;
			midRangeProbab = 0.8;
			maxRange = 40;
			maxRangeProbab = 0.2;
		};
		
		class Library {
			libTextDesc = "The vz 61 (correctly Sa vz 61 short for samopal vzor 61 submachine gun model 1961), or Škorpion (scorpion), is a Czechoslovak submachine gun. It is designed to fire 7.65 x 17 mm ammunition, also known as .32 ACP. Variants in 9 x 17 mm (380 ACP), 9 x 18 mm Makarov, and 9 x 19 mm have also been reported.";
		};
	};
	
	class RH_tec9 : Pistol {
		scope = public;
		model = "\RH_de\RH_tec9.p3d";
		modelOptics = "-";
		optics = true;
		distanceZoomMin = 50;
		distanceZoomMax = 50;
		dexterity = 1.75;
		displayName = "Intratec TEC9";
		picture = "\RH_de\inv\tec9.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		reloadMagazineSound[] = {"\RH_de\sound\tec9_reload.wss", 0.056234, 1, 25};
		magazines[] = {"RH_30Rnd_9x19_tec"};
		modes[] = {"Single", "Fullauto"};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\RH_de\Sound\tec9.wss", 1.77828, 1, 900};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			dispersion = 0.015;
			reloadTime = 0.07;
			recoil = "RH_9x19_SMG_Recoil";
			recoilProne = "RH_9x19_SMG_Recoil";
			ffCount = 1;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			autofire = false;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 0.5;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.3;
			midRange = 30;
			midRangeProbab = 0.7;
			maxRange = 50;
			maxRangeProbab = 0.5;
		};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\RH_de\Sound\tec9.wss", 1.77828, 1, 900};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			burst = 1;
			dispersion = 0.015;
			reloadTime = 0.07;
			recoil = "RH_pistolBase_Auto";
			recoilProne = "RH_pistolBase_Auto";
			ffCount = 1;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			autofire = 2;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 0.1;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.5;
			midRange = 20;
			midRangeProbab = 0.7;
			maxRange = 40;
			maxRangeProbab = 0.2;
		};
		
		class Library {
			libTextDesc = "The Intratec TEC-9 is a blowback-operated, semi-automatic 9 mm Para caliber firearm, classified by the Bureau of Alcohol, Tobacco, and Firearms as a handgun. It is made of inexpensive molded polymer and stamped steel parts. Magazines holding 10-, 20-, 32-, 36- and 50-round capacities are available. There are three different models, all of which are commonly referred to as the TEC-9, although only one model was actually sold under that name.";
		};
	};
	
	class RH_muzi : Pistol {
		scope = public;
		model = "\RH_de\RH_muzi.p3d";
		modelOptics = "-";
		optics = true;
		distanceZoomMin = 57;
		distanceZoomMax = 57;
		dexterity = 1.75;
		displayName = "Micro Uzi";
		picture = "\RH_de\inv\muzi.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		reloadMagazineSound[] = {"\RH_de\sound\muzi_reload.wss", 0.056234, 1, 25};
		magazines[] = {"RH_32Rnd_9x19_Muzi", "30Rnd_9x19_UZI", "30Rnd_9x19_UZI_SD"};
		modes[] = {"Single", "Fullauto"};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\RH_de\Sound\muzi.wss", 1.77828, 1, 900};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			dispersion = 0.011;
			reloadTime = 0.048;
			recoil = "RH_9x19_SMG_Recoil";
			recoilProne = "RH_9x19_SMG_Recoil";
			ffCount = 1;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			autofire = false;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 2.0;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.2;
			midRange = 30;
			midRangeProbab = 0.7;
			maxRange = 50;
			maxRangeProbab = 0.2;
		};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\RH_de\Sound\muzi.wss", 1.77828, 1, 900};
			soundBegin[] = {"begin1", 1};
			soundBurst = 1;
			soundContinuous = 0;
			multiplier = 1;
			burst = 1;
			dispersion = 0.011;
			reloadTime = 0.048;
			recoil = "RH_pistolBase_Auto";
			recoilProne = "RH_pistolBase_Auto";
			ffCount = 1;
			ffMagnitude = 0.5;
			ffFrequency = 11;
			autofire = 2;
			flash = "gunfire";
			flashSize = 0.1;
			useAction = false;
			useActionTitle = "";
			showToPlayer = true;
			aiRateOfFire = 0.05;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 2;
			minRangeProbab = 0.7;
			midRange = 20;
			midRangeProbab = 0.7;
			maxRange = 40;
			maxRangeProbab = 0.2;
		};
		
		class Library {
			libTextDesc = "Micro Uzi, At only 250 mm (9.84 inches) in length, it is slightly larger than a standard pistol and is about as small as the original Uzi design could be made. It fires from a closed bolt position and has a side-folding stock similar to the one on the Mini Uzi. The forward handgrip is completely eliminated. First introduced in 1986, the Micro Uzi weighs 2.2 kilograms less than the Uzi when unloaded and fires at a rate of 1250 rpm, which can unload the 20 round magazine in 0.96 seconds.";
		};
	};
};
