// config.bin - 13:28:16 06/17/17, generated in 0.22 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

#include "CfgPatches.hpp"
#include "CfgAddons.hpp"
#include "cfgRecoils.hpp"
#include "CfgAmmo.hpp"
#include "CfgMagazines.hpp"
class Mode_SemiAuto;	// External class reference
class Mode_Burst;	// External class reference
class Mode_FullAuto;	// External class reference
#include "cfgWeapons.hpp"
#include "CfgVehicles.hpp"
