// Generated by unRap v1.06 by Kegetys

class CfgMissions {
	class Missions {
		class FHQREM_Missions {
			displayName = "FHQ Remington Pack";
			overview = "fhq_remington\missions\overview.paa";
			
			class SP_Showcase {
				directory = "fhq_remington\missions\fhq_remington_showcase.Takistan";
			};
			
			class SP_Pinacle01 {
				directory = "fhq_remington\missions\fhq_remington_pmc1.Woodland_ACR";
			};
		};
	};
	
	class MPMissions {
		class MP_Pinacle01 {
			directory = "fhq_remington\missions\fhq_remington_pmc1.Woodland_ACR";
		};
	};
};
