// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class FHQ_Remington {
		units[] = {"FHQ_ACR_Ammobox"};
		weapons[] = {};
		requiredVersion = 1;
		requiredAddons[] = {"CAData", "CAWeapons", "FHQ_Remington_ACR", "FHQ_Remington_XM2010", "FHQ_Remington_MSR", "FHQ_Remington_RSASS", "FHQ_Remington_ammo"};
		version = 2012-12-28;
	};
};
