// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class USBasicAmmunitionBox_EP1;	// External class reference
	
	class FHQ_ACR_Ammobox : USBasicAmmunitionBox_EP1 {
		vehicleClass = "Ammo";
		scope = public;
		displayName = "Remington Supply Crate";
		
		class TransportMagazines {
			class _xx_FHQ_rem_20Rnd_762x51_PMAG_NT {
				magazine = "FHQ_rem_20Rnd_762x51_PMAG_NT";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_762x51_PMAG_NT_SD {
				magazine = "FHQ_rem_20Rnd_762x51_PMAG_NT_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_762x51_PMAG_T {
				magazine = "FHQ_rem_20Rnd_762x51_PMAG_T";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_762x51_PMAG_T_SD {
				magazine = "FHQ_rem_20Rnd_762x51_PMAG_T_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_762x51_PMAG_TS {
				magazine = "FHQ_rem_20Rnd_762x51_PMAG_TS";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_762x51_PMAG_TS_SD {
				magazine = "FHQ_rem_20Rnd_762x51_PMAG_TS_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_762x51_PMAG_TD {
				magazine = "FHQ_rem_20Rnd_762x51_PMAG_TD";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_762x51_PMAG_TD_SD {
				magazine = "FHQ_rem_20Rnd_762x51_PMAG_TD_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_300Win_XM2010_NT {
				magazine = "FHQ_rem_5Rnd_300Win_XM2010_NT";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_300Win_XM2010_NT_SD {
				magazine = "FHQ_rem_5Rnd_300Win_XM2010_NT_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_300Win_XM2010_T {
				magazine = "FHQ_rem_5Rnd_300Win_XM2010_T";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_300Win_XM2010_T_SD {
				magazine = "FHQ_rem_5Rnd_300Win_XM2010_T_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_300Win_XM2010_TS {
				magazine = "FHQ_rem_5Rnd_300Win_XM2010_TS";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_300Win_XM2010_TS_SD {
				magazine = "FHQ_rem_5Rnd_300Win_XM2010_TS_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_300Win_XM2010_TD {
				magazine = "FHQ_rem_5Rnd_300Win_XM2010_TD";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_300Win_XM2010_TD_SD {
				magazine = "FHQ_rem_5Rnd_300Win_XM2010_TD_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_338Lapua_MSR_NT {
				magazine = "FHQ_rem_5Rnd_338Lapua_MSR_NT";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_338Lapua_MSR_NT_SD {
				magazine = "FHQ_rem_5Rnd_338Lapua_MSR_NT_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_338Lapua_MSR_T {
				magazine = "FHQ_rem_5Rnd_338Lapua_MSR_T";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_338Lapua_MSR_T_SD {
				magazine = "FHQ_rem_5Rnd_338Lapua_MSR_T_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_338Lapua_MSR_TS {
				magazine = "FHQ_rem_5Rnd_338Lapua_MSR_TS";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_338Lapua_MSR_TS_SD {
				magazine = "FHQ_rem_5Rnd_338Lapua_MSR_TS_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_338Lapua_MSR_TD {
				magazine = "FHQ_rem_5Rnd_338Lapua_MSR_TD";
				count = 30;
			};
			
			class _xx_FHQ_rem_5Rnd_338Lapua_MSR_TD_SD {
				magazine = "FHQ_rem_5Rnd_338Lapua_MSR_TD_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_7Rnd_338Lapua_MSR_NT {
				magazine = "FHQ_rem_7Rnd_338Lapua_MSR_NT";
				count = 30;
			};
			
			class _xx_FHQ_rem_7Rnd_338Lapua_MSR_NT_SD {
				magazine = "FHQ_rem_7Rnd_338Lapua_MSR_NT_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_7Rnd_338Lapua_MSR_T {
				magazine = "FHQ_rem_7Rnd_338Lapua_MSR_T";
				count = 30;
			};
			
			class _xx_FHQ_rem_7Rnd_338Lapua_MSR_T_SD {
				magazine = "FHQ_rem_7Rnd_338Lapua_MSR_T_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_7Rnd_338Lapua_MSR_TS {
				magazine = "FHQ_rem_7Rnd_338Lapua_MSR_TS";
				count = 30;
			};
			
			class _xx_FHQ_rem_7Rnd_338Lapua_MSR_TS_SD {
				magazine = "FHQ_rem_7Rnd_338Lapua_MSR_TS_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_7Rnd_338Lapua_MSR_TD {
				magazine = "FHQ_rem_7Rnd_338Lapua_MSR_TD";
				count = 30;
			};
			
			class _xx_FHQ_rem_7Rnd_338Lapua_MSR_TD_SD {
				magazine = "FHQ_rem_7Rnd_338Lapua_MSR_TD_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_10Rnd_338Lapua_MSR_NT {
				magazine = "FHQ_rem_10Rnd_338Lapua_MSR_NT";
				count = 30;
			};
			
			class _xx_FHQ_rem_10Rnd_338Lapua_MSR_NT_SD {
				magazine = "FHQ_rem_10Rnd_338Lapua_MSR_NT_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_10Rnd_338Lapua_MSR_T {
				magazine = "FHQ_rem_10Rnd_338Lapua_MSR_T";
				count = 30;
			};
			
			class _xx_FHQ_rem_10Rnd_338Lapua_MSR_T_SD {
				magazine = "FHQ_rem_10Rnd_338Lapua_MSR_T_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_10Rnd_338Lapua_MSR_TS {
				magazine = "FHQ_rem_10Rnd_338Lapua_MSR_TS";
				count = 30;
			};
			
			class _xx_FHQ_rem_10Rnd_338Lapua_MSR_TS_SD {
				magazine = "FHQ_rem_10Rnd_338Lapua_MSR_TS_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_10Rnd_338Lapua_MSR_TD {
				magazine = "FHQ_rem_10Rnd_338Lapua_MSR_TD";
				count = 30;
			};
			
			class _xx_FHQ_rem_10Rnd_338Lapua_MSR_TD_SD {
				magazine = "FHQ_rem_10Rnd_338Lapua_MSR_TD_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_30Rnd_680x43_ACR {
				magazine = "FHQ_rem_30Rnd_680x43_ACR";
				count = 30;
			};
			
			class _xx_FHQ_rem_30Rnd_680x43_ACR_T {
				magazine = "FHQ_rem_30Rnd_680x43_ACR_T";
				count = 30;
			};
			
			class _xx_FHQ_rem_30Rnd_680x43_ACR_TS {
				magazine = "FHQ_rem_30Rnd_680x43_ACR_TS";
				count = 30;
			};
			
			class _xx_FHQ_rem_30Rnd_680x43_ACR_TD {
				magazine = "FHQ_rem_30Rnd_680x43_ACR_TD";
				count = 30;
			};
			
			class _xx_FHQ_rem_30Rnd_680x43_ACR_SD {
				magazine = "FHQ_rem_30Rnd_680x43_ACR_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_30Rnd_680x43_ACR_T_SD {
				magazine = "FHQ_rem_30Rnd_680x43_ACR_T_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_30Rnd_680x43_ACR_TS_SD {
				magazine = "FHQ_rem_30Rnd_680x43_ACR_TS_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_30Rnd_680x43_ACR_TD_SD {
				magazine = "FHQ_rem_30Rnd_680x43_ACR_TD_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_680x43_ACR {
				magazine = "FHQ_rem_20Rnd_680x43_ACR";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_680x43_ACR_T {
				magazine = "FHQ_rem_20Rnd_680x43_ACR_T";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_680x43_ACR_TS {
				magazine = "FHQ_rem_20Rnd_680x43_ACR_TS";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_680x43_ACR_TD {
				magazine = "FHQ_rem_20Rnd_680x43_ACR_TD";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_680x43_ACR_SD {
				magazine = "FHQ_rem_20Rnd_680x43_ACR_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_680x43_ACR_T_SD {
				magazine = "FHQ_rem_20Rnd_680x43_ACR_T_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_680x43_ACR_TS_SD {
				magazine = "FHQ_rem_20Rnd_680x43_ACR_TS_SD";
				count = 30;
			};
			
			class _xx_FHQ_rem_20Rnd_680x43_ACR_TD_SD {
				magazine = "FHQ_rem_20Rnd_680x43_ACR_TD_SD";
				count = 30;
			};
			
			class _xx_FlareWhite_M203 {
				magazine = "FlareWhite_M203";
				count = 30;
			};
			
			class _xx_FlareGreen_M203 {
				magazine = "FlareGreen_M203";
				count = 30;
			};
			
			class _xx_FlareRed_M203 {
				magazine = "FlareRed_M203";
				count = 30;
			};
			
			class _xx_FlareYellow_M203 {
				magazine = "FlareYellow_M203";
				count = 30;
			};
			
			class _xx_1Rnd_HE_M203 {
				magazine = "1Rnd_HE_M203";
				count = 30;
			};
			
			class _xx_1Rnd_SmokeRed_M203 {
				magazine = "1Rnd_SmokeRed_M203";
				count = 30;
			};
			
			class _xx_1Rnd_SmokeGreen_M203 {
				magazine = "1Rnd_SmokeGreen_M203";
				count = 30;
			};
			
			class _xx_1Rnd_SmokeYellow_M203 {
				magazine = "1Rnd_SmokeYellow_M203";
				count = 30;
			};
			
			class _xx_1Rnd_Smoke_M203 {
				magazine = "1Rnd_Smoke_M203";
				count = 30;
			};
		};
		
		class TransportWeapons {
			class _xx_FHQ_RSASS_TAN {
				weapon = FHQ_RSASS_TAN;
				count = 5;
			};
			
			class _xx_FHQ_RSASS_TWS_TAN {
				weapon = FHQ_RSASS_TWS_TAN;
				count = 2;
			};
			
			class _xx_FHQ_RSASS_SD_TAN {
				weapon = FHQ_RSASS_SD_TAN;
				count = 5;
			};
			
			class _xx_FHQ_RSASS_TWS_SD_TAN {
				weapon = FHQ_RSASS_TWS_SD_TAN;
				count = 2;
			};
			
			class _xx_FHQ_XM2010_DESERT {
				weapon = FHQ_XM2010_DESERT;
				count = 5;
			};
			
			class _xx_FHQ_XM2010_SD_DESERT {
				weapon = FHQ_XM2010_SD_DESERT;
				count = 2;
			};
			
			class _xx_FHQ_XM2010_NV_DESERT {
				weapon = FHQ_XM2010_NV_DESERT;
				count = 5;
			};
			
			class _xx_FHQ_XM2010_NV_SD_DESERT {
				weapon = FHQ_XM2010_NV_SD_DESERT;
				count = 2;
			};
			
			class _xx_FHQ_XM2010_TWS_DESERT {
				weapon = FHQ_XM2010_TWS_DESERT;
				count = 2;
			};
			
			class _xx_FHQ_XM2010_TWS_SD_DESERT {
				weapon = FHQ_XM2010_TWS_SD_DESERT;
				count = 2;
			};
			
			class _xx_FHQ_MSR_DESERT {
				weapon = FHQ_MSR_DESERT;
				count = 5;
			};
			
			class _xx_FHQ_MSR_NV_DESERT {
				weapon = FHQ_MSR_NV_DESERT;
				count = 5;
			};
			
			class _xx_FHQ_MSR_TWS_DESERT {
				weapon = FHQ_MSR_TWS_DESERT;
				count = 5;
			};
			
			class _xx_FHQ_MSR_SD_DESERT {
				weapon = FHQ_MSR_SD_DESERT;
				count = 2;
			};
			
			class _xx_FHQ_MSR_NV_SD_DESERT {
				weapon = FHQ_MSR_NV_SD_DESERT;
				count = 2;
			};
			
			class _xx_FHQ_MSR_TWS_SD_DESERT {
				weapon = FHQ_MSR_TWS_SD_DESERT;
				count = 2;
			};
			
			class _xx_FHQ_ACR_WDL_IRN {
				weapon = FHQ_ACR_WDL_IRN;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_IRN_F {
				weapon = FHQ_ACR_WDL_IRN_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_CCO {
				weapon = FHQ_ACR_WDL_CCO;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_CCO_F {
				weapon = FHQ_ACR_WDL_CCO_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_RCO {
				weapon = FHQ_ACR_WDL_RCO;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_RCO_F {
				weapon = FHQ_ACR_WDL_RCO_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HWS {
				weapon = FHQ_ACR_WDL_HWS;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HWS_F {
				weapon = FHQ_ACR_WDL_HWS_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_G33 {
				weapon = FHQ_ACR_WDL_G33;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_G33_F {
				weapon = FHQ_ACR_WDL_G33_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_IRN_SD {
				weapon = FHQ_ACR_WDL_IRN_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_IRN_SD_F {
				weapon = FHQ_ACR_WDL_IRN_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_CCO_SD {
				weapon = FHQ_ACR_WDL_CCO_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_CCO_SD_F {
				weapon = FHQ_ACR_WDL_CCO_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_RCO_SD {
				weapon = FHQ_ACR_WDL_RCO_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_RCO_SD_F {
				weapon = FHQ_ACR_WDL_RCO_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HWS_SD {
				weapon = FHQ_ACR_WDL_HWS_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HWS_SD_F {
				weapon = FHQ_ACR_WDL_HWS_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_G33_SD {
				weapon = FHQ_ACR_WDL_G33_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_G33_SD_F {
				weapon = FHQ_ACR_WDL_G33_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_IRN_GL {
				weapon = FHQ_ACR_WDL_IRN_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_IRN_GL_F {
				weapon = FHQ_ACR_WDL_IRN_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_CCO_GL {
				weapon = FHQ_ACR_WDL_CCO_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_CCO_GL_F {
				weapon = FHQ_ACR_WDL_CCO_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_RCO_GL {
				weapon = FHQ_ACR_WDL_RCO_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_RCO_GL_F {
				weapon = FHQ_ACR_WDL_RCO_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HWS_GL {
				weapon = FHQ_ACR_WDL_HWS_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HWS_GL_F {
				weapon = FHQ_ACR_WDL_HWS_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_G33_GL {
				weapon = FHQ_ACR_WDL_G33_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_G33_GL_F {
				weapon = FHQ_ACR_WDL_G33_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_IRN_GL_SD {
				weapon = FHQ_ACR_WDL_IRN_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_IRN_GL_SD_F {
				weapon = FHQ_ACR_WDL_IRN_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_CCO_GL_SD {
				weapon = FHQ_ACR_WDL_CCO_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_CCO_GL_SD_F {
				weapon = FHQ_ACR_WDL_CCO_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_RCO_GL_SD {
				weapon = FHQ_ACR_WDL_RCO_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_RCO_GL_SD_F {
				weapon = FHQ_ACR_WDL_RCO_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HWS_GL_SD {
				weapon = FHQ_ACR_WDL_HWS_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HWS_GL_SD_F {
				weapon = FHQ_ACR_WDL_HWS_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_G33_GL_SD {
				weapon = FHQ_ACR_WDL_G33_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_G33_GL_SD_F {
				weapon = FHQ_ACR_WDL_G33_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_IRN {
				weapon = FHQ_ACR_BLK_IRN;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_IRN_F {
				weapon = FHQ_ACR_BLK_IRN_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_CCO {
				weapon = FHQ_ACR_BLK_CCO;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_CCO_F {
				weapon = FHQ_ACR_BLK_CCO_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_RCO {
				weapon = FHQ_ACR_BLK_RCO;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_RCO_F {
				weapon = FHQ_ACR_BLK_RCO_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HWS {
				weapon = FHQ_ACR_BLK_HWS;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HWS_F {
				weapon = FHQ_ACR_BLK_HWS_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_G33 {
				weapon = FHQ_ACR_BLK_G33;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_G33_F {
				weapon = FHQ_ACR_BLK_G33_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_IRN_SD {
				weapon = FHQ_ACR_BLK_IRN_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_IRN_SD_F {
				weapon = FHQ_ACR_BLK_IRN_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_CCO_SD {
				weapon = FHQ_ACR_BLK_CCO_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_CCO_SD_F {
				weapon = FHQ_ACR_BLK_CCO_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_RCO_SD {
				weapon = FHQ_ACR_BLK_RCO_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_RCO_SD_F {
				weapon = FHQ_ACR_BLK_RCO_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HWS_SD {
				weapon = FHQ_ACR_BLK_HWS_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HWS_SD_F {
				weapon = FHQ_ACR_BLK_HWS_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_G33_SD {
				weapon = FHQ_ACR_BLK_G33_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_G33_SD_F {
				weapon = FHQ_ACR_BLK_G33_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_IRN_GL {
				weapon = FHQ_ACR_BLK_IRN_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_IRN_GL_F {
				weapon = FHQ_ACR_BLK_IRN_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_CCO_GL {
				weapon = FHQ_ACR_BLK_CCO_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_CCO_GL_F {
				weapon = FHQ_ACR_BLK_CCO_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_RCO_GL {
				weapon = FHQ_ACR_BLK_RCO_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_RCO_GL_F {
				weapon = FHQ_ACR_BLK_RCO_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HWS_GL {
				weapon = FHQ_ACR_BLK_HWS_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HWS_GL_F {
				weapon = FHQ_ACR_BLK_HWS_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_G33_GL {
				weapon = FHQ_ACR_BLK_G33_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_G33_GL_F {
				weapon = FHQ_ACR_BLK_G33_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_IRN_GL_SD {
				weapon = FHQ_ACR_BLK_IRN_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_IRN_GL_SD_F {
				weapon = FHQ_ACR_BLK_IRN_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_CCO_GL_SD {
				weapon = FHQ_ACR_BLK_CCO_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_CCO_GL_SD_F {
				weapon = FHQ_ACR_BLK_CCO_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_RCO_GL_SD {
				weapon = FHQ_ACR_BLK_RCO_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_RCO_GL_SD_F {
				weapon = FHQ_ACR_BLK_RCO_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HWS_GL_SD {
				weapon = FHQ_ACR_BLK_HWS_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HWS_GL_SD_F {
				weapon = FHQ_ACR_BLK_HWS_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_G33_GL_SD {
				weapon = FHQ_ACR_BLK_G33_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_G33_GL_SD_F {
				weapon = FHQ_ACR_BLK_G33_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_IRN {
				weapon = FHQ_ACR_TAN_IRN;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_IRN_F {
				weapon = FHQ_ACR_TAN_IRN_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_CCO {
				weapon = FHQ_ACR_TAN_CCO;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_CCO_F {
				weapon = FHQ_ACR_TAN_CCO_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_RCO {
				weapon = FHQ_ACR_TAN_RCO;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_RCO_F {
				weapon = FHQ_ACR_TAN_RCO_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HWS {
				weapon = FHQ_ACR_TAN_HWS;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HWS_F {
				weapon = FHQ_ACR_TAN_HWS_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_G33 {
				weapon = FHQ_ACR_TAN_G33;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_G33_F {
				weapon = FHQ_ACR_TAN_G33_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_IRN_SD {
				weapon = FHQ_ACR_TAN_IRN_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_IRN_SD_F {
				weapon = FHQ_ACR_TAN_IRN_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_CCO_SD {
				weapon = FHQ_ACR_TAN_CCO_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_CCO_SD_F {
				weapon = FHQ_ACR_TAN_CCO_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_RCO_SD {
				weapon = FHQ_ACR_TAN_RCO_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_RCO_SD_F {
				weapon = FHQ_ACR_TAN_RCO_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HWS_SD {
				weapon = FHQ_ACR_TAN_HWS_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HWS_SD_F {
				weapon = FHQ_ACR_TAN_HWS_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_G33_SD {
				weapon = FHQ_ACR_TAN_G33_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_G33_SD_F {
				weapon = FHQ_ACR_TAN_G33_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_IRN_GL {
				weapon = FHQ_ACR_TAN_IRN_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_IRN_GL_F {
				weapon = FHQ_ACR_TAN_IRN_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_CCO_GL {
				weapon = FHQ_ACR_TAN_CCO_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_CCO_GL_F {
				weapon = FHQ_ACR_TAN_CCO_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_RCO_GL {
				weapon = FHQ_ACR_TAN_RCO_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_RCO_GL_F {
				weapon = FHQ_ACR_TAN_RCO_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HWS_GL {
				weapon = FHQ_ACR_TAN_HWS_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HWS_GL_F {
				weapon = FHQ_ACR_TAN_HWS_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_G33_GL {
				weapon = FHQ_ACR_TAN_G33_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_G33_GL_F {
				weapon = FHQ_ACR_TAN_G33_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_IRN_GL_SD {
				weapon = FHQ_ACR_TAN_IRN_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_IRN_GL_SD_F {
				weapon = FHQ_ACR_TAN_IRN_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_CCO_GL_SD {
				weapon = FHQ_ACR_TAN_CCO_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_CCO_GL_SD_F {
				weapon = FHQ_ACR_TAN_CCO_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_RCO_GL_SD {
				weapon = FHQ_ACR_TAN_RCO_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_RCO_GL_SD_F {
				weapon = FHQ_ACR_TAN_RCO_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HWS_GL_SD {
				weapon = FHQ_ACR_TAN_HWS_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HWS_GL_SD_F {
				weapon = FHQ_ACR_TAN_HWS_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_G33_GL_SD {
				weapon = FHQ_ACR_TAN_G33_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_G33_GL_SD_F {
				weapon = FHQ_ACR_TAN_G33_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_IRN {
				weapon = FHQ_ACR_SNW_IRN;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_IRN_F {
				weapon = FHQ_ACR_SNW_IRN_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_CCO {
				weapon = FHQ_ACR_SNW_CCO;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_CCO_F {
				weapon = FHQ_ACR_SNW_CCO_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_RCO {
				weapon = FHQ_ACR_SNW_RCO;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_RCO_F {
				weapon = FHQ_ACR_SNW_RCO_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HWS {
				weapon = FHQ_ACR_SNW_HWS;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HWS_F {
				weapon = FHQ_ACR_SNW_HWS_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_G33 {
				weapon = FHQ_ACR_SNW_G33;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_G33_F {
				weapon = FHQ_ACR_SNW_G33_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_IRN_SD {
				weapon = FHQ_ACR_SNW_IRN_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_IRN_SD_F {
				weapon = FHQ_ACR_SNW_IRN_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_CCO_SD {
				weapon = FHQ_ACR_SNW_CCO_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_CCO_SD_F {
				weapon = FHQ_ACR_SNW_CCO_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_RCO_SD {
				weapon = FHQ_ACR_SNW_RCO_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_RCO_SD_F {
				weapon = FHQ_ACR_SNW_RCO_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HWS_SD {
				weapon = FHQ_ACR_SNW_HWS_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HWS_SD_F {
				weapon = FHQ_ACR_SNW_HWS_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_G33_SD {
				weapon = FHQ_ACR_SNW_G33_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_G33_SD_F {
				weapon = FHQ_ACR_SNW_G33_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_IRN_GL {
				weapon = FHQ_ACR_SNW_IRN_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_IRN_GL_F {
				weapon = FHQ_ACR_SNW_IRN_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_CCO_GL {
				weapon = FHQ_ACR_SNW_CCO_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_CCO_GL_F {
				weapon = FHQ_ACR_SNW_CCO_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_RCO_GL {
				weapon = FHQ_ACR_SNW_RCO_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_RCO_GL_F {
				weapon = FHQ_ACR_SNW_RCO_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HWS_GL {
				weapon = FHQ_ACR_SNW_HWS_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HWS_GL_F {
				weapon = FHQ_ACR_SNW_HWS_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_G33_GL {
				weapon = FHQ_ACR_SNW_G33_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_G33_GL_F {
				weapon = FHQ_ACR_SNW_G33_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_IRN_GL_SD {
				weapon = FHQ_ACR_SNW_IRN_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_IRN_GL_SD_F {
				weapon = FHQ_ACR_SNW_IRN_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_CCO_GL_SD {
				weapon = FHQ_ACR_SNW_CCO_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_CCO_GL_SD_F {
				weapon = FHQ_ACR_SNW_CCO_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_RCO_GL_SD {
				weapon = FHQ_ACR_SNW_RCO_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_RCO_GL_SD_F {
				weapon = FHQ_ACR_SNW_RCO_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HWS_GL_SD {
				weapon = FHQ_ACR_SNW_HWS_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HWS_GL_SD_F {
				weapon = FHQ_ACR_SNW_HWS_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_G33_GL_SD {
				weapon = FHQ_ACR_SNW_G33_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_G33_GL_SD_F {
				weapon = FHQ_ACR_SNW_G33_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HAMR {
				weapon = FHQ_ACR_WDL_HAMR;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HAMR_F {
				weapon = FHQ_ACR_WDL_HAMR_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HAMR_SD {
				weapon = FHQ_ACR_WDL_HAMR_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HAMR_SD_F {
				weapon = FHQ_ACR_WDL_HAMR_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HAMR_GL {
				weapon = FHQ_ACR_WDL_HAMR_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HAMR_GL_F {
				weapon = FHQ_ACR_WDL_HAMR_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HAMR_GL_SD {
				weapon = FHQ_ACR_WDL_HAMR_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_HAMR_GL_SD_F {
				weapon = FHQ_ACR_WDL_HAMR_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HAMR {
				weapon = FHQ_ACR_BLK_HAMR;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HAMR_F {
				weapon = FHQ_ACR_BLK_HAMR_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HAMR_SD {
				weapon = FHQ_ACR_BLK_HAMR_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HAMR_SD_F {
				weapon = FHQ_ACR_BLK_HAMR_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HAMR_GL {
				weapon = FHQ_ACR_BLK_HAMR_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HAMR_GL_F {
				weapon = FHQ_ACR_BLK_HAMR_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HAMR_GL_SD {
				weapon = FHQ_ACR_BLK_HAMR_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_HAMR_GL_SD_F {
				weapon = FHQ_ACR_BLK_HAMR_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HAMR {
				weapon = FHQ_ACR_TAN_HAMR;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HAMR_F {
				weapon = FHQ_ACR_TAN_HAMR_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HAMR_SD {
				weapon = FHQ_ACR_TAN_HAMR_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HAMR_SD_F {
				weapon = FHQ_ACR_TAN_HAMR_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HAMR_GL {
				weapon = FHQ_ACR_TAN_HAMR_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HAMR_GL_F {
				weapon = FHQ_ACR_TAN_HAMR_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HAMR_GL_SD {
				weapon = FHQ_ACR_TAN_HAMR_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_HAMR_GL_SD_F {
				weapon = FHQ_ACR_TAN_HAMR_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HAMR {
				weapon = FHQ_ACR_SNW_HAMR;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HAMR_F {
				weapon = FHQ_ACR_SNW_HAMR_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HAMR_SD {
				weapon = FHQ_ACR_SNW_HAMR_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HAMR_SD_F {
				weapon = FHQ_ACR_SNW_HAMR_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HAMR_GL {
				weapon = FHQ_ACR_SNW_HAMR_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HAMR_GL_F {
				weapon = FHQ_ACR_SNW_HAMR_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HAMR_GL_SD {
				weapon = FHQ_ACR_SNW_HAMR_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_HAMR_GL_SD_F {
				weapon = FHQ_ACR_SNW_HAMR_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_TWS {
				weapon = FHQ_ACR_WDL_TWS;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_TWS_F {
				weapon = FHQ_ACR_WDL_TWS_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_TWS_SD {
				weapon = FHQ_ACR_WDL_TWS_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_TWS_SD_F {
				weapon = FHQ_ACR_WDL_TWS_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_TWS_GL {
				weapon = FHQ_ACR_WDL_TWS_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_TWS_GL_F {
				weapon = FHQ_ACR_WDL_TWS_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_TWS_GL_SD {
				weapon = FHQ_ACR_WDL_TWS_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_WDL_TWS_GL_SD_F {
				weapon = FHQ_ACR_WDL_TWS_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_TWS {
				weapon = FHQ_ACR_BLK_TWS;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_TWS_F {
				weapon = FHQ_ACR_BLK_TWS_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_TWS_SD {
				weapon = FHQ_ACR_BLK_TWS_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_TWS_SD_F {
				weapon = FHQ_ACR_BLK_TWS_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_TWS_GL {
				weapon = FHQ_ACR_BLK_TWS_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_TWS_GL_F {
				weapon = FHQ_ACR_BLK_TWS_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_TWS_GL_SD {
				weapon = FHQ_ACR_BLK_TWS_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_BLK_TWS_GL_SD_F {
				weapon = FHQ_ACR_BLK_TWS_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_TWS {
				weapon = FHQ_ACR_TAN_TWS;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_TWS_F {
				weapon = FHQ_ACR_TAN_TWS_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_TWS_SD {
				weapon = FHQ_ACR_TAN_TWS_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_TWS_SD_F {
				weapon = FHQ_ACR_TAN_TWS_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_TWS_GL {
				weapon = FHQ_ACR_TAN_TWS_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_TWS_GL_F {
				weapon = FHQ_ACR_TAN_TWS_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_TWS_GL_SD {
				weapon = FHQ_ACR_TAN_TWS_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_TAN_TWS_GL_SD_F {
				weapon = FHQ_ACR_TAN_TWS_GL_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_TWS {
				weapon = FHQ_ACR_SNW_TWS;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_TWS_F {
				weapon = FHQ_ACR_SNW_TWS_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_TWS_SD {
				weapon = FHQ_ACR_SNW_TWS_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_TWS_SD_F {
				weapon = FHQ_ACR_SNW_TWS_SD_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_TWS_GL {
				weapon = FHQ_ACR_SNW_TWS_GL;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_TWS_GL_F {
				weapon = FHQ_ACR_SNW_TWS_GL_F;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_TWS_GL_SD {
				weapon = FHQ_ACR_SNW_TWS_GL_SD;
				count = 5;
			};
			
			class _xx_FHQ_ACR_SNW_TWS_GL_SD_F {
				weapon = FHQ_ACR_SNW_TWS_GL_SD_F;
				count = 5;
			};
		};
	};
};
