// config.bin - 13:05:44 06/17/17, generated in 0.11 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#include "CfgPatches.hpp"
class RscText;	// External class reference
#include "RscInGameUI.hpp"
#include "CfgVehicles.hpp"
#include "CfgMissions.hpp"
