// Generated by unRap v1.06 by Kegetys

class RscInGameUI {
	class RscIGUIText : RscText {};
	
	class RscIGUIValue : RscIGUIText {};
	
	class RscWeaponZeroingFix {
		idd = 300;
		controls[] = {"CA_ZeroingText", "CA_Zeroing"};
		
		class CA_ZeroingText : RscIGUIText {
			idc = 169;
			style = 0;
			x = "(SafeZoneW + SafeZoneX) - (1 - 0.761)";
			y = "0.095 + SafeZoneY";
			w = 0.214;
			h = 0.039;
			text = "Fixed Zero: ";
		};
		
		class CA_Zeroing : RscIGUIValue {
			idc = 168;
			style = 1;
			x = "(SafeZoneW + SafeZoneX) - (1 - 0.761)";
			y = "0.095 + SafeZoneY";
			w = 0.214;
			h = 0.039;
		};
	};
};
