// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class dayz_communityassets {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"dayz_code"};
		dayzVersion = 1.8.0.1;
	};
};
