// config.bin - 13:24:58 06/17/17, generated in 0.04 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define LockNo		0
#define LockCadet		1
#define LockYes		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define VSoft		0
#define VArmor		1
#define VAir		2

#define true	1
#define false	0

#include "CfgPatches.hpp"
#include "cfgsounds.hpp"
class Mode_SemiAuto;	// External class reference
class Mode_Burst;	// External class reference
class Mode_FullAuto;	// External class reference
class CfgWeapons;	// External class reference
#include "CfgVehicleClasses.hpp"
#include "CfgVehicles.hpp"
