// Generated by unRap v1.06 by Kegetys

class CfgEnvSounds {
	class Default {
		name = $STR_CFG_ENVSOUNDS_DEFAULT;
		sound[] = {$DEFAULT$, 0, 1};
		soundNight[] = {$DEFAULT$, 0, 1};
	};
	
	class Rain {
		name = $STR_DN_RAIN;
		sound[] = {"\SOW_Sounds\Enviromental\amb_rain_d.wss", 0.398107, 1};
		soundNight[] = {"", 0, 1};
		volume = "rain*(1-night)*(1-forest)";
	};
	
	class RainNight {
		name = "SoW_NoUse";
		sound[] = {"\SOW_Sounds\Enviromental\amb_rain_n.wss", 0.398107, 1};
		soundNight[] = {"", 0, 1};
		volume = "rain*(1-forest)*night";
	};
	
	class RainForest {
		name = "SoW_NoUse";
		sound[] = {"\SOW_Sounds\Enviromental\amb_rain_f.wss", db-10, 1};
		soundNight[] = {"", 0, 1};
		volume = "rain*forest";
	};
	
	class RainHouses {
		name = "SoW_NoUse";
		sound[] = {"\SOW_Sounds\Enviromental\amb_rain_h.wss", db-23, 1};
		soundNight[] = {"", 0, 1};
		volume = "rain*houses";
	};
	
	class WindForestHigh {
		name = $STR_DN_WIND;
		sound[] = {"\SOW_Sounds\Enviromental\amb_forest_dw.wss", 0.562341, 1};
		volume = "forest*(windy factor[0,1])*(0.1+(hills factor[0,1])*0.9)-(night*0.25)";
	};
	
	class Forest {
		name = $STR_DN_WIND;
		sound[] = {"\SOW_Sounds\Enviromental\amb_forest_d.wss", 0.562341, 1};
		volume = "forest*(1-night)";
		randSamp11[] = {"ca\sounds\Ambient\forest\forest-sfx-9bird", 0.1, 1, 30, 0.14, 5, 8, 10};
		randSamp10[] = {"ca\sounds\Ambient\forest\forest-sfx-12datel", 0.1, 30, 0.125, 10, 20, 40};
		randSamp0[] = {"ca\sounds\Ambient\forest\forest-sfx-5bird", 0.125893, 1, 30, 0.13, 4, 8, 12};
		randSamp1[] = {"ca\sounds\Ambient\forest\forest-sfx-6bird", 0.125893, 1, 30, 0.125, 4, 8, 12};
		randSamp2[] = {"ca\sounds\Ambient\forest\forest-sfx-7bird", 0.125893, 1, 30, 0.125, 4, 8, 12};
		randSamp3[] = {"ca\sounds\Ambient\forest\forest-sfx-8bird", 0.125893, 1, 30, 0.1, 4, 8, 12};
		randSamp8[] = {"ca\sounds\Ambient\forest\forest-sfx-10bird-flapping", 0.1, 1, 30, 0.04, 10, 20, 40};
		randSamp9[] = {"ca\sounds\Ambient\forest\forest-sfx-11holub-flapping", 0.1, 1, 30, 0.04, 10, 20, 40};
		randSamp4[] = {"ca\sounds\Ambient\forest\forest-sfx-1", 0.1, 1, 30, 0.025, 4, 8, 10};
		randSamp5[] = {"ca\sounds\Ambient\forest\forest-sfx-2", 0.1, 1, 30, 0.025, 4, 8, 10};
		randSamp6[] = {"ca\sounds\Ambient\forest\forest-sfx-3", 0.1, 1, 30, 0.025, 4, 8, 10};
		randSamp7[] = {"ca\sounds\Ambient\forest\forest-sfx-4", 0.1, 1, 30, 0.025, 4, 8, 10};
		random[] = {"randSamp11", "randSamp10", "randSamp0", "randSamp1", "randSamp2", "randSamp3", "randSamp8", "randSamp9", "randSamp4", "randSamp5", "randSamp6", "randSamp7"};
	};
};
