// Generated by unRap v1.06 by Kegetys

class CfgMovesBasic {
	class Default {};
	
	class HealBase : Default {};
	
	class HealBaseRfl : HealBase {};
	
	class StandBase : Default {};
	
	class DefaultDie : Default {};
	
	class ManActions {};
	class Actions;	// External class reference
	
	class Interpolations {};
	transitionsInterpolated[] = {};
	transitionsSimple[] = {};
	transitionsDisabled[] = {};
	
	class BlendAnims {};
	
	class AgonyBase : Default {};
	
	class AgonyBaseRfl : AgonyBase {};
	
	class InjuredMovedBase : Default {};
};
