// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class SOW_Sounds {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"CAAir", "CAData", "CA_Anims_Char", "CAMisc", "CAWeapons", "CAWeapons2", "CA_Modules", "CAWheeled", "CATracked", "CATracked2", "CACharacters", "CACharacters2", "CABuildings", "CABuildings2"};
	};
};
