// Generated by unRap v1.06 by Kegetys

class CfgSFX {
	class DestrHouse {
		sounds[] = {"DestrHouse1", "DestrHouse2"};
		name = "$STR_CFG_SFX_DestrHouse";
		DestrHouse1[] = {"\SOW_Sounds\Impact\expl_h_1.wss", 0, 1, 150, 1, 60, 120, 240};
		DestrHouse2[] = {"\SOW_Sounds\Impact\expl_h_2.wss", 0, 1, 150, 1, 60, 120, 240};
		empty[] = {"", 0, 0, 0, 0, 1, 5, 20};
	};
};
