// Generated by unRap v1.06 by Kegetys

class CfgSounds {
	class fly_sh_81 {
		name = "SoW_NoUse";
		sound[] = {"\SOW_Sounds\Guns\Fly\fly_sh_81.wss", 0, 1, 1000};
		titles[] = {};
	};
	
	class fly_sh_105 {
		name = "SoW_NoUse";
		sound[] = {"\SOW_Sounds\Guns\Fly\fly_sh_105.wss", 0, 1, 1000};
		titles[] = {};
	};
	
	class fly_sh_122 {
		name = "SoW_NoUse";
		sound[] = {"\SOW_Sounds\Guns\Fly\fly_sh_122.wss", 0, 1, 1000};
		titles[] = {};
	};
	
	class fly_sh_227 {
		name = "SoW_NoUse";
		sound[] = {"\SOW_Sounds\Guns\Fly\fly_sh_227.wss", 0, 1, 1000};
		titles[] = {};
	};
};
