// Generated by unRap v1.06 by Kegetys

class CfgWorlds {
	class DefaultWorld {
		class Weather {
			class Overcast {
				class Weather1;	// External class reference
				class Weather2;	// External class reference
				class Weather3;	// External class reference
				class Weather4;	// External class reference
				class Weather5;	// External class reference
			};
		};
	};
	
	class CAWorld : DefaultWorld {
		class Weather : Weather {
			class Overcast : Overcast {
				class Weather1 : Weather1 {};
				
				class Weather7 : Weather1 {};
				
				class Weather2 : Weather2 {};
				
				class Weather3 : Weather3 {};
				
				class Weather4 : Weather4 {};
				
				class Weather5 : Weather5 {};
				
				class Weather6 : Weather5 {};
			};
			
			class ThunderboltNorm {
				soundNear[] = {"\SOW_Sounds\Enviromental\amb_thunder_n_1.wss", db50, 1};
				soundFar[] = {"\SOW_Sounds\Enviromental\amb_thunder_f_2.wss", db30, 1};
			};
			
			class ThunderboltHeavy {
				soundNear[] = {"\SOW_Sounds\Enviromental\amb_thunder_n_2.wss", db40, 1};
				soundFar[] = {"\SOW_Sounds\Enviromental\amb_thunder_f_1.wss", db50, 1};
			};
		};
		
		class Rain {};
	};
};
