// Generated by unRap v1.06 by Kegetys

class cfgWeapons {
	class Default;	// External class reference
	class PistolCore;	// External class reference
	class RifleCore;	// External class reference
	class MGunCore;	// External class reference
	class LauncherCore;	// External class reference
	class GrenadeCore;	// External class reference
	class CannonCore;	// External class reference
	
	class MGun : MGunCore {};
	
	class Pistol : PistolCore {
		bullet1[] = {"ca\sounds\weapons\shells\pistols_shell_metal_04", 0, 1, 30};
		bullet2[] = {"ca\sounds\weapons\shells\pistols_shell_metal_03", 0, 1, 30};
		bullet3[] = {"ca\sounds\weapons\shells\pistols_shell_metal_02", 0, 1, 30};
		bullet4[] = {"ca\sounds\weapons\shells\pistols_shell_metal_01", 0, 1, 30};
		bullet5[] = {"ca\sounds\weapons\shells\pistols_shell_dirt_01", 0, 1, 25};
		bullet6[] = {"ca\sounds\weapons\shells\pistols_shell_dirt_02", 0, 1, 25};
		bullet7[] = {"ca\sounds\weapons\shells\pistols_shell_dirt_03", 0, 1, 25};
		bullet8[] = {"ca\sounds\weapons\shells\pistols_shell_dirt_04", 0, 1, 25};
		bullet9[] = {"ca\sounds\weapons\shells\pistols_shell_soft_01", 0, 1, 25};
		bullet10[] = {"ca\sounds\weapons\shells\pistols_shell_soft_02", 0, 1, 25};
		bullet11[] = {"ca\sounds\weapons\shells\pistols_shell_soft_03", 0, 1, 25};
		bullet12[] = {"ca\sounds\weapons\shells\pistols_shell_soft_04", 0, 1, 25};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
	};
	
	class M9 : Pistol {
		begin1[] = {"\SOW_Sounds\Guns\f_m9.wss", 0, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\SOW_Sounds\Guns\e_m9.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m9.wss", 0, 1, 20};
	};
	
	class M9SD : M9 {
		begin1[] = {"\SOW_Sounds\Guns\f_m9sd.wss", 0, 1, 50};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\SOW_Sounds\Guns\e_m9.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m9.wss", 0, 1, 20};
	};
	
	class Colt1911 : M9 {
		begin1[] = {"\SOW_Sounds\Guns\f_1911.wss", 0, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\SOW_Sounds\Guns\e_m9.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m9.wss", 0, 1, 20};
	};
	
	class Makarov : Pistol {
		begin1[] = {"\SOW_Sounds\Guns\f_makarov.wss", 0, 1, 700};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\SOW_Sounds\Guns\e_m9.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m9.wss", 0, 1, 20};
	};
	
	class MakarovSD : Makarov {
		begin1[] = {"\SOW_Sounds\Guns\f_makarovsd.wss", 0, 1, 50};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\SOW_Sounds\Guns\e_m9.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m9.wss", 0, 1, 20};
	};
	
	class GrenadeLauncher : Default {
		sound[] = {"\SOW_Sounds\Guns\f_m203.wss", 0, 1, 400};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m203.wss", 0, 1, 20};
	};
	
	class Rifle : RifleCore {
		soundContinuous = 0;
		sound[] = {""};
		drySound[] = {"\SOW_Sounds\Guns\e_m4.wss", 0, 1, 10};
		reloadSound[] = {"", 1, 1};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m4.wss", 0, 1, 20};
		bullet1[] = {"ca\sounds\weapons\shells\small_shell_metal_04", 0, 1, 15};
		bullet2[] = {"ca\sounds\weapons\shells\small_shell_metal_03", 0, 1, 15};
		bullet3[] = {"ca\sounds\weapons\shells\small_shell_metal_02", 0, 1, 15};
		bullet4[] = {"ca\sounds\weapons\shells\small_shell_metal_01", 0, 1, 15};
		bullet5[] = {"ca\sounds\weapons\shells\small_shell_dirt_07", 0, 1, 15};
		bullet6[] = {"ca\sounds\weapons\shells\small_shell_dirt_09", 0, 1, 15};
		bullet7[] = {"ca\sounds\weapons\shells\small_shell_dirt_10", 0, 1, 15};
		bullet8[] = {"ca\sounds\weapons\shells\small_shell_dirt_12", 0, 1, 15};
		bullet9[] = {"ca\sounds\weapons\shells\small_shell_soft_05", 0, 1, 15};
		bullet10[] = {"ca\sounds\weapons\shells\small_shell_soft_09", 0, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\small_shell_soft_10", 0, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\small_shell_soft_13", 0, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		
		class M203Muzzle : GrenadeLauncher {
			sound[] = {"\SOW_Sounds\Guns\f_m203.wss", 0, 1, 400};
			reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m203.wss", 0, 1, 20};
		};
	};
	
	class M16_base : Rifle {
		class Single : Mode_SemiAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_m16.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_m16.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
		
		class Burst : Mode_Burst {
			begin1[] = {"\SOW_Sounds\Guns\f_m16.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_m16.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			soundBurst = 0;
		};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_m16.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_m16.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
		
		class M203Muzzle : M203Muzzle {};
	};
	
	class M16A2 : M16_base {
		drySound[] = {"\SOW_Sounds\Guns\e_m4.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m4.wss", 0, 1, 20};
	};
	
	class M16A2GL : M16A2 {};
	
	class m16a4 : M16A2 {
		modes[] = {"Single", "Burst"};
		class Single;	// External class reference
		class Burst;	// External class reference
	};
	
	class m16a4_acg : m16a4 {
		class Single : Single {};
		
		class Burst : Burst {};
	};
	
	class M16A4_GL : m16a4 {};
	
	class M16A4_ACG_GL : M16A4_GL {
		class Single : Single {};
		
		class Burst : Burst {};
	};
	
	class M24 : Rifle {
		begin1[] = {"\SOW_Sounds\Guns\f_m24.wss", 0, 1, 1000};
		soundBegin[] = {"begin1", 1};
		soundContinuous = 0;
		drySound[] = {"\SOW_Sounds\Guns\e_mp5.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m24.wss", 0, 1, 20};
		reloadSound[] = {"\SOW_Sounds\Guns\r_m24_b.wss", 0, 1, 20};
	};
	
	class huntingrifle : M24 {
		begin1[] = {"\SOW_Sounds\Guns\f_m24.wss", 0, 1, 1000};
		soundBegin[] = {"begin1", 1};
		soundContinuous = 0;
		drySound[] = {"\SOW_Sounds\Guns\e_mp5.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m24.wss", 0, 1, 20};
		reloadSound[] = {"\SOW_Sounds\Guns\r_m24_b.wss", 0, 1, 20};
	};
	
	class DMR : Rifle {
		class Single : Mode_SemiAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_dmr.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
			drySound[] = {"\SOW_Sounds\Guns\e_m240.wss", 0, 1, 10};
			reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_svd.wss", 0, 1, 20};
		};
	};
	
	class m107 : Rifle {
		begin1[] = {"\SOW_Sounds\Guns\f_m107.wss", 0, 1, 1000};
		soundBegin[] = {"begin1", 1};
		drySound[] = {"\SOW_Sounds\Guns\e_m240.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_svd.wss", 0, 1, 20};
	};
	
	class M40A3 : M24 {};
	
	class M240 : Rifle {
		bullet1[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet2[] = {"ca\sounds\weapons\shells\big_shell_metal_03", 0, 1, 15};
		bullet3[] = {"ca\sounds\weapons\shells\big_shell_metal_02", 0, 1, 15};
		bullet4[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet5[] = {"ca\sounds\weapons\shells\big_shell_dirt_01", 0, 1, 15};
		bullet6[] = {"ca\sounds\weapons\shells\big_shell_dirt_02", 0, 1, 15};
		bullet7[] = {"ca\sounds\weapons\shells\big_shell_dirt_03", 0, 1, 15};
		bullet8[] = {"ca\sounds\weapons\shells\big_shell_dirt_04", 0, 1, 15};
		bullet9[] = {"ca\sounds\weapons\shells\big_shell_soft_01", 0, 1, 15};
		bullet10[] = {"ca\sounds\weapons\shells\big_shell_soft_02", 0, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\big_shell_soft_03", 0, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\big_shell_soft_04", 0, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		drySound[] = {"\SOW_Sounds\Guns\e_m240.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m240.wss", 0, 1, 20};
		reloadSound[] = {"\SOW_Sounds\Guns\sc_mg_b.wss", 0, 1, 20};
		
		class manual : Mode_FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_m240.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_m240.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			soundContinuous = 0;
			soundBurst = 0;
		};
		
		class close : manual {
			showToPlayer = false;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class Mk_48 : M240 {
		class manual : manual {
			begin1[] = {"\SOW_Sounds\Guns\f_m240.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_m240.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
		
		class close : close {};
		
		class short : short {};
		
		class medium : medium {};
		
		class far : far {};
	};
	
	class M249 : Rifle {
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m249.wss", 0, 1, 20};
		reloadSound[] = {"\SOW_Sounds\Guns\sc_mg_b.wss", 0, 1, 20};
		
		class manual : Mode_FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_m249.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_m249.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			soundContinuous = 0;
			soundBurst = 0;
			showToPlayer = true;
		};
		
		class close : manual {
			showToPlayer = false;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class M4A1 : M16_base {
		drySound[] = {"\SOW_Sounds\Guns\e_m4.wss", 0, 1};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m4.wss", 0, 1, 20};
		
		class Single : Single {
			begin1[] = {"\SOW_Sounds\Guns\f_m4.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_m4.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_m4.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_m4.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
	};
	
	class M4A1_Aim : M4A1 {};
	
	class M4A1_Aim_camo : M4A1_Aim {};
	
	class M4SPR : M4A1 {
		class Single : Single {};
	};
	
	class M4A1_RCO_GL : M4A1 {
		class M4_ACOG_Muzzle : M4A1 {};
		
		class M4_CQB_Muzzle : M4A1 {};
	};
	
	class M4A1_AIM_SD_camo : M4A1_Aim {
		class Single : Mode_SemiAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_m4sd.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 1};
		};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_m4sd.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class M4A1_HWS_GL_SD_Camo : M4A1_AIM_SD_camo {};
	
	class M4A1_HWS_GL : M4A1_RCO_GL {};
	
	class M4A1_HWS_GL_camo : M4A1_HWS_GL {};
	
	class MP5SD : Rifle {
		drySound[] = {"\SOW_Sounds\Guns\e_mp5.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_mp5.wss", 0, 1, 20};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_mp5sd.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 1};
		};
		
		class Burst : Mode_Burst {
			begin1[] = {"\SOW_Sounds\Guns\f_mp5sd.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			soundBurst = 0;
		};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_mp5sd.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
		};
	};
	
	class MP5A5 : MP5SD {
		class Single : Mode_SemiAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_mp5.wss", 0, 1, 700};
			soundBegin[] = {"begin1", 1};
		};
		
		class Burst : Mode_Burst {
			begin1[] = {"\SOW_Sounds\Guns\f_mp5.wss", 0, 1, 700};
			soundBegin[] = {"begin1", 1};
			soundBurst = 0;
		};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_mp5.wss", 0, 1, 700};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class M1014 : Rifle {
		class Single : Mode_SemiAuto {
			soundContinuous = 0;
			drySound[] = {"\SOW_Sounds\Guns\e_mp5.wss", 0, 1, 10};
			reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_mp5.wss", 0, 1, 20};
			begin1[] = {"\SOW_Sounds\Guns\f_m1014.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_m1014.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
	};
	
	class Saiga12K : Rifle {
		class Single : Mode_SemiAuto {
			drySound[] = {"\SOW_Sounds\Guns\e_mp5.wss", 0, 1, 10};
			reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_mp5.wss", 0, 1, 20};
			begin1[] = {"\SOW_Sounds\Guns\f_saiga.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
		};
	};
	
	class AK_BASE : Rifle {
		drySound[] = {"\SOW_Sounds\Guns\e_ak74.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_ak74.wss", 0, 1, 20};
		bullet1[] = {"ca\sounds\weapons\shells\small_shell_metal_04", 0, 1, 15};
		bullet2[] = {"ca\sounds\weapons\shells\small_shell_metal_03", 0, 1, 15};
		bullet3[] = {"ca\sounds\weapons\shells\small_shell_metal_02", 0, 1, 15};
		bullet4[] = {"ca\sounds\weapons\shells\small_shell_metal_01", 0, 1, 15};
		bullet5[] = {"ca\sounds\weapons\shells\small_shell_dirt_07", 0, 1, 15};
		bullet6[] = {"ca\sounds\weapons\shells\small_shell_dirt_09", 0, 1, 15};
		bullet7[] = {"ca\sounds\weapons\shells\small_shell_dirt_10", 0, 1, 15};
		bullet8[] = {"ca\sounds\weapons\shells\small_shell_dirt_12", 0, 1, 15};
		bullet9[] = {"ca\sounds\weapons\shells\small_shell_soft_05", 0, 1, 15};
		bullet10[] = {"ca\sounds\weapons\shells\small_shell_soft_09", 0, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\small_shell_soft_10", 0, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\small_shell_soft_13", 0, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_ak74.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
		
		class Burst : Mode_Burst {
			begin1[] = {"\SOW_Sounds\Guns\f_ak74.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
			soundBurst = 0;
			showToPlayer = false;
		};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_ak74.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
		
		class GP25Muzzle : GrenadeLauncher {
			begin1[] = {"\SOW_Sounds\Guns\f_gp25.wss", 0, 1, 400};
			soundBegin[] = {"begin1", 1};
			reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_gp25.wss", 0, 1, 20};
		};
	};
	
	class AKS_BASE : AK_BASE {
		class Single : Single {
			begin1[] = {"\SOW_Sounds\Guns\f_aks74u.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
		
		class Burst : Burst {
			begin1[] = {"\SOW_Sounds\Guns\f_aks74u.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
			soundBurst = 0;
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_aks74u.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class AK_107_BASE : AK_BASE {
		class Single : Single {
			begin1[] = {"\SOW_Sounds\Guns\f_ak107.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
		
		class Burst : Burst {
			begin1[] = {"\SOW_Sounds\Guns\f_ak107.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
			soundBurst = 0;
			showToPlayer = true;
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_ak107.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class AK_47_M : AK_BASE {
		class Single : Mode_SemiAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_ak74.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
		
		class Burst : Mode_Burst {
			begin1[] = {"\SOW_Sounds\Guns\f_ak74.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
			soundBurst = 0;
			showToPlayer = false;
		};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_ak74.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class AK_47_S : AK_47_M {};
	
	class AKS_GOLD : AK_47_S {};
	
	class AK_74 : AK_BASE {};
	
	class AK_74_GL : AK_BASE {};
	
	class AK_107_kobra : AK_107_BASE {};
	
	class AK_107_GL_kobra : AK_107_BASE {};
	
	class AK_107_GL_pso : AK_107_GL_kobra {};
	
	class AK_107_pso : AK_107_BASE {};
	
	class AKS_74_kobra : AKS_BASE {};
	
	class AKS_74_pso : AKS_BASE {};
	
	class AKS_74_U : AKS_BASE {};
	
	class AKS_74_UN_kobra : AKS_BASE {
		class Single : Single {
			begin1[] = {"\SOW_Sounds\Guns\f_aks74un.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 1};
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_aks74un.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class RPK_74 : AK_74 {
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_rpk74.wss", 0, 1, 20};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_rpk74.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
		
		class manual : Mode_FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_rpk74.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
			soundContinuous = 0;
			soundBurst = 0;
			showToPlayer = true;
		};
		
		class close : manual {
			showToPlayer = false;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_rpk74.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class bizon : Rifle {
		drySound[] = {"\SOW_Sounds\Guns\e_ak74.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_bizon.wss", 0, 1, 20};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_bizon.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_bizon.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
		
		class Burst : Mode_Burst {
			begin1[] = {"\SOW_Sounds\Guns\f_bizon.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_bizon.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			soundContinuous = 0;
			soundBurst = 0;
			showToPlayer = false;
		};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_bizon.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_bizon.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			soundContinuous = 0;
		};
	};
	
	class bizon_silenced : bizon {
		class Single : Single {
			begin1[] = {"\SOW_Sounds\Guns\f_bizonsd.wss", 0, 1, 50};
			begin2[] = {"\SOW_Sounds\Guns\f_bizonsd.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
		
		class Burst : Burst {
			begin1[] = {"\SOW_Sounds\Guns\f_bizonsd.wss", 0, 1, 50};
			begin2[] = {"\SOW_Sounds\Guns\f_bizonsd.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_bizonsd.wss", 0, 1, 50};
			begin2[] = {"\SOW_Sounds\Guns\f_bizonsd.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
	};
	
	class PK : Rifle {
		bullet1[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet2[] = {"ca\sounds\weapons\shells\big_shell_metal_03", 0, 1, 15};
		bullet3[] = {"ca\sounds\weapons\shells\big_shell_metal_02", 0, 1, 15};
		bullet4[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet5[] = {"ca\sounds\weapons\shells\big_shell_dirt_01", 0, 1, 15};
		bullet6[] = {"ca\sounds\weapons\shells\big_shell_dirt_02", 0, 1, 15};
		bullet7[] = {"ca\sounds\weapons\shells\big_shell_dirt_03", 0, 1, 15};
		bullet8[] = {"ca\sounds\weapons\shells\big_shell_dirt_04", 0, 1, 15};
		bullet9[] = {"ca\sounds\weapons\shells\big_shell_soft_01", 0, 1, 15};
		bullet10[] = {"ca\sounds\weapons\shells\big_shell_soft_02", 0, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\big_shell_soft_03", 0, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\big_shell_soft_04", 0, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_pk.wss", 0, 1, 20};
		reloadSound[] = {"\SOW_Sounds\Guns\sc_mg_b.wss", 0, 1, 20};
		
		class manual : Mode_FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_pk.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_pk.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			soundContinuous = 0;
			soundBurst = 0;
			showToPlayer = true;
		};
		
		class close : manual {
			burst = 10;
			showToPlayer = false;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class Pecheneg : PK {
		class manual : manual {};
		
		class close : close {};
		
		class short : short {};
		
		class medium : medium {};
		
		class far : far {};
	};
	
	class SVD : Rifle {
		begin1[] = {"\SOW_Sounds\Guns\f_svd.wss", 0, 1, 1000};
		soundBegin[] = {"begin1", 1};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_svd.wss", 0, 1, 20};
	};
	
	class SVD_CAMO : SVD {};
	
	class VSS_vintorez : Rifle {
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_svd.wss", 0, 1, 20};
		
		class Single : Mode_SemiAuto {
			soundContinuous = 0;
			begin1[] = {"\SOW_Sounds\Guns\f_vintorez.wss", 0, 1, 50};
			begin2[] = {"\SOW_Sounds\Guns\f_vintorez.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
		
		class Full : Mode_FullAuto {
			soundContinuous = 0;
			begin1[] = {"\SOW_Sounds\Guns\f_vintorez.wss", 0, 1, 50};
			begin2[] = {"\SOW_Sounds\Guns\f_vintorez.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
	};
	
	class ksvk : Rifle {
		begin1[] = {"\SOW_Sounds\Guns\f_ksvk.wss", 0, 1, 1000};
		soundBegin[] = {"begin1", 1};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_svd.wss", 0, 1, 20};
	};
	
	class G36C : Rifle {
		drySound[] = {"\SOW_Sounds\Guns\e_g36.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_g36.wss", 0, 1, 20};
		bullet1[] = {"ca\sounds\weapons\shells\small_shell_metal_04", 0, 1, 15};
		bullet2[] = {"ca\sounds\weapons\shells\small_shell_metal_03", 0, 1, 15};
		bullet3[] = {"ca\sounds\weapons\shells\small_shell_metal_02", 0, 1, 15};
		bullet4[] = {"ca\sounds\weapons\shells\small_shell_metal_01", 0, 1, 15};
		bullet5[] = {"ca\sounds\weapons\shells\small_shell_dirt_07", 0, 1, 15};
		bullet6[] = {"ca\sounds\weapons\shells\small_shell_dirt_09", 0, 1, 15};
		bullet7[] = {"ca\sounds\weapons\shells\small_shell_dirt_10", 0, 1, 15};
		bullet8[] = {"ca\sounds\weapons\shells\small_shell_dirt_12", 0, 1, 15};
		bullet9[] = {"ca\sounds\weapons\shells\small_shell_soft_05", 0, 1, 15};
		bullet10[] = {"ca\sounds\weapons\shells\small_shell_soft_09", 0, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\small_shell_soft_10", 0, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\small_shell_soft_13", 0, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
		
		class Burst : Mode_Burst {
			begin1[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			soundBurst = 0;
		};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			soundContinuous = 0;
		};
	};
	
	class G36_C_SD_eotech : G36C {
		class Single : Single {
			begin1[] = {"\SOW_Sounds\Guns\f_g36sd.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 1};
		};
		
		class Burst : Burst {
			begin1[] = {"\SOW_Sounds\Guns\f_g36sd.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 1};
		};
		
		class FullAuto : FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_g36sd.wss", 0, 1, 50};
			soundBegin[] = {"begin1", 1};
		};
	};
	
	class G36a : Rifle {
		drySound[] = {"\SOW_Sounds\Guns\e_g36.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_g36.wss", 0, 1, 20};
		bullet1[] = {"ca\sounds\weapons\shells\small_shell_metal_04", 0, 1, 20};
		bullet2[] = {"ca\sounds\weapons\shells\small_shell_metal_03", 0, 1, 20};
		bullet3[] = {"ca\sounds\weapons\shells\small_shell_metal_02", 0, 1, 20};
		bullet4[] = {"ca\sounds\weapons\shells\small_shell_metal_01", 0, 1, 20};
		bullet5[] = {"ca\sounds\weapons\shells\small_shell_dirt_07", 0, 1, 20};
		bullet6[] = {"ca\sounds\weapons\shells\small_shell_dirt_09", 0, 1, 20};
		bullet7[] = {"ca\sounds\weapons\shells\small_shell_dirt_10", 0, 1, 20};
		bullet8[] = {"ca\sounds\weapons\shells\small_shell_dirt_12", 0, 1, 20};
		bullet9[] = {"ca\sounds\weapons\shells\small_shell_soft_05", 0, 1, 20};
		bullet10[] = {"ca\sounds\weapons\shells\small_shell_soft_09", 0, 1, 20};
		bullet11[] = {"ca\sounds\weapons\shells\small_shell_soft_10", 0, 1, 20};
		bullet12[] = {"ca\sounds\weapons\shells\small_shell_soft_13", 0, 1, 20};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		
		class MuzzleFar : G36C {
			class Single : Mode_SemiAuto {
				begin1[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
				begin2[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
				soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			};
			
			class Burst : Mode_Burst {
				begin1[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
				begin2[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
				soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
				soundBurst = 0;
			};
			
			class FullAuto : Mode_FullAuto {
				begin1[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
				begin2[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
				soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
				soundContinuous = 0;
			};
		};
	};
	
	class G36K : G36a {
		class MuzzleFar : MuzzleFar {
			class Single : Single {};
			
			class Burst : Burst {};
			
			class FullAuto : FullAuto {};
		};
	};
	
	class MG36 : G36C {
		drySound[] = {"\SOW_Sounds\Guns\e_g36.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_g36.wss", 0, 1, 20};
		bullet1[] = {"ca\sounds\weapons\shells\small_shell_metal_04", 0, 1, 20};
		bullet2[] = {"ca\sounds\weapons\shells\small_shell_metal_03", 0, 1, 20};
		bullet3[] = {"ca\sounds\weapons\shells\small_shell_metal_02", 0, 1, 20};
		bullet4[] = {"ca\sounds\weapons\shells\small_shell_metal_01", 0, 1, 20};
		bullet5[] = {"ca\sounds\weapons\shells\small_shell_dirt_07", 0, 1, 20};
		bullet6[] = {"ca\sounds\weapons\shells\small_shell_dirt_09", 0, 1, 20};
		bullet7[] = {"ca\sounds\weapons\shells\small_shell_dirt_10", 0, 1, 20};
		bullet8[] = {"ca\sounds\weapons\shells\small_shell_dirt_12", 0, 1, 20};
		bullet9[] = {"ca\sounds\weapons\shells\small_shell_soft_05", 0, 1, 20};
		bullet10[] = {"ca\sounds\weapons\shells\small_shell_soft_09", 0, 1, 20};
		bullet11[] = {"ca\sounds\weapons\shells\small_shell_soft_10", 0, 1, 20};
		bullet12[] = {"ca\sounds\weapons\shells\small_shell_soft_13", 0, 1, 20};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			showToPlayer = true;
		};
		
		class Burst : Mode_Burst {
			begin1[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			soundBurst = 0;
		};
		
		class FullAuto : Mode_FullAuto {
			soundContinuous = 0;
			soundBurst = 0;
			showToPlayer = true;
			begin1[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_g36.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
		
		class close : FullAuto {
			showToPlayer = false;
		};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class m8_base : Rifle {
		drySound[] = {"\SOW_Sounds\Guns\e_g36.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_g36.wss", 0, 1, 20};
		bullet1[] = {"ca\sounds\weapons\shells\small_shell_metal_04", 0, 1, 30};
		bullet2[] = {"ca\sounds\weapons\shells\small_shell_metal_03", 0, 1, 30};
		bullet3[] = {"ca\sounds\weapons\shells\small_shell_metal_02", 0, 1, 30};
		bullet4[] = {"ca\sounds\weapons\shells\small_shell_metal_01", 0, 1, 30};
		bullet5[] = {"ca\sounds\weapons\shells\small_shell_dirt_07", 0, 1, 20};
		bullet6[] = {"ca\sounds\weapons\shells\small_shell_dirt_09", 0, 1, 20};
		bullet7[] = {"ca\sounds\weapons\shells\small_shell_dirt_10", 0, 1, 20};
		bullet8[] = {"ca\sounds\weapons\shells\small_shell_dirt_12", 0, 1, 20};
		bullet9[] = {"ca\sounds\weapons\shells\small_shell_soft_05", 0, 1, 20};
		bullet10[] = {"ca\sounds\weapons\shells\small_shell_soft_09", 0, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\small_shell_soft_10", 0, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\small_shell_soft_13", 0, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		
		class Single : Mode_SemiAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_xm8.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_xm8.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		};
		
		class Burst : Mode_Burst {
			begin1[] = {"\SOW_Sounds\Guns\f_xm8.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_xm8.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			soundBurst = "false";
		};
		
		class FullAuto : Mode_FullAuto {
			begin1[] = {"\SOW_Sounds\Guns\f_xm8.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_xm8.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			soundContinuous = 0;
		};
		
		class XM320Muzzle : M203Muzzle {};
	};
	
	class m8_carbine : m8_base {};
	
	class m8_carbineGL : m8_base {};
	
	class m8_compact : m8_base {};
	
	class m8_sharpshooter : m8_base {};
	
	class m8_SAW : m8_sharpshooter {
		class manual : Mode_FullAuto {
			sound[] = {"\SOW_Sounds\Guns\f_xm8.wss", 0, 1, 1000};
			soundContinuous = 0;
			soundBurst = "false";
			showToPlayer = "true";
		};
		
		class close : manual {
			showToPlayer = "false";
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class Launcher : LauncherCore {};
	
	class M136 : Launcher {
		sound[] = {"\SOW_Sounds\Guns\f_m136.wss", 0, 1, 1200};
		drySound[] = {"\SOW_Sounds\Guns\e_m136.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m136.wss", 0, 1, 20};
	};
	
	class Javelin : Launcher {
		sound[] = {"\SOW_Sounds\Guns\f_javelin.wss", 0, 1, 1200};
		drySound[] = {"\SOW_Sounds\Guns\e_m136.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m136.wss", 0, 1, 20};
	};
	
	class SMAW : Launcher {
		sound[] = {"\SOW_Sounds\Guns\f_smaw.wss", 0, 1, 1200};
		drySound[] = {"\SOW_Sounds\Guns\e_m136.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m136.wss", 0, 1, 20};
	};
	
	class Stinger : Launcher {
		sound[] = {"\SOW_Sounds\Guns\f_stinger.wss", 0, 1, 1200};
		drySound[] = {"\SOW_Sounds\Guns\e_m136.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m136.wss", 0, 1, 20};
	};
	
	class RPG7V : Launcher {
		sound[] = {"\SOW_Sounds\Guns\f_rpg7v.wss", 0, 1, 1200};
		drySound[] = {"\SOW_Sounds\Guns\e_rpg7v.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_rpg7v.wss", 0, 1, 20};
	};
	
	class RPG18 : Launcher {
		sound[] = {"\SOW_Sounds\Guns\f_rpg18.wss", 0, 1, 1200};
		drySound[] = {"\SOW_Sounds\Guns\e_rpg7v.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_rpg7v.wss", 0, 1, 20};
	};
	
	class Strela : Launcher {
		sound[] = {"\SOW_Sounds\Guns\f_strela.wss", 0, 1, 1200};
		drySound[] = {"\SOW_Sounds\Guns\e_rpg7v.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_rpg7v.wss", 0, 1, 20};
	};
	
	class Igla : Strela {};
	
	class MetisLauncher : Launcher {
		sound[] = {"\SOW_Sounds\Guns\f_metis.wss", 0, 1, 1200};
		drySound[] = {"\SOW_Sounds\Guns\e_rpg7v.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_rpg7v.wss", 0, 1, 20};
	};
	
	class Binocular : Default {};
	
	class Laserdesignator : Binocular {};
	
	class Laserdesignator_mounted : Default {};
	
	class NVGoggles : Binocular {};
	
	class Throw : GrenadeLauncher {
		class ThrowMuzzle : GrenadeLauncher {};
		
		class HandGrenadeMuzzle : ThrowMuzzle {
			sound[] = {"\SOW_Sounds\Guns\f_hg.wss", 0, 1, 20};
			drySound[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			reloadMagazineSound[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			reloadSound[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			bullet1[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_1.wss", 0, 1, 30};
			bullet2[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_2.wss", 0, 1, 30};
			bullet3[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_3.wss", 0, 1, 30};
			bullet4[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_4.wss", 0, 1, 30};
			bullet5[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_1.wss", 0, 1, 20};
			bullet6[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_2.wss", 0, 1, 20};
			bullet7[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_3.wss", 0, 1, 20};
			bullet8[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_4.wss", 0, 1, 20};
			bullet9[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_1.wss", 0, 1, 20};
			bullet10[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_2.wss", 0, 1, 15};
			bullet11[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_3.wss", 0, 1, 15};
			bullet12[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_4.wss", 0, 1, 15};
			soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		};
		
		class HandGrenade_Stone : ThrowMuzzle {
			sound[] = {"\SOW_Sounds\Guns\f_stone.wss", 0, 1, 20};
			drySound[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			reloadMagazineSound[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			reloadSound[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			bullet1[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			bullet2[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			bullet3[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			bullet4[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			bullet5[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			bullet6[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			bullet7[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			bullet8[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			bullet9[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			bullet10[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			bullet11[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			bullet12[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		};
		
		class SmokeShellMuzzle : ThrowMuzzle {
			sound[] = {"\SOW_Sounds\Guns\f_hg.wss", 0, 1, 20};
			drySound[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			reloadMagazineSound[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			reloadSound[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 1};
			bullet1[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_1.wss", 0, 1, 30};
			bullet2[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_2.wss", 0, 1, 30};
			bullet3[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_3.wss", 0, 1, 30};
			bullet4[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_4.wss", 0, 1, 30};
			bullet5[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_1.wss", 0, 1, 20};
			bullet6[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_2.wss", 0, 1, 20};
			bullet7[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_3.wss", 0, 1, 20};
			bullet8[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_4.wss", 0, 1, 20};
			bullet9[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_1.wss", 0, 1, 20};
			bullet10[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_2.wss", 0, 1, 15};
			bullet11[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_3.wss", 0, 1, 15};
			bullet12[] = {"\SOW_Sounds\Guns\Shell\sh_hg_m_4.wss", 0, 1, 15};
			soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		};
	};
	
	class HandGunBase : Rifle {};
	
	class Put : Default {
		class PutMuzzle : Default {};
		
		class TimeBombMuzzle : PutMuzzle {
			sound[] = {"\SOW_Sounds\Guns\f_c4.wss", 0, 1, 20};
		};
		
		class PipeBombMuzzle : PutMuzzle {
			sound[] = {"\SOW_Sounds\Guns\f_c4.wss", 0, 1, 20};
		};
		
		class MineMuzzle : PutMuzzle {
			sound[] = {"\SOW_Sounds\Guns\f_mine.wss", 0, 1, 20};
		};
		
		class MineEMuzzle : PutMuzzle {
			sound[] = {"\SOW_Sounds\Guns\f_mine.wss", 0, 1, 20};
		};
	};
	
	class TimeBomb : Default {};
	
	class Mine : TimeBomb {};
	
	class MineE : Mine {};
	
	class PipeBomb : Put {};
	
	class SmokeLauncher : MGun {
		sound[] = {"\SOW_Sounds\Guns\f_smoke.wss", 0, 1, 300};
	};
	
	class FlareLauncher : SmokeLauncher {};
	
	class M134 : MGun {};
	
	class M134_2 : M134 {};
	
	class TwinM134 : M134 {};
	
	class M240_veh : MGun {
		bullet1[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet2[] = {"ca\sounds\weapons\shells\big_shell_metal_03", 0, 1, 15};
		bullet3[] = {"ca\sounds\weapons\shells\big_shell_metal_02", 0, 1, 15};
		bullet4[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet5[] = {"ca\sounds\weapons\shells\big_shell_dirt_01", 0, 1, 15};
		bullet6[] = {"ca\sounds\weapons\shells\big_shell_dirt_02", 0, 1, 15};
		bullet7[] = {"ca\sounds\weapons\shells\big_shell_dirt_03", 0, 1, 15};
		bullet8[] = {"ca\sounds\weapons\shells\big_shell_dirt_04", 0, 1, 15};
		bullet9[] = {"ca\sounds\weapons\shells\big_shell_soft_01", 0, 1, 15};
		bullet10[] = {"ca\sounds\weapons\shells\big_shell_soft_02", 0, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\big_shell_soft_03", 0, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\big_shell_soft_04", 0, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		drySound[] = {"\SOW_Sounds\Guns\e_m240.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m240.wss", 0, 1, 20};
		reloadSound[] = {"\SOW_Sounds\Guns\sc_mg_b.wss", 0, 1, 20};
		
		class manual : MGun {
			begin1[] = {"\SOW_Sounds\Guns\f_m240.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_m240.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			showToPlayer = true;
		};
		
		class close : manual {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class M240_veh_2 : M240_veh {};
	
	class M240_veh_MG_Nest : M240_veh {
		class manual : manual {};
		
		class close : close {};
		
		class short : short {};
		
		class medium : medium {};
		
		class far : far {};
	};
	
	class PKT : MGun {
		bullet1[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet2[] = {"ca\sounds\weapons\shells\big_shell_metal_03", 0, 1, 15};
		bullet3[] = {"ca\sounds\weapons\shells\big_shell_metal_02", 0, 1, 15};
		bullet4[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet5[] = {"ca\sounds\weapons\shells\big_shell_dirt_01", 0, 1, 15};
		bullet6[] = {"ca\sounds\weapons\shells\big_shell_dirt_02", 0, 1, 15};
		bullet7[] = {"ca\sounds\weapons\shells\big_shell_dirt_03", 0, 1, 15};
		bullet8[] = {"ca\sounds\weapons\shells\big_shell_dirt_04", 0, 1, 15};
		bullet9[] = {"ca\sounds\weapons\shells\big_shell_soft_01", 0, 1, 15};
		bullet10[] = {"ca\sounds\weapons\shells\big_shell_soft_02", 0, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\big_shell_soft_03", 0, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\big_shell_soft_04", 0, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		drySound[] = {"\SOW_Sounds\Guns\e_m240.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_pk.wss", 0, 1, 20};
		reloadSound[] = {"\SOW_Sounds\Guns\sc_mg_b.wss", 0, 1, 20};
		
		class manual : MGun {
			begin1[] = {"\SOW_Sounds\Guns\f_pkt.wss", 0, 1, 1000};
			begin2[] = {"\SOW_Sounds\Guns\f_pkt.wss", 0, 1, 1000};
			soundBegin[] = {"begin1", 0.3, "begin2", 0.7};
			showToPlayer = true;
			soundContinuous = 0;
		};
		
		class close : manual {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class PKT_MG_Nest : PKT {
		class manual : manual {};
		
		class close : close {};
		
		class short : short {};
		
		class medium : medium {};
		
		class far : far {};
	};
	
	class PKT_veh : PKT_MG_Nest {
		class manual : manual {};
		
		class close : close {};
		
		class short : short {};
		
		class medium : medium {};
		
		class far : far {};
	};
	
	class DT_veh : PKT {
		begin1[] = {"\SOW_Sounds\Guns\f_pkt.wss", 0, 1, 1000};
		begin2[] = {"\SOW_Sounds\Guns\f_pkt.wss", 0, 1, 1000};
		soundBegin[] = {"begin1", 0.3, "begin2", 0.7};
		
		class manual : manual {};
		
		class close : close {};
		
		class short : short {};
		
		class medium : medium {};
		
		class far : far {};
	};
	
	class TwinVickers : MGun {};
	
	class M2 : MGun {
		bullet1[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet2[] = {"ca\sounds\weapons\shells\big_shell_metal_03", 0, 1, 15};
		bullet3[] = {"ca\sounds\weapons\shells\big_shell_metal_02", 0, 1, 15};
		bullet4[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet5[] = {"ca\sounds\weapons\shells\big_shell_dirt_01", 0, 1, 15};
		bullet6[] = {"ca\sounds\weapons\shells\big_shell_dirt_02", 0, 1, 15};
		bullet7[] = {"ca\sounds\weapons\shells\big_shell_dirt_03", 0, 1, 15};
		bullet8[] = {"ca\sounds\weapons\shells\big_shell_dirt_04", 0, 1, 15};
		bullet9[] = {"ca\sounds\weapons\shells\big_shell_soft_01", 0, 1, 15};
		bullet10[] = {"ca\sounds\weapons\shells\big_shell_soft_02", 0, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\big_shell_soft_03", 0, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\big_shell_soft_04", 0, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		drySound[] = {"\SOW_Sounds\Guns\e_m2.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m2.wss", 0, 1, 20};
		reloadSound[] = {"\SOW_Sounds\Guns\sc_mg_b.wss", 0, 1, 20};
		
		class manual : MGun {
			begin1[] = {"\SOW_Sounds\Guns\f_m2.wss", 0, 1, 1200};
			begin2[] = {"\SOW_Sounds\Guns\f_m2.wss", 0, 1, 1200};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			showToPlayer = true;
		};
		
		class close : manual {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class M3P : M2 {
		class manual : manual {};
		
		class close : close {};
		
		class short : short {};
		
		class medium : medium {};
		
		class far : far {};
	};
	
	class DSHKM : MGun {
		bullet1[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet2[] = {"ca\sounds\weapons\shells\big_shell_metal_03", 0, 1, 15};
		bullet3[] = {"ca\sounds\weapons\shells\big_shell_metal_02", 0, 1, 15};
		bullet4[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet5[] = {"ca\sounds\weapons\shells\big_shell_dirt_01", 0, 1, 15};
		bullet6[] = {"ca\sounds\weapons\shells\big_shell_dirt_02", 0, 1, 15};
		bullet7[] = {"ca\sounds\weapons\shells\big_shell_dirt_03", 0, 1, 15};
		bullet8[] = {"ca\sounds\weapons\shells\big_shell_dirt_04", 0, 1, 15};
		bullet9[] = {"ca\sounds\weapons\shells\big_shell_soft_01", 0, 1, 15};
		bullet10[] = {"ca\sounds\weapons\shells\big_shell_soft_02", 0, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\big_shell_soft_03", 0, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\big_shell_soft_04", 0, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		drySound[] = {"\SOW_Sounds\Guns\e_m2.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m2.wss", 0, 1, 20};
		reloadSound[] = {"\SOW_Sounds\Guns\sc_mg_b.wss", 0, 1, 20};
		
		class manual : MGun {
			sound[] = {"\SOW_Sounds\Guns\f_dshkm.wss", 0, 1, 1200};
			showToPlayer = true;
		};
		
		class close : manual {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class KORD : MGun {
		bullet1[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet2[] = {"ca\sounds\weapons\shells\big_shell_metal_03", 0, 1, 15};
		bullet3[] = {"ca\sounds\weapons\shells\big_shell_metal_02", 0, 1, 15};
		bullet4[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet5[] = {"ca\sounds\weapons\shells\big_shell_dirt_01", 0, 1, 15};
		bullet6[] = {"ca\sounds\weapons\shells\big_shell_dirt_02", 0, 1, 15};
		bullet7[] = {"ca\sounds\weapons\shells\big_shell_dirt_03", 0, 1, 15};
		bullet8[] = {"ca\sounds\weapons\shells\big_shell_dirt_04", 0, 1, 15};
		bullet9[] = {"ca\sounds\weapons\shells\big_shell_soft_01", 0, 1, 15};
		bullet10[] = {"ca\sounds\weapons\shells\big_shell_soft_02", 0, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\big_shell_soft_03", 0, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\big_shell_soft_04", 0, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		drySound[] = {"\SOW_Sounds\Guns\e_m2.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m2.wss", 0, 1, 20};
		reloadSound[] = {"\SOW_Sounds\Guns\sc_mg_b.wss", 0, 1, 20};
		
		class manual : MGun {
			sound[] = {"\SOW_Sounds\Guns\f_kord.wss", 0, 1, 1200};
			showToPlayer = true;
		};
		
		class close : manual {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class KPVT : MGun {
		bullet1[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet2[] = {"ca\sounds\weapons\shells\big_shell_metal_03", 0, 1, 15};
		bullet3[] = {"ca\sounds\weapons\shells\big_shell_metal_02", 0, 1, 15};
		bullet4[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet5[] = {"ca\sounds\weapons\shells\big_shell_dirt_01", 0, 1, 15};
		bullet6[] = {"ca\sounds\weapons\shells\big_shell_dirt_02", 0, 1, 15};
		bullet7[] = {"ca\sounds\weapons\shells\big_shell_dirt_03", 0, 1, 15};
		bullet8[] = {"ca\sounds\weapons\shells\big_shell_dirt_04", 0, 1, 15};
		bullet9[] = {"ca\sounds\weapons\shells\big_shell_soft_01", 0, 1, 15};
		bullet10[] = {"ca\sounds\weapons\shells\big_shell_soft_02", 0, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\big_shell_soft_03", 0, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\big_shell_soft_04", 0, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		drySound[] = {"\SOW_Sounds\Guns\e_m2.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m2.wss", 0, 1, 20};
		reloadSound[] = {"\SOW_Sounds\Guns\sc_mg_b.wss", 0, 1, 20};
		
		class manual : MGun {
			begin1[] = {"\SOW_Sounds\Guns\f_kpvt.wss", 0, 1, 1200};
			begin2[] = {"\SOW_Sounds\Guns\f_kpvt.wss", 0, 1, 1200};
			soundBegin[] = {"begin1", 0.3, "begin2", 0.7};
			showToPlayer = true;
		};
		
		class close : manual {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class M168 : CannonCore {
		class manual : CannonCore {
			sound[] = {"\Ca\sounds\Weapons\cannon\m197", db20, 1, 1200};
			showToPlayer = true;
		};
		
		class close : manual {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class M197 : CannonCore {
		class manual : CannonCore {
			sound[] = {"\SOW_Sounds\Guns\f_m197.wss", 0, 1, 1200};
			showToPlayer = true;
		};
		
		class close : manual {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class AZP85 : CannonCore {
		bullet1[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet2[] = {"ca\sounds\weapons\shells\big_shell_metal_03", 0, 1, 15};
		bullet3[] = {"ca\sounds\weapons\shells\big_shell_metal_02", 0, 1, 15};
		bullet4[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet5[] = {"ca\sounds\weapons\shells\big_shell_dirt_01", 0, 1, 15};
		bullet6[] = {"ca\sounds\weapons\shells\big_shell_dirt_02", 0, 1, 15};
		bullet7[] = {"ca\sounds\weapons\shells\big_shell_dirt_03", 0, 1, 15};
		bullet8[] = {"ca\sounds\weapons\shells\big_shell_dirt_04", 0, 1, 15};
		bullet9[] = {"ca\sounds\weapons\shells\big_shell_soft_01", 0, 1, 15};
		bullet10[] = {"ca\sounds\weapons\shells\big_shell_soft_02", 0, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\big_shell_soft_03", 0, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\big_shell_soft_04", 0, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		
		class manual : CannonCore {
			sound[] = {"\SOW_Sounds\Guns\f_azp85_1.wss", 0, 1, 1200};
			soundContinuous = 0;
			showToPlayer = false;
			soundBurst = 0;
			autoFire = true;
		};
		
		class close : manual {
			sound[] = {"\SOW_Sounds\Guns\f_azp85_2.wss", 0, 1, 1200};
			showToPlayer = true;
			soundBurst = 1;
			autoFire = false;
		};
		
		class short : close {
			showToPlayer = false;
		};
		
		class medium : close {
			sound[] = {"\SOW_Sounds\Guns\f_azp85_3.wss", 0, 1, 1200};
			showToPlayer = false;
		};
		
		class far : close {
			sound[] = {"\SOW_Sounds\Guns\f_azp85_4.wss", 0, 1, 1200};
			showToPlayer = false;
		};
	};
	
	class 2A14 : CannonCore {
		bullet1[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet2[] = {"ca\sounds\weapons\shells\big_shell_metal_03", 0, 1, 15};
		bullet3[] = {"ca\sounds\weapons\shells\big_shell_metal_02", 0, 1, 15};
		bullet4[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0, 1, 15};
		bullet5[] = {"ca\sounds\weapons\shells\big_shell_dirt_01", 0, 1, 15};
		bullet6[] = {"ca\sounds\weapons\shells\big_shell_dirt_02", 0, 1, 15};
		bullet7[] = {"ca\sounds\weapons\shells\big_shell_dirt_03", 0, 1, 15};
		bullet8[] = {"ca\sounds\weapons\shells\big_shell_dirt_04", 0, 1, 15};
		bullet9[] = {"ca\sounds\weapons\shells\big_shell_soft_01", 0, 1, 15};
		bullet10[] = {"ca\sounds\weapons\shells\big_shell_soft_02", 0, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\big_shell_soft_03", 0, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\big_shell_soft_04", 0, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		
		class manual : CannonCore {
			sound[] = {"\Ca\sounds\Weapons\cannon\2A38_4pcs_fast", db20, 1, 1400};
			soundContinuous = 0;
			showToPlayer = false;
			soundBurst = 0;
			autoFire = true;
		};
		
		class close : manual {
			sound[] = {"\SOW_Sounds\Guns\f_sergei.wss", 0, 1, 1200};
			showToPlayer = true;
			soundBurst = 1;
			autoFire = false;
		};
		
		class short : close {
			showToPlayer = false;
		};
		
		class medium : close {
			showToPlayer = false;
		};
		
		class far : close {
			showToPlayer = false;
		};
	};
	
	class 2A38M : CannonCore {
		bullet1[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 10000, 1, 25};
		bullet2[] = {"ca\sounds\weapons\shells\big_shell_metal_03", 10000, 1, 25};
		bullet3[] = {"ca\sounds\weapons\shells\big_shell_metal_02", 10000, 1, 25};
		bullet4[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 10000, 1, 25};
		bullet5[] = {"ca\sounds\weapons\shells\big_shell_dirt_01", 10000, 1, 25};
		bullet6[] = {"ca\sounds\weapons\shells\big_shell_dirt_02", 10000, 1, 25};
		bullet7[] = {"ca\sounds\weapons\shells\big_shell_dirt_03", 10000, 1, 25};
		bullet8[] = {"ca\sounds\weapons\shells\big_shell_dirt_04", 10000, 1, 25};
		bullet9[] = {"ca\sounds\weapons\shells\big_shell_soft_01", 10000, 1, 25};
		bullet10[] = {"ca\sounds\weapons\shells\big_shell_soft_02", 10000, 1, 25};
		bullet11[] = {"ca\sounds\weapons\shells\big_shell_soft_03", 10000, 1, 25};
		bullet12[] = {"ca\sounds\weapons\shells\big_shell_soft_04", 10000, 1, 25};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		
		class manual : CannonCore {
			sound[] = {"\SOW_Sounds\Guns\f_2a38m_1.wss", 0, 1, 1200};
			soundContinuous = 0;
			showToPlayer = false;
			soundBurst = 0;
			autoFire = true;
		};
		
		class close : manual {
			sound[] = {"\SOW_Sounds\Guns\f_2a38m_2.wss", 0, 1, 1200};
			showToPlayer = true;
			soundBurst = 1;
			autoFire = false;
		};
		
		class short : close {
			showToPlayer = false;
		};
		
		class medium : close {
			sound[] = {"\SOW_Sounds\Guns\f_2a38m_3.wss", 0, 1, 1200};
			showToPlayer = false;
		};
		
		class far : close {
			sound[] = {"\SOW_Sounds\Guns\f_2a38m_4.wss", 0, 1, 1200};
			showToPlayer = false;
		};
	};
	
	class GAU8 : CannonCore {
		class manual : CannonCore {
			sound[] = {"\Ca\sounds\Weapons\cannon\a10vulcanVII", 0, 1, 1100};
			soundContinuous = 0;
			showToPlayer = false;
			soundBurst = 0;
			autoFire = true;
		};
		
		class close : manual {
			sound[] = {"\SOW_Sounds\Guns\f_gau8.wss", 0, 1, 3000};
			showToPlayer = true;
			soundBurst = 1;
			autoFire = false;
		};
		
		class short : close {
			showToPlayer = false;
		};
		
		class medium : close {
			showToPlayer = false;
		};
		
		class far : close {
			showToPlayer = false;
		};
	};
	
	class GAU12 : CannonCore {
		class manual : CannonCore {
			sound[] = {"\Ca\sounds\Weapons\cannon\A10vulcanVII", 0, 1, 1100};
			soundContinuous = 0;
			showToPlayer = false;
			soundBurst = 0;
			autoFire = true;
		};
		
		class close : manual {
			sound[] = {"\SOW_Sounds\Guns\f_gau12.wss", 0, 1, 3000};
			showToPlayer = true;
			soundBurst = 1;
			autoFire = false;
		};
		
		class short : close {
			showToPlayer = false;
		};
		
		class medium : close {
			showToPlayer = false;
		};
		
		class far : close {
			showToPlayer = false;
		};
	};
	
	class 2A42 : CannonCore {
		class LowROF : Mode_FullAuto {
			sound[] = {"\SOW_Sounds\Guns\f_2a42.wss", 0, 1, 1200};
			soundContinuous = 0;
		};
		
		class HighROF : LowROF {
			sound[] = {"\SOW_Sounds\Guns\f_2a42.wss", 0, 1, 1200};
			soundContinuous = 0;
		};
		
		class close : HighROF {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class short : close {};
		
		class medium : LowROF {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class far : medium {};
	};
	
	class 2A72 : CannonCore {
		soundContinuous = 0;
		
		class manual : CannonCore {
			sound[] = {"\SOW_Sounds\Guns\f_2a42.wss", 0, 1, 1200};
			soundContinuous = 0;
			showToPlayer = true;
		};
		
		class close : manual {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class M242 : CannonCore {
		class LowROF : Mode_FullAuto {
			sound[] = {"\SOW_Sounds\Guns\f_m242.wss", 0, 1, 1200};
			soundContinuous = 0;
		};
		
		class HighROF : LowROF {};
		
		class close : HighROF {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class short : close {};
		
		class medium : LowROF {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class far : medium {};
	};
	
	class YakB : MGun {
		class manual : MGun {
			sound[] = {"\SOW_Sounds\Guns\f_yakb_1.wss", 0, 1, 1200};
			soundContinuous = 0;
			showToPlayer = false;
			soundBurst = 0;
			autoFire = true;
		};
		
		class close : manual {
			sound[] = {"\SOW_Sounds\Guns\f_yakb_2.wss", 0, 1, 1200};
			showToPlayer = true;
			soundBurst = 1;
			autoFire = false;
		};
		
		class short : close {
			showToPlayer = false;
		};
		
		class medium : close {
			showToPlayer = false;
		};
		
		class far : close {
			showToPlayer = false;
		};
	};
	
	class GSh23L : CannonCore {
		class manual : CannonCore {
			sound[] = {"\Ca\sounds\Weapons\cannon\gsh301", db10, 1, 1200};
			soundContinuous = 0;
			showToPlayer = true;
		};
		
		class close : manual {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class GSh301 : CannonCore {
		sound[] = {"\SOW_Sounds\Guns\f_gsh301.wss", 0, 1, 1200};
		soundContinuous = 0;
		soundBurst = 1;
		autoFire = false;
	};
	
	class GSh302 : CannonCore {
		class manual : CannonCore {
			sound[] = {"\SOW_Sounds\Guns\f_kpvt.wss", 0, 1, 1200};
			soundContinuous = 0;
			showToPlayer = true;
		};
		
		class close : manual {
			showToPlayer = false;
			soundBurst = 0;
		};
		
		class short : close {};
		
		class medium : close {};
		
		class far : close {};
	};
	
	class AGS30 : MGun {
		sound[] = {"\SOW_Sounds\Guns\f_ags30.wss", 0, 1, 1000};
		drySound[] = {"\SOW_Sounds\Guns\e_m2.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m2.wss", 0, 1, 20};
		reloadSound[] = {"\SOW_Sounds\Guns\sc_mg_b.wss", 0, 1, 20};
	};
	
	class AGS17 : AGS30 {};
	
	class MK19 : MGun {
		sound[] = {"\SOW_Sounds\Guns\f_mk19.wss", 0, 1, 1000};
		drySound[] = {"\SOW_Sounds\Guns\e_m2.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_m2.wss", 0, 1, 20};
		reloadSound[] = {"\SOW_Sounds\Guns\sc_mg_b.wss", 0, 1, 20};
	};
	
	class M119 : CannonCore {
		sound[] = {"\SOW_Sounds\Guns\f_m119.wss", 0, 1, 1500};
		reloadSound[] = {"\SOW_Sounds\Guns\r_d30.wss", 0, 1, 20};
	};
	
	class M256 : CannonCore {
		sound[] = {"\SOW_Sounds\Guns\f_m256.wss", 0, 1, 1500, "reloadSound[] = {""\ca\Sounds\weapons\cannon\gun120reload""", 0, 1, 20};
	};
	
	class D30 : CannonCore {
		sound[] = {"\SOW_Sounds\Guns\f_d30.wss", 0, 1, 1500};
		reloadSound[] = {"\SOW_Sounds\Guns\r_d30.wss", 0, 1, 20};
	};
	
	class D81 : CannonCore {
		sound[] = {"\SOW_Sounds\Guns\f_d81.wss", 0, 1, 1500};
		reloadSound[] = {"\ca\Sounds\weapons\cannon\gun125reload", 0, 1, 20};
	};
	
	class ZiS_S_53 : CannonCore {
		sound[] = {"\SOW_Sounds\Guns\f_2a70.wss", 0, 1, 1500};
		reloadSound[] = {"\ca\Sounds\weapons\cannon\gun73reload", 0, 1, 20};
	};
	
	class 2A46M : D81 {};
	
	class M252 : CannonCore {
		sound[] = {"\SOW_Sounds\Guns\f_m252.wss", 0, 1, 1000};
		reloadSound[] = {"\Ca\sounds\Weapons\cannon\mortar_load", 0, 1, 12};
	};
	
	class 2B14 : CannonCore {
		sound[] = {"\SOW_Sounds\Guns\f_2b14.wss", 0, 1, 1000};
		reloadSound[] = {"\Ca\sounds\Weapons\cannon\mortar_load", 0, 1, 12};
	};
	
	class RocketPods : LauncherCore {};
	
	class FFARLauncher : RocketPods {
		magazines[] = {"38Rnd_FFAR", "28Rnd_FFAR"};
		modes[] = {"Far_AI", "Burst"};
		
		class Far_AI : RocketPods {
			sound[] = {"\SOW_Sounds\Guns\f_ffar.wss", 0, 1, 1000};
			soundContinuous = 0;
			autoFire = false;
			showToPlayer = false;
		};
		
		class Burst : RocketPods {
			soundContinuous = 0;
			sound[] = {"\SOW_Sounds\Guns\f_ffar.wss", 0, 1, 1000};
		};
	};
	
	class FFARLauncher_14 : FFARLauncher {};
	
	class CamelGrenades : RocketPods {};
	
	class 57mmLauncher : RocketPods {
		class Far_AI : RocketPods {
			sound[] = {"\SOW_Sounds\Guns\f_s5.wss", 0, 1, 1000};
			showToPlayer = false;
		};
		
		class Burst : RocketPods {
			sound[] = {"\SOW_Sounds\Guns\f_s5.wss", 0, 1, 1000};
			soundContinuous = 0;
		};
	};
	
	class 57mmLauncher_64 : 57mmLauncher {};
	
	class 57mmLauncher_128 : 57mmLauncher {};
	
	class 80mmLauncher : RocketPods {
		class Far_AI : RocketPods {
			sound[] = {"\SOW_Sounds\Guns\f_s8.wss", 0, 1, 1000};
			showToPlayer = false;
		};
		
		class Burst : RocketPods {
			sound[] = {"\SOW_Sounds\Guns\f_s8.wss", 0, 1, 1000};
			soundContinuous = 0;
		};
	};
	
	class S8Launcher : 80mmLauncher {};
	
	class MissileLauncher : LauncherCore {};
	
	class SidewinderLaucher : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_aim9.wss", 0, 1, 1000};
	};
	
	class SidewinderLaucher_F35 : SidewinderLaucher {};
	
	class SidewinderLaucher_AH1Z : SidewinderLaucher {};
	
	class AT5Launcher : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_at5.wss", 0, 1, 1000};
	};
	
	class AT5LauncherSingle : AT5Launcher {};
	
	class 2A46MRocket : AT5Launcher {
		sound[] = {"\SOW_Sounds\Guns\f_2a46r.wss", 0, 1, 1000};
	};
	
	class AT10LauncherSingle : AT5Launcher {
		sound[] = {"\SOW_Sounds\Guns\f_at10.wss", 0, 1, 1000};
	};
	
	class AT11LauncherSingle : AT5Launcher {
		sound[] = {"\SOW_Sounds\Guns\f_at10.wss", 0, 1, 1000};
	};
	
	class AT13LauncherSingle : AT11LauncherSingle {
		sound[] = {"\SOW_Sounds\Guns\f_at10.wss", 0, 1, 1000};
	};
	
	class TOWLauncher : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_tow.wss", 0, 1, 1000};
	};
	
	class TOWLauncherSingle : TOWLauncher {};
	
	class HellfireLauncher : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_hellfire.wss", 0, 1, 1000};
	};
	
	class VikhrLauncher : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_vikhr.wss", 0, 1, 1000};
	};
	
	class BombLauncher : RocketPods {
		sound[] = {"\SOW_Sounds\Guns\f_gbu.wss", 0, 1, 20};
	};
	
	class BombLauncherF35 : BombLauncher {};
	
	class BombLauncherA10 : BombLauncher {};
	
	class SEARCHLIGHT : MGun {};
	
	class CarHorn : Default {
		drySound[] = {"\ca\Weapons\Data\Sound\car_horn_v1", 3.16228, 1, 400};
	};
	
	class BikeHorn : CarHorn {
		drySound[] = {"\ca\weapons\Data\Sound\bicycle_ring_v1", 0.01, 1, 80};
	};
	
	class TruckHorn : CarHorn {
		drySound[] = {"\ca\Weapons\Data\Sound\truck_horn_v1", 10.0, 1, 400};
	};
	
	class TruckHorn2 : CarHorn {
		drySound[] = {"\ca\Weapons\Data\Sound\truck_horn_v2", 10.0, 1, 400};
	};
	
	class SportCarHorn : CarHorn {
		drySound[] = {"\ca\Weapons\Data\Sound\Skoda_horn_v1", 3.16228, 1, 300};
	};
	
	class MiniCarHorn : CarHorn {
		drySound[] = {"\Ca\weapons\Data\Sound\minicar_horn_v1", 3.16228, 1, 300};
	};
	
	class R73Launcher : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_vikhr.wss", 0, 1, 1000};
	};
	
	class R73Launcher_2 : R73Launcher {};
	
	class Ch29Launcher : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_ch29.wss", 0, 1, 1000};
	};
	
	class Ch29Launcher_Su34 : Ch29Launcher {};
	
	class 2A70Rocket : 2A46MRocket {
		sound[] = {"\SOW_Sounds\Guns\f_2a70r.wss", 0, 1, 1000};
	};
	
	class 2A70 : D81 {
		sound[] = {"\SOW_Sounds\Guns\f_2a70.wss", 0, 1, 1000};
	};
	
	class AT6Launcher : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_at5.wss", 0, 1, 1000};
	};
	
	class AT9Launcher : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_at5.wss", 0, 1, 1000};
	};
	
	class AT2Launcher : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_at5.wss", 0, 1, 1000};
	};
	
	class HeliBombLauncher : RocketPods {
		sound[] = {"\SOW_Sounds\Guns\f_gbu.wss", 0, 1, 25};
	};
	
	class AirBombLauncher : HeliBombLauncher {};
	
	class Mk82BombLauncher : RocketPods {
		sound[] = {"\SOW_Sounds\Guns\f_gbu.wss", 0, 1, 50};
	};
	
	class Mk82BombLauncher_6 : Mk82BombLauncher {};
	
	class StingerLaucher : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_stinger.wss", 0, 1, 1000};
	};
	
	class StingerLauncher_twice : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_stinger.wss", 0, 1, 1000};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_aapod.wss", 0, 1, 20};
	};
	
	class AALauncher_twice : StingerLauncher_twice {};
	
	class Igla_twice : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_strela.wss", 0, 1, 1000};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_aapod.wss", 0, 1, 20};
	};
	
	class MaverickLauncher : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_hellfire.wss", 0, 1, 1000};
	};
	
	class 9M311Laucher : MissileLauncher {
		sound[] = {"\SOW_Sounds\Guns\f_strela.wss", 0, 1, 1000};
	};
	
	class SPG9 : RocketPods {
		sound[] = {"\SOW_Sounds\Guns\f_spg9.wss", 0, 1, 1500};
		drySound[] = {"\SOW_Sounds\Guns\e_rpg7v.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_rpg7v.wss", 0, 1, 20};
	};
	
	class GRAD : RocketPods {
		sound[] = {"\SOW_Sounds\Guns\f_grad.wss", 0, 1, 1000};
		drySound[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_rpg7v.wss", 0, 1, 20};
		soundContinuous = 0;
		soundBurst = 0;
	};
	
	class MLRS : RocketPods {
		sound[] = {"\SOW_Sounds\Guns\f_mlrs.wss", 0, 1, 1000};
		drySound[] = {"\SOW_Sounds\Misc\null.wss", 0, 1, 10};
		reloadMagazineSound[] = {"\SOW_Sounds\Guns\r_rpg7v.wss", 0, 1, 20};
		soundContinuous = 0;
		soundBurst = 0;
	};
};
