// config.bin - 13:29:29 06/17/17, generated in 1.34 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define true	1
#define false	0

#include "CfgPatches.hpp"
#include "CfgAddons.hpp"
#include "CfgWhistleSound.hpp"
#include "CfgSounds.hpp"
#include "CfgSFX.hpp"
#include "CfgEnvSounds.hpp"
#include "CfgWorlds.hpp"
#include "CfgAmmo.hpp"
#include "Mode_SemiAuto.hpp"
#include "Mode_Burst.hpp"
#include "Mode_FullAuto.hpp"
#include "cfgWeapons.hpp"
#include "CfgVehicles.hpp"
#include "CfgMovesBasic.hpp"
#include "CfgMovesMaleSdr.hpp"
